### ISSUE TITLE
[BUG] Wordlist removal doesn't work after job stop

### ISSUE THREAD

**Issue by XazkerBoy** [openbullet/OpenBullet2#10]
**Steps to reproduce:**

1. Upload new wordlist
2. Start a new job with it (and any config)
3. Stop or abort a job (at this point deleting no longer works)
4. Try to delete the wordlist FROM DISK

Error in the console:
`fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]                                                        Unhandled exception in circuit 'sBhh3SnBf9FBEkX8Kic4o4Ups_QXDIU8zyaoWBGk08A'.                                           System.IO.IOException: The process cannot access the file 'C:\Users\Xazker\Desktop\OpenBullet2\UserData\Wordlists\e4492ed6-5f5b-43c3-a168-5e21198e8340.txt' because it is being used by another process.                                           at System.IO.FileSystem.DeleteFile(String fullPath)                                                                     at System.IO.File.Delete(String path)                                                                                   at OpenBullet2.Repositories.HybridWordlistRepository.Delete(WordlistEntity entity, Boolean deleteFile) in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Repositories\HybridWordlistRepository.cs:line 64                                  at OpenBullet2.Pages.Wordlists.DeleteWordlist() in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Pages\Wordlists.razor.cs:line 165                                                                                                        at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)                        at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

Also, there is such a warning:
`warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]                                                     Unhandled exception rendering component: The process cannot access the file 'C:\Users\Xazker\Desktop\OpenBullet2\UserData\Wordlists\e4492ed6-5f5b-43c3-a168-5e21198e8340.txt' because it is being used by another process.                      System.IO.IOException: The process cannot access the file 'C:\Users\Xazker\Desktop\OpenBullet2\UserData\Wordlists\e4492ed6-5f5b-43c3-a168-5e21198e8340.txt' because it is being used by another process.                                           at System.IO.FileSystem.DeleteFile(String fullPath)                                                                     at System.IO.File.Delete(String path)                                                                                   at OpenBullet2.Repositories.HybridWordlistRepository.Delete(WordlistEntity entity, Boolean deleteFile) in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Repositories\HybridWordlistRepository.cs:line 64                                  at OpenBullet2.Pages.Wordlists.DeleteWordlist() in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Pages\Wordlists.razor.cs:line 165                                                                                                        at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)                        at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

**Screenshot**
https://prnt.sc/10gsacd

**OS Information:**

- OS: Windows 10 LTSC
- Browser: Mozilla Firefox 86.0
- Version 0.1.0

**Comment by Laiteux** [comment]
Thanks for your report!

My commit will fix the exact described issue (deleting after stop/abort), but deleting a wordlist while a job is running remains an issue.

@openbullet maybe we could prevent deleting a wordlist if a running job is using it?

**Comment by openbullet** [comment]
@Laiteux yes we can definitely do that
