### ISSUE TITLE
[Bug]: 0.3.0 Accessing Remotely Doesn't work

### ISSUE THREAD

**Issue by Vylixus** [openbullet/OpenBullet2#1003]
### Version of the software

0.3.0

### Operating system

Windows 10 Server 2019/2022

### Browser / Native

Latest Chrome

### What happened?

I have turned off firewall on my rdp, allowed port 5000, and allowed the openbullet web exe itself to firewall. On 0.2.4 this works fine and lets me access it remotely by <my rdp ip>:5000 but on the new 0.3.0 version the port stays closed when scanning and doesn't let me access remotely.

**Comment by openbullet** [comment]
Hello, have you started OB2 using the `--urls "http://*:5000"` flag? Does it say it's listening to localhost/127.0.0.1 only?

**Comment by Vylixus** [comment]
Hi, no I didn't but that fixed the issue. Just ran `openbullet2.web.exe --urls "http://*:5000` while in the openbullet directory and it worked!

**Comment by openbullet** [comment]
I'm glad it worked. Remember to set an admin password and require admin login from the security settings, otherwise anybody will be able to access your instance.
