### ISSUE TITLE
[BUG] Block Script | 2 bugs

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#102]
**Describe the bug**
i bypass this part

**To Reproduce**
First Bug
1. create a block script (Lint or Node)
2. write your code, and execute it => the script file will be generated
3. edit the code, and run it again => another file will be generated with a new name
Can you do something to prevent the generation of new files for every edition

Now, the second Bug
1. delete the generated file from the /Scripts folder
2. execute the code, and still you will see a new execution, even if the file is gone

**Comment by openbullet** [comment]
First bug:
If the code of the script changes, I build a new one. I cannot know what the name of the old script was. So I cannot do anything about this.

Second bug:
See above, and also try to F5 in the folder maybe it recreated the file but your explorer doesn't see it yet.
