### ISSUE TITLE
[REQUEST] please add user controll group

### ISSUE THREAD

**Issue by UnknowUsername** [openbullet/OpenBullet2#103]
Hello, I`m really interested if You add config area selection per user! So I can set access for guest. Thanks!

**Comment by UnknowUsername** [comment]
Combobox of group type also, I got 20k of to check xD

**Comment by openbullet** [comment]
> 
> 
> Combobox of group type also, I got 20k of to check xD

I don't understand what you mean, please provide an example

**Comment by UnknowUsername** [comment]
> > Combobox of group type also, I got 20k of to check xD
> 
> I don't understand what you mean, please provide an example

I mean this https://i.imgur.com/KhW8Vdl.png
It shouldn`t show all groups in 1

**Comment by openbullet** [comment]
User blocked for posting illegal content, reply deleted and issue closed
