### ISSUE TITLE
[Bug]: Api sharing

### ISSUE THREAD

**Issue by Mert-Zengin** [openbullet/OpenBullet2#1034]
### Version of the software

3.0.0

### Operating system

Ubunut 24.00

### Browser / Native

Firefux

### What happened?

A bug happened!

On Sharing option when i select get random api key didn't made anything and i see on console "crypto.UUID not a function"

**Comment by openbullet** [comment]
Thanks for this. I overlooked the fact that `crypto.UUID` is only available in HTTPS contexts (which is what I used when developing, through a self-signed certificate). I will fix this in version 0.3.1.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
