### ISSUE TITLE
[Bug]: database filter

### ISSUE THREAD

**Issue by KE4NaS** [openbullet/OpenBullet2#1038]
### Version of the software

0.3.0

### Operating system

Windows 10

### Browser / Native

Chrome 126

### What happened?

the "database" part in your program has some problem because It is applied a filter decided by the program from 06/26/2024 09:14:43 - 07/03/2024 23:59:59 and in the url it shows this `http://localhost:5000/hits?minDate=2024-06-26T16:12:52.259Z&maxDate=2024-07-04T06:59:59.999Z&sortDescending=true` when I have the database from Aug 11, 2021, 3:56:55 PM to Jul 3, 2024, 9:07:55 AM while if I go to filter except that it doesn't work well the date selection because if I want things only from today from Jul 3, 2024, 5:24:01 AM to Jul 3, 2024, 9:07:55 AM I was able applying this filter 07/02/2024 17:00:00 - 07/04/2024 23:59:59 with this in the url `http://localhost:5000/hits?minDate=2024-07-03T00:00:00.000Z&maxDate=2024-07-05T06:59:59.000Z&sortDescending=true` the date in my computer IS (UTC-08:00) Pacific Time (US & Canada)

**Comment by openbullet** [comment]
A few things on this:
1. The `Z` in the dates means UTC, so the dates are always passed to the backend as UTC
2. By default, the software filters the last 2 weeks of hits
3. I don't really understand, by reading your issue, what the problem is. Can you please show, step by step, what you're doing, what happens and what you expect to happen? It would really help. Thanks.

**Comment by KE4NaS** [comment]
I wanted to have only none from Jul 3, 2024, 5:24:01 AM to Jul 3, 2024, 9:07:55 AM when I tried to filter from Jul 3, 2024 from 00:00:00 to 23:59:59 it shows nothing I looked in the manual you uploaded but there is nothing. now I noticed that the program in the home says 
```
Server Time
Thu, Jul 4, 2024 12:37 AM
```

**Comment by openbullet** [comment]
I'll look into it, thanks for reporting
