### ISSUE TITLE
[BUG] Problem with hits, shift works after pressing on hit

### ISSUE THREAD

**Issue by UnknowUsername** [openbullet/OpenBullet2#104]
Hello, I was tried several times to copy some of my hits result, I did it on 7 tries. I guess some problem with time request/response, because I litterally wait 1 second to do it, then it works

**Comment by UnknowUsername** [comment]
+ 
![image](https://user-images.githubusercontent.com/20859455/111080373-4004eb80-850f-11eb-86af-2cb2446ded16.png)

**Comment by openbullet** [comment]
Chrome prevents websites from accessing your clipboard if they don't use https so you have to either trust unsecure websites (in the options) or use something like ngrok
