### ISSUE TITLE
[BUG] File ReadLines doesn't work 

### ISSUE THREAD

**Issue by Swirlon** [openbullet/OpenBullet2#105]
**Describe the bug**
The mentioned block doesn't work for me at any time. Even if reading 2 lines

**To Reproduce**
Just try to specify the path and see. It only freezes the whole UI, no response.

**Comment by openbullet** [comment]
I tried and couldn't reproduce, it reads the file correctly for me :(
We need a way to reliably reproduce this, please try different files (close and reopen OB2 each time it freezes) and see if you can find a specific reason why this happens, thank you!

**Comment by openbullet** [comment]
Any update on this? Also, which OS are you using?
