### ISSUE TITLE
[Bug]: There are no button to run the debugger

### ISSUE THREAD

**Issue by priv2024** [openbullet/OpenBullet2#1068]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I am using the latest version of Openbullet 0.3.1 (it also occurs in 0.3.0).

When editing a Config, in the Stacker page and in the Debugger tab, I am able to define my settings (data, proxy and so on) but there are no "start" button like there was before 0.3.0

### Reproduction steps

1. Start OpenBullet 2 web client
2. Log in as the admin user
3. Navigate to Configs
4. Select any Config. If there are not then create a new config.
5. Go to Stacker page
6. There are no button to start the Debugger.

### What is the current bug behavior?

There are no button to start the debugger.

### What is the expected correct behavior?

There should be a button named "Run" or "Start" like there was before 0.3.0

### Version of the client

0.3.1 and 0.3.0

### Type of client

Web client

### Environment

```markdown
- OS: Arch Linux
- Virtualization: KVM
- Browser: Firefox 127
```

### Relevant screenshots or videos

![Capture d’écran du 2024-07-15 17-01-34](https://github.com/user-attachments/assets/370c9d79-9374-41b1-824f-5f0dbf3c0204)

**Comment by openbullet** [comment]
Can you please press F12 to open the browser console (or sometimes CTRL + I) and see if there are errors in it? Because it might be due to an error. Also maybe try restarting OB2 or selecting another config and then reselecting the old one

**Comment by priv2024** [comment]
I solved the problem by changing my nginx configuration to allow websockets because I saw errors in the console saying that the connection was failing.
