### ISSUE TITLE
[Bug]: OB2 Updater fails with Unhandled Exception

### ISSUE THREAD

**Issue by frozen905** [openbullet/OpenBullet2#1075]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Tried using the auto-update feature in my OB 0.2.5 installation after it alerts me of an update, but both running Updater.exe manually, or the dotnet ./Updater.dll both fail with Unhandled Exception error:

![image](https://github.com/user-attachments/assets/b859a5f3-46cd-4963-807c-f239492b6e14)

I really am dreading having to do a fresh install of the new version in a new folder from scratch as I'm going to lose the history that was in my previous installation..  So I am still stuck on 0.2.5 for now.

Is there any way to bypass this error and let it successfully self update?

### Reproduction steps

Try to auto-update in 0.2.5, it fails.

### What is the current bug behavior?

Update failed, Unhandled Exception:

![image](https://github.com/user-attachments/assets/868ae646-febc-4420-954c-7816817bfea1)

### What is the expected correct behavior?

To correctly self-update

### Version of the client

0.2.5

### Type of client

Web client

### Environment

```markdown
- OS: Windows 10, Windows 11
- Virtualization: VMware
- Browser: Edge
```

### Relevant screenshots or videos

![image](https://github.com/user-attachments/assets/a378b29f-8f28-4035-9814-f13bfc3b9e47)

**Comment by openbullet** [comment]
Hello, please find the instructions here https://discourse.openbullet.dev/t/openbullet-2-release-0-3-0/7994

You cannot update from 0.2.x to 0.3.x using the old updater, you need to redownload the new updater to an empty folder, download the new build through it, and then copy over the `UserData` folder to retain all of your settings and data.
