### ISSUE TITLE
[Bug]:  OB2 WEB 0.3.1 CLOSES ON IT OWN 

### ISSUE THREAD

**Issue by chrislefron** [openbullet/OpenBullet2#1079]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Unhandled exception. System.Net.NetworkInformation.NetworkInformationException (0x80004005): An error was encountered while querying information from the operating system.
—> System.AggregateException: One or more errors occurred. (An error was encountered while querying information from the operating system.)
—> System.Net.NetworkInformation.NetworkInformationException (0x80004005): An error was encountered while querying information from the operating system.
at System.Net.NetworkInformation.BsdNetworkInterface…ctor(String name, Int32 index)
at System.Net.NetworkInformation.BsdNetworkInterface.Context.GetOrCreate(Byte* pName, Int32 index)
at System.Net.NetworkInformation.BsdNetworkInterface.ProcessLinkLayerAddress(Void* pContext, Byte* ifaceName, LinkLayerAddressInfo* llAddr)
— End of inner exception stack trace —
at System.Net.NetworkInformation.BsdNetworkInterface.GetBsdNetworkInterfaces()
at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
at System.Net.NetworkInformation.NetworkChange.OnAddressChanged(IntPtr store, IntPtr changedKeys, IntPtr info)
zsh: abort dotnet ./OpenBullet2.Web.dll

### Reproduction steps

nn

### What is the current bug behavior?

When OB2 start working after a hour/s stop working 

### What is the expected correct behavior?

nn

### Version of the client

0.3.1

### Type of client

Web client

### Environment

```markdown
- OS: MacOS 12.7.5 (21H1222)
- Virtualization:
- Browser: Chrome Version 126.0.6478.183
```

**Comment by openbullet** [comment]
It seems like it's an issue with other pieces of software too, possibly related to the .NET runtime on MacOS.

https://emby.media/community/index.php?/topic/126585-arm-version-crashing-every-few-days/

I'm pretty sure the code that causes this is the following

https://github.com/openbullet/OpenBullet2/blob/master/OpenBullet2.Web/Services/PerformanceMonitorService.cs#L143-L159

For now I'll try to add a try/catch statement around it, I hope it will work, otherwise I will have to disable network I/O stats for macOS as a whole.
