### ISSUE TITLE
Bug parsing in JSON [BUG]

### ISSUE THREAD

**Issue by beer15** [openbullet/OpenBullet2#108]
**Describe the bug**

I will put the error in the image

When you parse a json token with jtoken and the recursive option is activated while there is no recurrence an error occurs in a variable 

The only way to avoid the error is to disable the recursive option 

**To Reproduce**
Parse JSON with JToken

**Expected behavior**
fix

![b244eba9ade181d1ec1ef1fb25d47b78](https://user-images.githubusercontent.com/50250811/111217388-cdab0e80-85d5-11eb-85bb-bbe6accdd306.png)

**Comment by openbullet** [comment]
You are just trying to use a List variable as a single string. If your list is called `myList` Use `<myList[0]>` to get the first value. This is not an issue with OB2, it's an issue with how you pass variables.
