### ISSUE TITLE
[REQUEST]: Add Turnstile Option 3 from capmonster.cloud

### ISSUE THREAD

**Issue by mastercho** [openbullet/OpenBullet2#1089]
### This feature request respects the following points:

- [X] This is a **feature request**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) _(I've searched it)_.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single feature request; If you have multiple feature request, kindly create separate reports for each one.

### Description of the feature request

Would be good to add Turnstile option 3 from [capmonster.cloud](https://docs.capmonster.cloud/docs/captchas/tunrstile-task/)  and https://docs.capsolver.com/guide/antibots/cloudflare_turnstile.html (currently under maintenance) for sites who dont know all turnstile params available 

### Is your feature request related to a problem

No

### Describe the solution you'd like

.

### Describe alternatives you've considered

Alternatives can be done with HTTP requests

### Relevant screenshots or videos

.

### Additional information

.

**Comment by openbullet** [comment]
URL to test: https://2captcha.com/demo/cloudflare-turnstile-challenge
