### ISSUE TITLE
AES Encryption

### ISSUE THREAD

**Issue by AfMarwen** [openbullet/OpenBullet2#109]
Please work on the AES Encryption 

++ Add to us the option to put a **base64 value** or a **utf8 value** ( Of Key & IV)
++ Add to us the option of select the Key-Size ( Example: **128 / 8** * **256** * **512** ....etc) dont make it default ( this type of encryption is required to choose the option of encryption, because some websites work with different key size

Thank you

**Comment by openbullet** [comment]
I am not going to do number 1 as you just need to convert manually or through an additional block, but I will do number 2
