### ISSUE TITLE
Loli files error on job start

### ISSUE THREAD

**Issue by l3lack-eyes** [openbullet/OpenBullet2#1092]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When starting a job with open bullet 1 Configs (loli) it says world list type is not accepted by Config which I have tested all types of word lists and it errors the same

### Reproduction steps

1. Test

### What is the current bug behavior?

Word list not accepted by config

### What is the expected correct behavior?

Accepts the word list 

### Version of the client

0.3.2

### Type of client

Web client

### Environment

```markdown
- OS:linux
- Virtualization:kvm
- Browser:chrome
```

**Comment by openbullet** [comment]
Hello, are you sure your wordlist type is one of the allowed ones in the config? Please have a look at the docs

https://docs.openbullet.dev/docs/wordlists/general-info

https://docs.openbullet.dev/docs/wordlists/using-a-wordlist

**Comment by l3lack-eyes** [comment]
Yes I have checked all types of Configs and word lists .
Loli files have this problem opk s are working fine .
Thank you for your response .

**Comment by openbullet** [comment]
Alright, we will check it out. @l3lack-eyes can you please take a screenshot of what you see in the config settings in the Data section (the allowed wordlist types) and what you have in the Environment.ini file, so we have a way to easily reproduce your setup? Thanks.

**Comment by l3lack-eyes** [comment]
thank you for your response!
problem solved.
i've checked section you wrote here and it was "mailpass" so i changed it to "credentials" and its working fine now
![Uploading Screenshot 2024-08-10 164330.png…]()
