### ISSUE TITLE
[BUG] HTTP 2.0 Not working

### ISSUE THREAD

**Issue by styles977** [openbullet/OpenBullet2#11]
in HTTP version tab if i Put the digit/string "2" then it says "[Executing block Http Request] Version string portion was too short or too long. (Parameter 'input')"

And If I put the string "2.0" .. it says "[Executing block Http Request] HTTP/2.0 not supported yet" 

I donot know if OB2 support HTTP 2.0 protocol ... right now it is not.

**Comment by Laiteux** [comment]
Hello,

HTTP 2.0 is not supported by OB2 at the moment, this error is thrown on purpose: https://github.com/openbullet/OpenBullet2/blob/245683ffdf55e9a3641fee8de4eba2bc5b53b1bd/RuriLib.Http/Models/HttpRequest.cs#L60

**Comment by openbullet** [comment]
You can still make requests with HTTP/2.0 by using the default HTTP client (through C# code) because that one supports it, but it's a lot trickier to do as there isn't a block for it at the moment.
