### ISSUE TITLE
[BUG] CPU/RAM  ISSUE MEMORY GOING SLOWLY UP TO UNLIMITED

### ISSUE THREAD

**Issue by charliebishoptm** [openbullet/OpenBullet2#111]
**Describe the bug**

**To Reproduce**
1. Load config
2. Watch memory of OB2 slowly growing to unlimited(cpu having issues too sometimes)
3. Had same issue on ubuntu and cent os with several configs now,tested on huge spec also even with 1 job with 50 runners it will still go up and up till it gets killed eventually

**Comment by openbullet** [comment]
1. Do you perhaps have "Enable bot logging" ticked in RL Settings?
2. How many bots are you using? Did you try lowering them?
3. Did you test on windows as well?
4. Do you have heavy I/O operations (writing or reading files) in your configs?
5. Which hit output are you using in your jobs? DB or file system?

**Comment by charliebishoptm** [comment]
I figured this out,it was because of broken configs mainly...
  I was getting many tocheck hits and that was making ram usage grow constantly till 100% even 12gb ram usage for 50 threads, only tested in linux no logging and database output,everyhing is ok with good configs!

Thank you for your amazing work!!
