### ISSUE TITLE
[Bug]: Proxy Not working

### ISSUE THREAD

**Issue by parvinders347** [openbullet/OpenBullet2#1119]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After Upgrading to the latest openbullet 2 proxy is not working.

### Reproduction steps

1. Started Ob 2. Imported Proxies 3. Checked Proxies 4. Proxies not working

### What is the current bug behavior?

Not a single proxy working, i have checked the proxies its working

### What is the expected correct behavior?

Work Proxies Properly

### Version of the client

0.3.2

### Type of client

Native client

### Environment

```markdown
- OS: Windows 10
- Virtualization: Enabled
- Browser: Firefox
```

### OpenBullet2 logs

```shell
Empty Logs
```

### Relevant screenshots or videos

![fvdf](https://github.com/user-attachments/assets/a09dc5a1-2d4f-4e96-879f-036d9538c350)

**Comment by openbullet** [comment]
1. Are you sure you imported them with the correct type?
2. Do they use credentials?
3. What service are the proxies from? Or are they free proxies?
4. Have you tested that they work with a separate tool? Which one? Did you test from the same machine and same IP as OB2?
5. Which version of OB2 were you using before when it was working?

**Comment by RifHut** [comment]
If you don't import the proxy in this format IP:PORT
, it won't work.

**Comment by DevourerOfG0DS** [comment]
I have been having the same problem. Got a workaround for it, delete the job to check proxies in the jobs tab and make a new one and check your proxies. It worked for me hope it does for you

**Comment by DevourerOfG0DS** [comment]
> I have been having the same problem. Got a workaround for it, delete the job to check proxies in the jobs tab and make a new one and check your proxies. It worked for me hope it does for you

if you make a new job to check proxies and the target website is google remove title> in the success key window. hope it works

**Comment by daradals** [comment]
same problem with web client, checking IP:PORT all dead, checking in another site, a lot alive

**Comment by parvinders347** [comment]
when i try with duckduckgo.com its working but when i do with google.com its shows proxy not working

**Comment by openbullet** [comment]
> when i try with duckduckgo.com its working but when i do with google.com its shows proxy not working

Then it means google is blocking the proxy, it's not an OB2 issue.

**Comment by onlybluebandzz** [comment]
"when i try with duckduckgo.com its working but when i do with google.com its shows proxy not working"

so what would I enter in the success key section??
