### ISSUE TITLE
[BUG] SCRIPT Indentation Problem [expected an indented block error]

### ISSUE THREAD

**Issue by oynomed** [openbullet/OpenBullet2#113]
A working SCRIPT broke after changing stacker to lolicode and vice versa, OB2 removes all indentation of the scripts.

**Comment by qMMMp** [comment]
for now, all what you can do is:
minify your code
and problem solved

**Comment by openbullet** [comment]
I think he's having this problem in python where indentation is required. I'm not sure one can minify python

**Comment by PurityWasHere** [comment]
workaround is to save the script to a file and tell write a statement in C# telling ironpython to execute that file
