### ISSUE TITLE
[REQUEST]: Add get data network in selenium 

### ISSUE THREAD

**Issue by Duc-python** [openbullet/OpenBullet2#1135]
### This feature request respects the following points:

- [X] This is a **feature request**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) _(I've searched it)_.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single feature request; If you have multiple feature request, kindly create separate reports for each one.

### Description of the feature request

Can you add a block that adds get data network on selenium?

### Is your feature request related to a problem

I want that because it will do more things.

### Describe the solution you'd like

I would like to have this feature

**Comment by openbullet** [comment]
Hello, what exactly would this block do? What would be the inputs / outputs? Please write out your ideas and we'll see how to best design something like that.

**Comment by Duc-python** [comment]
> Hello, what exactly would this block do? What would be the inputs / outputs? Please write out your ideas and we'll see how to best design something like that.

IDK :0

**Comment by openbullet** [comment]
Closing stale issue
