### ISSUE TITLE
[REQUEST] AES configurable key size

### ISSUE THREAD

**Issue by fairysubsteam** [openbullet/OpenBullet2#114]
**Is your feature request related to a problem? Please describe.**
OB2 uses a fixed Key Size at 256, and generally it is better to have a configurable key size for the use of AES CBC PKCS7 padding, like (128 / 8)
I thus see that having the ability to adjust the key size would be amazing.

**Describe the solution you'd like**
Implementation of a feature where we can adjust the key size ourselves.

**Describe alternatives you've considered**
Implementation of different PKCS padding such as PKCS5 and PKCS8 padding modes

**Additional context**
It has become a necessity for us to use configurable key sizes and/or other PKCS paddings other than the default PKCS7 padding.
And thank you in advance **Ruri**

**Comment by openbullet** [comment]
#109
As for the other paddings, I am only using what .NET offers, so wait until those are implemented in .NET
