### ISSUE TITLE
[BUG] Can`t make more then 1 script (breaks the tabulation of the python)

### ISSUE THREAD

**Issue by RiseFox** [openbullet/OpenBullet2#116]
When I create the second script, I break the first, make first (python) like a second (Jint)
With this have error, unreal to use diff languages scripts (+ breaks the tabulation of the python )

**Comment by openbullet** [comment]
For the tabulation see this issue https://github.com/openbullet/OpenBullet2/issues/113

**Comment by RiseFox** [comment]
@openbullet It`s a Joke? said about tabulations.... Minified not helping 200%
Can u add import script file? (u doing it in C# CodeBlock )

`ExecuteIronPyScript(data, tmp_rvwpkf, "Scripts/66c8ac26ebe6e672f991ce8ffac3c373.py");`

its a python, tabulations cant be Minified

**Comment by openbullet** [comment]
What's a joke?
#113 is still open as you can clearly see, which means it hasn't been fixed yet. What are you being salty about?

**Comment by RiseFox** [comment]
@RiseFox missed to add:
It`s a Stacker make a problem - deleting tabs when reopened as Stacker

**Comment by openbullet** [comment]
> 
> 
> @RiseFox missed to add:
> It`s a Stacker make a problem - deleting tabs when reopened as Stacker

I already fixed that, as you can see 
![immagine](https://user-images.githubusercontent.com/48930622/111345427-92641a80-867d-11eb-97f5-88cc0255e2b2.png)
if you go to that commit you will see the change
please learn how github works
