### ISSUE TITLE
[REQUEST] Add drag and drop option to wordlist and add a option to add multiple wordlists in both upload and filesystem

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#120]
[REQUEST] Add drag and drop option to wordlist and add a option to add multiple wordlists in both upload and filesystem

**Comment by openbullet** [comment]
You literally opened a similar issues a few days ago https://github.com/openbullet/OpenBullet2/issues/31

**Comment by Rohan4412s** [comment]
please add that option as soon as possible

**Comment by openbullet** [comment]
> 
> 
> please add that option as soon as possible

Everything takes time, I don't see this as a priority right now, bugfixes need to be addressed before anything else.
