### ISSUE TITLE
[REQUEST] Add a option if possible to convert .loli configs to .opk

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#121]
if its possible please add that option.

**Comment by openbullet** [comment]
This is not possible, the two systems are too different. Some people are making converters but they won't work for many configs, only for very simple ones. Look on the forum for more details.

**Comment by ShyamBhagat2004** [comment]
Hi, sorry but I couldn't find a place to convert .loli to .opk. Could someone please help  me out?

**Comment by openbullet** [comment]
@ShyamBhagat2004 you cannot do that. Period.
