### ISSUE TITLE
Captcha service ERROR[BUG]

### ISSUE THREAD

**Issue by LittlePrinceOB** [openbullet/OpenBullet2#122]
Captcha service ERROR.
I Bought Imagetypez Captcha service. I make config with puppeteer, But I got error: timeout.
Detail issues: https://discourse.openbullet.dev/t/captcha-service-error/1239
Thank you

**Comment by meinname** [comment]
As you provided no url or so i tried it with some other site:
![image](https://user-images.githubusercontent.com/16181408/111478787-aae13d00-8730-11eb-9b7b-7c62299107cd.png)
and also the screenshot in the forum post
![image](https://user-images.githubusercontent.com/16181408/111478847-b7fe2c00-8730-11eb-92e7-587bd9cceb32.png)

🤷 works for me

**Comment by LittlePrinceOB** [comment]
> As you provided no url or so i tried it with some other site:
> ![image](https://user-images.githubusercontent.com/16181408/111478787-aae13d00-8730-11eb-9b7b-7c62299107cd.png)
> and also the screenshot in the forum post
> ![image](https://user-images.githubusercontent.com/16181408/111478847-b7fe2c00-8730-11eb-92e7-587bd9cceb32.png)
> 
> 🤷 works for me

Check with this captcha: https://alonhadat.com.vn/CaptchaGenerator.ashx?t=kvd

**Comment by meinname** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16181408/111481068-e2e97f80-8732-11eb-9ec0-2b2c6a64634b.png">

**Comment by LittlePrinceOB** [comment]
Can you give me the code.

**Comment by meinname** [comment]
here the one i used:
`BLOCK:PuppeteerOpenBrowser
ENDBLOCK

BLOCK:PuppeteerNavigateTo
  url = "https://alonhadat.com.vn/CaptchaGenerator.ashx?t=kvd"
ENDBLOCK

BLOCK:PuppeteerScreenshotBase64
  findBy = Selector
  identifier = "body > img"
  => VAR @puppeteerScreenshotBase64Output
ENDBLOCK

BLOCK:PuppeteerCloseBrowser
ENDBLOCK

BLOCK:SolveImageCaptcha
  base64 = @puppeteerScreenshotBase64Output
  => CAP @solveImageCaptchaOutput
ENDBLOCK
`

**Comment by LittlePrinceOB** [comment]
I dont know why you did close browser block

**Comment by meinname** [comment]
just to make sure the browser gets closed after ther config ran - to have no dead browsers in background.
As i also set no status yet or so cause then i could just use this setting
<img width="474" alt="image" src="https://user-images.githubusercontent.com/16181408/111483079-c2222980-8734-11eb-962c-017d5f7ff3a2.png">

**Comment by LittlePrinceOB** [comment]
> just to make sure the browser gets closed after ther config ran - to have no dead browsers in background.
> As i also set no status yet or so cause then i could just use this setting
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/16181408/111483079-c2222980-8734-11eb-962c-017d5f7ff3a2.png">

Can You So Me how Can you Find   identifier = "body > img"
Because I Dont know. I just find form#form1 div.value > img

**Comment by meinname** [comment]
i gone to the page you gave me - clicked right and selected inspect element.
And then 
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/16181408/111485984-60af8a00-8737-11eb-85ea-46f3238b2908.png">

**Comment by LittlePrinceOB** [comment]
THANK YOU

**Comment by openbullet** [comment]
@LittlePrinceOB usually after an issue is solved we close the issue. Next time please do it.
