### ISSUE TITLE
[BUG] Variable name containing underscore aren't available in Script Block

### ISSUE THREAD

**Issue by AtlasZ-PM** [openbullet/OpenBullet2#124]
**Describe the bug**
When we pass a variable containing underscore in its name, that variable isn't available inside the Script Block.

**To Reproduce**
Check attached screenshot.

**Expected behavior**
Should be able to use that variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/80449894/111492981-2cea5980-8763-11eb-9d48-18c7d5118471.png)

**Comment by RiseFox** [comment]
@AtlasZ-PM make input and output strings with same name
