### ISSUE TITLE
[BUG] Changing bots from Job detail resumes the job without updating the UI

### ISSUE THREAD

**Issue by AtlasZ-PM** [openbullet/OpenBullet2#126]
**Describe the bug**
When we change the bots from Job detail, the job resumes but the buttons still shows Resume, Stop & Abort

**To Reproduce**
1. Create a New Job (Multi-Run or Proxy Check)
2. Start it
3. Pause it
4. Change bots from Job detail
5. The Job resumes but buttons still remain same

**Expected behavior**
Either it shouldn't resume the job or it should update the UI showing Pause, Stop & Abort buttons

**Additional Request**
When we Pause the job, Abort button isn't available when its pausing. Suppose there's a situation when all things goes to BAN and we accidentally press Pause then we aren't able to stop/abort the Job and need to close OB from terminal.
If possible please show Abort button when pausing also.

Also the timer for Elapsed & Remaining time doesn't stop on Pausing any Job

**Comment by openbullet** [comment]
@AtlasZ-PM I would really appreciate if you opened 2 separate issues for the other 2 things you asked
- When we Pause the job, Abort button isn't available when its pausing. Suppose there's a situation when all things goes to BAN and we accidentally press Pause then we aren't able to stop/abort the Job and need to close OB from terminal.
If possible please show Abort button when pausing also.
- Also the timer for Elapsed & Remaining time doesn't stop on Pausing any Job

**Comment by AtlasZ-PM** [comment]
Okay sure @openbullet . Sorry for lumping all into one.
I think someone already opened an issue for first point here #140 .
I will create separate issue for the second point. Thanks!
