### ISSUE TITLE
[REQUEST] Option to URL ENCODE the variable from PARSE Block itself

### ISSUE THREAD

**Issue by AtlasZ-PM** [openbullet/OpenBullet2#127]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to URL encode the parsed data to use in next requests. For that currently we need to add a separate block.

**Describe the solution you'd like**
It would be good if you can provide a URL encode option in parse block to get the variable in encoded format.

**Comment by beer15** [comment]
I wanted to ask this option yesterday lol good idea

**Comment by openbullet** [comment]
You can already do URL encoding on POST data, I don't think any further encoding options are needed in a parse block since you can just encode when you send
![immagine](https://user-images.githubusercontent.com/48930622/111534689-9325ab00-8768-11eb-8424-ab29ad0b196e.png)
