### ISSUE TITLE
[REQUEST] Possible to have Step by Step Debugging now?

### ISSUE THREAD

**Issue by AtlasZ-PM** [openbullet/OpenBullet2#128]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to check a config step by step to find out some problem in a config. Currently it just goes through all the blocks.

**Describe the solution you'd like**
I don't know if its possible to have a step by step debugging now as per the new system but it would be good if its possible.

**Comment by openbullet** [comment]
Note for myself when I try to do this in the future: there are 2 ways to approach this that I thought of so far.

### First option
Make it save the `ScriptState` from 1 block to the other (only works for blocks-only configs, doesn't work if there's lolicode or C# code) and use the `ContinueWith` but I already tried this in the past and had some problems.

### Second option
Manually insert some logic in every step of the code that waits for some external flag to be set before proceeding (with the ability to cancel the work to avoid infinite loops, maybe even cancel the token after a given time to avoid blocking a thread forever if the user refreshes the debugger page).
