### ISSUE TITLE
implement oauth and aws4 sig hash

### ISSUE THREAD

**Issue by pasterlevis** [openbullet/OpenBullet2#13]
implement oauth and aws4 sig hash

**Comment by openbullet** [comment]
Fairy made a guide for aws4
https://discourse.openbullet.dev/t/how-to-generate-an-aws4-signature-ob2/530

**Comment by openbullet** [comment]
And Br4uN made a plugin https://discourse.openbullet.dev/t/br4un-aws4-signatue-plugin/739
