### ISSUE TITLE
[BUG] Unable to Type Custom Headers Containing a Colon

### ISSUE THREAD

**Issue by aeruginascin** [openbullet/OpenBullet2#132]
**Describe the bug**
When pasting or typing headers containing a colon other than the one to separate name from value, OB behaves strangely. I believe it's trying to put a space after the colon automatically. I do not know why it deletes the lines.

**To Reproduce**
1. Create a new HTTP Request block.
2. Insert the following into the custom headers box. Pasting or typing manually results in the same thing.

```
    :authority: login.example.com
    :method: POST
    :path: /login
    :scheme: https
```

**Screenshots**
https://i.imgur.com/bXbMHGt.gif

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**Comment by openbullet** [comment]
Why would you write headers like these? These don't go in the headers box, they are shown by some HTTP debuggers just to help you see what was sent, they are not actual headers because they don't respect the syntax of valid headers.

**Comment by openbullet** [comment]
Authority is the Host header, method is the first word sent in the first line of the request e.g. `GET /login HTTP/1.1`, the path is the second word as you can see, and the scheme is just how you connect (if https connect over SSL otherwise if http connect normally). These are NOT valid headers and should not be sent as headers.

**Comment by aeruginascin** [comment]
> Authority is the Host header e.g. `Host: login.example.com`, method is the first word sent in the first line of the request e.g. `GET /login HTTP/1.1`, the path is the second word as you can see, and the scheme is just how you connect (if https connect over SSL otherwise if http connect normally). These are NOT valid headers and should not be sent as headers.

I see, I've been doing that wrong for a good while then. Do you have any links to where I could learn about this? Before posting this issue I attempted to find out exactly what they were but found nothing useful.

**Comment by aeruginascin** [comment]
https://tools.ietf.org/html/rfc7540
https://developers.google.com/web/fundamentals/performance/http2
![image](https://user-images.githubusercontent.com/73770150/111699583-514b4200-8806-11eb-90f5-fa9c714c9f4a.png)

I found these two resources, they're called pseudo-headers and they do seem to be valid headers in HTTP/2

**Comment by openbullet** [comment]
@aeruginascin As far as I can read those new headers are only supported in HTTP/2, which is currently not supported in OB2 to begin with, so maybe wait for https://github.com/openbullet/OpenBullet2/issues/88 to be implemented and then open a new issue to ask for this change, thanks!
