### ISSUE TITLE
[BUG] Drop-down list in Plugin getting Error

### ISSUE THREAD

**Issue by ep5tein** [openbullet/OpenBullet2#133]
Hi, I made a plugin using drop down list, when i lauch it in stacker i'm getting this error:
`[IDLE] CompilationErrorException: (3,37): error CS0103: The name ‘SheetLib’ does not exist in the current context
`

Here is my code:

[Methods.cs]
```
using SheetLib;
using RuriLib.Attributes;
using RuriLib.Logging;
using RuriLib.Models.Bots;

namespace GoogleSuite.Blocks.Functions
{
    [BlockCategory("GoogleSuite", "All functions for Google Suite", "#9acd32")]
    public static class Methods
    {
        [Block("SetRow/GetRow Format= A1, GetRange Format= A1:B5")]
        public static int GSheet(BotData data, string InputText, ListOption opt)
        {
            if (opt.Equals(0))
            {
                data.Logger.Log($"Entered: SetCell", LogColors.YellowGreen); ;
            }
            if (opt.Equals(1))
            {
                data.Logger.Log($"Entered: Getcell", LogColors.YellowGreen); ;
            }
            if (opt.Equals(2))
            {
               data.Logger.Log($"Entered: GetSheet", LogColors.YellowGreen); ;
            }
            if (opt.Equals(3))
            {
                data.Logger.Log($"Entered: GetRange", LogColors.YellowGreen); ;
            }
            data.Logger.Log($"Entered: {InputText} with option {opt}", LogColors.YellowGreen);
            return 0;
        }
    }
}
```
[SheetLib.cs]
```
namespace SheetLib
{
    public enum ListOption
    {
        SetCell = 0,
        GetCell = 1,
        GetSheet = 2,
        GetRange = 3
    }
}
```

Thanks 💯

**Comment by openbullet** [comment]
Can you confirm that `SheetLib.cs` is in your plugin project and not in a dependency? Have you tried adding a `custom using` in the config with the `SheetLib` namespace to see how it reacts?

**Comment by ep5tein** [comment]
SheetLib.cs was a dependency (added in .csproj of current project). I tried to put it directly on the same project like you said, and now it work perfectly fine.

**Comment by openbullet** [comment]
Yes enums in dependencies aren't supported, only the ones in the plugin itself. So if you need to use an enum that is in a dependency as a block parameter, just remake your own and then make a method to map it to the other enum inside the plugin to prevent this issue from happening
