### ISSUE TITLE
[REQUEST] Add multiple line in Test Data 

### ISSUE THREAD

**Issue by coolerspeex** [openbullet/OpenBullet2#135]
**Sometimes i need to check multiple creditianial.**
Because sometimes due knowing how many attempts after site stop and blacklist IP so its better to allow multiple line test data or create a multiline test data checkbox so it will be better

Thanks

**Comment by openbullet** [comment]
Sorry I am not going to do this as it requires a lot of effort for the little advantage it brings, just swap out the line manually when you need to.
