### ISSUE TITLE
[REQUEST] Add data view option in complete log debugger 

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#138]
please add an option for data view in complete log debugger and also if possible to add a search option because I know there is option ctrl + f but it selects all from the right data too?

add option that belowo
![wasd212Capture](https://user-images.githubusercontent.com/53138230/111666107-6a211b00-8839-11eb-8b6c-e15f1c9c0b94.PNG)

**Comment by openbullet** [comment]
I think you're looking for this

![immagine](https://user-images.githubusercontent.com/48930622/111674840-bad64b00-881c-11eb-9057-6db57b3b244a.png)

as for the custom search box, as said a thousand times, I'm not going to do it sorry
