### ISSUE TITLE
[BUG] Pausing any Job doesn't stop the Elapsed & Remaining Timer

### ISSUE THREAD

**Issue by AtlasZ-PM** [openbullet/OpenBullet2#142]
**Describe the bug**
When we press Pause button from Job page, the Elapsed & Remaining Timer under Other Stats keeps on running.

**To Reproduce**
1. Create a Job
2. Start it
3. Pause it
4. You can see that the Elapsed & Remaining Timer are still running

**Expected behavior**
The timers should also pause.

**Additional context**
Hope its just the timer problem.

**Comment by openbullet** [comment]
In order to do this we need to switch from a DateTime based `Elapsed` to a Stopwatch based one in

https://github.com/openbullet/OpenBullet2/blob/master/RuriLib.Parallelization/Parallelizer.cs#L61

**Comment by openbullet** [comment]
I fixed the elapsed time. The remaining time is fine like this, as it's based on the CPM value.

**Comment by YashvirGaming** [comment]
> I fixed the elapsed time. The remaining time is fine like this, as it's based on the CPM value.

hey buddy can you help me too, how do i add a time elapsed or timer counter in Openbullet
is there any FUNCTION BLOCK  

I want to add this timer in my Title 
here is an example 

TITLE "|| SuperFlix By YashvirGaming#7131 & Kinxy#0001 (Netflix API-3) || Matched: <GOOD> | Valids: <GOOD> | Invalids: <BAD> | Free: <CUSTOM(FREE)> | Retry Payment: <CUSTOM(Retry Payment)> | Checked: <CHECKED>/<COMBOLENGTH> | CPM: <CPM> | Retries: <RETRY> | Time Elapsed: <>"

**Comment by YashvirGaming** [comment]
> **Describe the bug** When we press Pause button from Job page, the Elapsed & Remaining Timer under Other Stats keeps on running.
> 
> **To Reproduce**
> 
>     1. Create a Job
> 
>     2. Start it
> 
>     3. Pause it
> 
>     4. You can see that the Elapsed & Remaining Timer are still running
> 
> 
> **Expected behavior** The timers should also pause.
> 
> **Additional context** Hope its just the timer problem.

pls help me me figure this too, see above brother.
is there that timer function in OB 1 or OB2 ?
they should implement that.
