### ISSUE TITLE
[BUG] inport blog problem

### ISSUE THREAD

**Issue by KokainUHD** [openbullet/OpenBullet2#146]
Hi, we can't test it in config when we create an input blog, because we can't test it, we can't find the name we gave to the openbullet2 input blog, and we get an error in short, the input does not come out in the config stacker section

**Comment by openbullet** [comment]
What the heck is an input blog? ^^ I'm guessing you mean custom inputs. Anyways I made a guide to clear things up https://discourse.openbullet.dev/t/how-to-use-custom-inputs/1352
