### ISSUE TITLE
[BUG] Memory Leak

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#149]
**Describe the bug**
When starting a job with a wordlist containing high number of data for a long period of time causes the pc to stuck.
At first - starting a job with high number of data will not have any issues, only later when it has progressed more it gets slower and slower until finally unresponsive at all.
Can't open task manager to show more details, because the entire PC is not responding, so I can't tell if it's the CPU or Memory or even Disk fault.
It doesn't matter if the browser is closed or open on the job details, result is the same.
(My guess - Probably because the program uses more and more memory without cleaning it every once in a while?)
Don't know if it's related - The only thing shown is: "fail: Microsoft.EntityFrameworkCore.Query[10100].

**To Reproduce**
1. Create a wordlist containing high number of data (for example: 4,000,000).
2. Start a job with the selected wordlist for a long period of time (for example 6 hours).
3. See error - PC become slower and slower untill unresponsive. If browser is open - Job details page of the UI is stuck on the reloading animation (white background with blue circle reloading).

**Expected behavior**
PC should be responsive all the time.

**Desktop (please complete the following information):**
 - OS: Windows 10 - 64bit
 - Browser Chrome
 - Version 0.1.7

**Comment by openbullet** [comment]
Please answer the following questions:
1. Are you getting a huge amount of hits?
2. Do you have bot logs enabled? If you do, can you turn them off?
3. How much RAM do you have available on your PC?
4. Which hits output are you using? If you're using database can you please switch to FileSystem and try again?

**Comment by ObsessedHacker** [comment]
> Please answer the following questions:
> 
> 1. Are you getting a huge amount of hits?
> 2. Do you have bot logs enabled? If you do, can you turn them off?
> 3. How much RAM do you have available on your PC?
> 4. Which hits output are you using? If you're using database can you please switch to FileSystem and try again?

1. No. Normal amount of hits.
2. No. Bot logs was and still is disabled.
3. 4GB.
4. HTTP Request on the config. Not using the database.

**Comment by openbullet** [comment]
@ObsessedHacker regarding number 4 I am referring to this section in the job options

![immagine](https://user-images.githubusercontent.com/48930622/111841397-352acc00-88fe-11eb-92d5-b208c9e118dd.png)

**Comment by ObsessedHacker** [comment]
> @ObsessedHacker regarding number 4 I am referring to this section in the job options
> 
> ![immagine](https://user-images.githubusercontent.com/48930622/111841397-352acc00-88fe-11eb-92d5-b208c9e118dd.png)

I am aware.
I clicked on "X" when creating the job.

**Comment by openbullet** [comment]
> 
> 
> > @ObsessedHacker regarding number 4 I am referring to this section in the job options
> > ![immagine](https://user-images.githubusercontent.com/48930622/111841397-352acc00-88fe-11eb-92d5-b208c9e118dd.png)
> 
> I am aware.
> I clicked on "X" when creating the job.

Ok perfect it was just because you mentioned Http Request so I wasn't sure we were on the same page ^_^ Alright I will look into this and see if I can replicate it.

**Comment by ObsessedHacker** [comment]
> > > @ObsessedHacker regarding number 4 I am referring to this section in the job options
> > > ![immagine](https://user-images.githubusercontent.com/48930622/111841397-352acc00-88fe-11eb-92d5-b208c9e118dd.png)
> > 
> > 
> > I am aware.
> > I clicked on "X" when creating the job.
> 
> Ok perfect it was just because you mentioned Http Request so I wasn't sure we were on the same page ^_^ Alright I will look into this and see if I can replicate it.

Don't know if it's related - Now when it crashed again, the only shown text is "warn: Microsoft.AspNetCore.Server.Kestrel[22]".

**Comment by ObsessedHacker** [comment]
Also - I noticed now when the progress is 99.86% (4301545/4308524) it doesn't finish it, it doesn't reach 100%.

**Comment by openbullet** [comment]
> 
> 
> Also - I noticed now when the progress is 99.86% (4301545/4308524) it doesn't finish it, it doesn't reach 100%.

That is a separate issue, I am aware of that but never found the cause as it's hard to debug (you need to run it for a very long time)

**Comment by openbullet** [comment]
> Edit - And now after I closed the program - on task manager I see 100% Disk usage from "Service Host: SysMain"

Are you using blocks like File Write or File Append in your config? They are known to have problems and hang the thread.

**Comment by ObsessedHacker** [comment]
> > Edit - And now after I closed the program - on task manager I see 100% Disk usage from "Service Host: SysMain"
> 
> Are you using blocks like File Write or File Append in your config? They are known to have problems and hang the thread.

No. Not using those blocks.

**Comment by openbullet** [comment]
> 
> 
> > > Edit - And now after I closed the program - on task manager I see 100% Disk usage from "Service Host: SysMain"
> > 
> > 
> > Are you using blocks like File Write or File Append in your config? They are known to have problems and hang the thread.
> 
> No. Not using those blocks.

Alright then this clearly looks like a memory leak somewhere. I will let you know if I find out more.

**Comment by sudo216** [comment]
IDK why the ram keeps increasing even without any usasge. When the ram get's to its limit it crashes.
Please fix this issue ASAP.

HOPING FOR POSTIVIE RESPONSE

**Comment by openbullet** [comment]
Please follow this guide and send me the `.gcdump` file, otherwise it's really hard to debug this issue to see where the memleak is coming from.
https://devblogs.microsoft.com/dotnet/collecting-and-analyzing-memory-dumps/

**Comment by sudo216** [comment]
> collecting-and-analyzing-memory-dumps/
iam trying to but idk
why it says 
root@98bbf7f42051:/home/coder/project# dotnet tool install --global dotnet-gcdump
Tool 'dotnet-gcdump' is already installed.
root@98bbf7f42051:/home/coder/project# pidof dotnet
13758
`root@98bbf7f42051:/home/coder/project# dotnet gcdump collect -p 13758
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-gcdump does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
root@98bbf7f42051:/home/coder/project# `

**Comment by openbullet** [comment]
@sudo216 if you have the chance to do this on windows, please try, as we also tried on linux but it was giving errors (we got past this part though, it had to do with the fact that `dotnet-gcdump` is not added to the path).

**Comment by meinname** [comment]
the tool is in your homedir in .dotnet/tools 

so best is to add
this to your ~/.bash_profile if your system is a non-sudo system.
export PATH="$PATH:/root/.dotnet/tools" 
if you have used sudo, then it is
export PATH="$PATH:/home/yourusername/.dotnet/tools" 
(maybe check before, which one is the right one)

and then log out and log in again.

if you get some error about some .so file missing you also need to set the DOTNET_ROOT environment variable. so also add
export DOTNET_ROOT=$(dirname $(realpath $(which dotnet)))

**Comment by sudo216** [comment]
> the tool is in your homedir in .dotnet/tools
> 
> so best is to add
> this to your ~/.bash_profile if your system is a non-sudo system.
> export PATH="$PATH:/root/.dotnet/tools"
> if you have used sudo, then it is
> export PATH="$PATH:/home/yourusername/.dotnet/tools"
> (ofc replace yourusername ;) - maybe check before, which one is the right one)
> 
> to add it to your Path and then log out and log in again.
> 
> if you get some error about some .so file missing you also need to set the DOTNET_ROOT environment variable. so also add
> export DOTNET_ROOT=$(dirname $(realpath $(which dotnet)))

i tried but dk why 
the error comes 

**coder@f110c9f609d8:~/project/dump$ pidof dotnet
7915
coder@f110c9f609d8:~/project/dump$ dotnet gcdump collect -p 7915
Writing gcdump to '/home/coder/project/dump/20210417_102226_7915.gcdump'...
        Failed to collect gcdump. Try running with '-v' for more information.
coder@f110c9f609d8:~/project/dump$ dotnet gcdump collect -v -p 7915
Writing gcdump to '/home/coder/project/dump/20210417_102239_7915.gcdump'...
  0.0s: Creating type table flushing task
  0.0s: [Error] Exception during gcdump: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (13): Permission denied /tmp/dotnet-diagnostic-7915-304489597-socket
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at Microsoft.Diagnostics.NETCore.Client.UnixDomainSocket.Connect(String path, TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/UnixDomainSocket.cs:line 57
   at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.Connect(TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs:line 138
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessage(IpcEndpoint endpoint, IpcMessage message, IpcMessage& response) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs:line 42
   at Microsoft.Diagnostics.NETCore.Client.EventPipeSession..ctor(IpcEndpoint endpoint, IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs:line 30
   at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.StartEventPipeSession(IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs:line 66
   at Microsoft.Diagnostics.Tools.GCDump.EventPipeSessionController..ctor(Int32 pid, List`1 providers, Boolean requestRundown) in /_/src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs:line 235
   at Microsoft.Diagnostics.Tools.GCDump.EventPipeDotNetHeapDumper.DumpFromEventPipe(CancellationToken ct, Int32 processID, MemoryGraph memoryGraph, TextWriter log, Int32 timeout, DotNetHeapInfo dotNetInfo) in /_/src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs:line 52
[  0.1s: Done Dumping .NET heap success=False]
        Failed to collect gcdump. Try running with '-v' for more information.
coder@f110c9f609d8:~/project/dump$ ls
coder@f110c9f609d8:~/project/dump$**

**Comment by sudo216** [comment]
i dumped but idk if i did correct or not. Although
here(https://drive.google.com/file/d/1OhgfZxCx8Q_ZkxahFtkgiMMyR9tg7YTC/view?usp=sharing)

**Comment by openbullet** [comment]
Please can anyone confirm if the memory leaks are still present in 0.1.12? I fixed the big one, so maybe now it's acceptable? Please let me know.

**Comment by ObsessedHacker** [comment]
> Please can anyone confirm if the memory leaks are still present in 0.1.12? I fixed the big one, so maybe now it's acceptable? Please let me know.

It's hard to replicate the issue since the job has to run for a long period of time, so I guess for now it's fixed?
