### ISSUE TITLE
[BUG] Port changing

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#15]
**Describe the bug**
dotnet ./OpenBullet2.dll --urls="http://*:1234" ---> it is not working, both locally and remotely
appsettings.release.json                                      ---> it works locally, but not remotely

**Comment by XazkerBoy** [comment]
Same issue, OB2 running on Debian 10 on VPS (no port forwarding needed) and the remote interface can be accessed through port 5000 (ext_ip:5000). When running in home network (OB2 on Win10 LTSC), after port forwardinc can also be accessed from outer world (router_ext_ip:5000)

**Comment by qMMMp** [comment]
> can you access remotely when port is 5000 ?

yes
