### ISSUE TITLE
[BUG] About Config Tab

### ISSUE THREAD

**Issue by ENH4R** [openbullet/OpenBullet2#151]
Tab does not close unless reloading in Configs tab.

**Comment by ENH4R** [comment]
![resim](https://user-images.githubusercontent.com/70763026/111858369-62e93280-8949-11eb-9667-63e9d5f70655.png)

**Comment by openbullet** [comment]
This is an intended behaviour

**Comment by ENH4R** [comment]
But it's not nice to have it there even though I saved :(

**Comment by openbullet** [comment]
Sorry I'm not going to change that, I save my config multiple times while I'm editing and maybe I switch to other tabs and I want to get back to the LoliCode or Stacker quickly, it's very handy to have it open at all times. It seems like your screen is really short (low height) so maybe try to zoom out so you can see the entire menu on the left?

**Comment by ENH4R** [comment]
okay thank you very mach! :)
