### ISSUE TITLE
[BUG] About Hit Database

### ISSUE THREAD

**Issue by Teals53** [openbullet/OpenBullet2#158]
when i try to purge my db my console givin dozens of error and my hit db is bugged when i switch window etc

**Comment by openbullet** [comment]
I need to see the errors, please send screenshots

**Comment by Teals53** [comment]
sure

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/111912637-9af09280-8a7b-11eb-8c7c-468c2e174ac7.png)
most erros is these ones but in depth there is some different errors too like cannot taking proxies from unknown source eth idk smthng like that let me reproduce that

**Comment by openbullet** [comment]
Are you trying to purge the hits db while jobs are running?
Which version of OB2 are you on?

**Comment by Teals53** [comment]
latest one and yes maybe

**Comment by openbullet** [comment]
@Teals53 latest one as in 0.1.8? Can you confirm it's the exact version you have?
Also please don't purge your hits db while jobs are running.

**Comment by Teals53** [comment]
yeap 0.1.8
![image](https://user-images.githubusercontent.com/13446881/111912791-4c8fc380-8a7c-11eb-80a9-2fef3879b686.png)

**Comment by Teals53** [comment]
i do that bcs i cant delete hits from only selected configs

**Comment by Teals53** [comment]
but it must be need to work when runner is running so i purge my db and if some new hits come out they can be add on db again right ?

**Comment by openbullet** [comment]
Why? You can do that.

![immagine](https://user-images.githubusercontent.com/48930622/111912874-d4b99d00-8a6b-11eb-9642-b508c70137d5.png)

Just click on the filter button and write the name of the config. Then maybe set it to show 500 elements or so, this makes deleting filtered hits much quicker.

**Comment by openbullet** [comment]
About the exception, maybe you clicked purge multiple times because you thought it wasn't working? If you have many hits it takes a long time to delete them all.

**Comment by Teals53** [comment]
hmm so actually i tried to purge then its not deleted em all then i switch windows and tried again but evertime some new hits coming out xd ? wtfrick

**Comment by Teals53** [comment]
i guess i am still not quite used to the new system

**Comment by Teals53** [comment]
also why when i select all groups in proxy options its showing smthng like that
![image](https://user-images.githubusercontent.com/13446881/111913443-2881b180-8a7f-11eb-82fa-4f15f1b87dde.png)

**Comment by openbullet** [comment]
> 
> 
> hmm so actually i tried to purge then its not deleted em all then i switch windows and tried again but evertime some new hits coming out xd ? wtfrick

It's not deleting them all because it takes time for it to delete them. New hits are coming out because your jobs are running and getting hits, you should stop them before purging the db.

**Comment by openbullet** [comment]
> 
> 
> i guess i am still not quite used to the new system

Yes, OB2 has nothing to do with OB1. Also remember this is still a beta version

**Comment by openbullet** [comment]
> 
> 
> also why when i select all groups in proxy options its showing smthng like that
> ![image](https://user-images.githubusercontent.com/13446881/111913443-2881b180-8a7f-11eb-82fa-4f15f1b87dde.png)

`-1` is the id of the group that identifies all proxies. If you see `0` it means the first group, `1` for the second group etc.
Anyways closing this as I don't understand the issue, seems like you just need to familiarize with OB2 a bit.

**Comment by Teals53** [comment]
tysm for instant help hope its gonna better

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/111913591-ead15880-8a7f-11eb-9f2c-446373bac0df.png)
i dont do anything and its happened again

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/111913642-1d7b5100-8a80-11eb-9100-afb4cebcee16.png)
its happened when runner working i didnt touched hit db now

**Comment by Teals53** [comment]
@openbullet

**Comment by Teals53** [comment]
keep giving errors when i try to start and stop runner .d

**Comment by openbullet** [comment]
Follow this issue. https://github.com/openbullet/OpenBullet2/issues/91
Also please
- Do not ping me, I get notified of every message
- This is not a chat, try to send only 1 message otherwise you spam my email

**Comment by Teals53** [comment]
okey now i learned rules sorry if i disturbed
