### ISSUE TITLE
[BUG] Wordlist

### ISSUE THREAD

**Issue by Teals53** [openbullet/OpenBullet2#160]
when i wanna close to loading wordlist its giving error
![image](https://user-images.githubusercontent.com/13446881/111914505-4d782380-8a83-11eb-9e50-3525b6c6a299.png)
if u wanna ask why u need to cancel wordlist adding procces cuz its taking too long time when i tried to load wordlist around 50mb lol there is no other way to take these from file locations ?

**Comment by openbullet** [comment]
Use this

![immagine](https://user-images.githubusercontent.com/48930622/111914948-662d0d00-8a74-11eb-8c16-8aa8cd199d73.png)

**Comment by Teals53** [comment]
for that maybe i need to move my all wordlist to ob folder right ?

**Comment by openbullet** [comment]
No, just go to OB Settings > Security and allow system-wide file access

**Comment by Teals53** [comment]
okey but that can be makeable more useful with better easy to use stuff

**Comment by openbullet** [comment]
> 
> 
> okey but that can be makeable more useful with better easy to use stuff

What do you mean?

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/111915235-38e95a80-8a86-11eb-8636-40ec61a4bc69.png)
cant i select directly direction instead of writing file location manually ?

**Comment by openbullet** [comment]
It's working here

![immagine](https://user-images.githubusercontent.com/48930622/111915917-d3db3800-8a78-11eb-89ea-ef6e63d11554.png)
