### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sarar996** [openbullet/OpenBullet2#162]
![Screenshot 2021-03-22 080432](https://user-images.githubusercontent.com/51756254/111942842-41bd4900-8ae5-11eb-9b7b-605f2e37e6f8.png)

two different problem

![Screenshot 2021-03-22 080924](https://user-images.githubusercontent.com/51756254/111943226-0d965800-8ae6-11eb-9d54-8804acab616f.png)

**Comment by openbullet** [comment]
Which version of OB2 are you using?
What were you doing when the error appeared? Give the steps to replicate.

**Comment by sarar996** [comment]
> Which version of OB2 are you using?
// I'm using 0.1.8
> What were you doing when the error appeared? Give the steps to replicate.
// when I'm running a job at 200 bot  using PROXYLESS config

**Comment by openbullet** [comment]
Please refer to this issue https://github.com/openbullet/OpenBullet2/issues/91
