### ISSUE TITLE
[BUG] cant start up openbullet 2 exe after updater

### ISSUE THREAD

**Issue by timzwaart12** [openbullet/OpenBullet2#164]
my openbullet 2 wont start up after the updater.
when i move the openbullet 2 file on cmd i see this : 
C:\Users\piet>C:\Users\piet\Desktop\OpenBullet2\OpenBullet2.exe
Error:
  An assembly specified in the application dependencies manifest (OpenBullet2.deps.json) was not found:
    package: 'System.Management', version: '4.6.0'
    path: 'runtimes/win/lib/netcoreapp2.0/System.Management.dll'

i have to delete all the files and download it again to get it working without the update

**Comment by openbullet** [comment]
https://discourse.openbullet.dev/t/updater-breaking-the-ob2-build/1322
