### ISSUE TITLE
[REQUEST] HMAC - Interpolated mode

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#167]
HMAC has only 2 modes:
1) Variable
2) Static text

I wish for a third mode:
3) Interpolated mode
(The support of <>)

**Comment by openbullet** [comment]
Use the HMAC string block.
HMAC is only for byte arrays to byte arrays

**Comment by ObsessedHacker** [comment]
> Use the HMAC string block.
> HMAC is only for byte arrays to byte arrays

Then how do I do this from OB1?
![image](https://user-images.githubusercontent.com/13978119/112174261-f26b3b80-8bfe-11eb-9e0d-f15ac2805a5d.png)

**Comment by openbullet** [comment]
If you want to do that, then yes you have to use the standard HMAC block.
You have to make a constant string block where you interpolate the string as you wish, and then pass the resulting variable as input to the HMAC block which will take the UTF-8 string and convert it to bytes, and then output another byte array. Then you have to put a bytes => base64 block if you want to have it as base64.

**Comment by openbullet** [comment]
> 
> 
> 3) Interpolated mode

I cannot add interpolated mode for a byte array, it makes no sense because it's not a string, a byte array has nothing to do with a string and hence interpolation makes no sense.
