### ISSUE TITLE
[BUG] RuriLib.Http fails to read response content in edge case

### ISSUE THREAD

**Issue by openbullet** [openbullet/OpenBullet2#170]
In the response there are no `Content-Length`, `Content-Encoding` and `Transfer-Encoding` headers (only `Content-Type`) so the response falls into this category

https://github.com/openbullet/OpenBullet2/blob/master/RuriLib.Http/HttpResponseBuilder.cs#L317

But either the method returns before being able to read everything or there is something wrong because it doesn't pick up any content but if you put fiddler in between you will actually see there is a content and it will work correctly.

Introduced in https://github.com/openbullet/OpenBullet2/pull/81 (was working before)
PM me on the forum for a URL to test this on, or send me an email.

**Comment by RydjGit** [comment]
Hey , sorry I could not PM you on the forum .
could plz send me the like to debug for no headers issue.
also custom ports should not be a problem as long as you parse the input textbox as a Uri object.

**Comment by openbullet** [comment]
@RydjGit the URL I have is private and was sent by a user who asked me to not disclose it publicly, I hope you can understand. Please send me an email at `ruri (at) openbullet [dot] dev` and I will send it to you. Thanks!

**Comment by RydjGit** [comment]
I just sent you an email.

**Comment by openbullet** [comment]
I replied. I am going to sleep now so I'll read any further discussion tomorrow, thanks for helping out I really appreciate it!
