### ISSUE TITLE
[BUG] Stoping A Job Takes So Long

### ISSUE THREAD

**Issue by usdogu** [openbullet/OpenBullet2#173]
**Describe the bug**
I am testing my config with only 40 bots but when I try to stop it, it can't stop (I am waiting nearly 15 mins). On OB1 I can stop a check in nearly 1 sec.
**To Reproduce**
1. Create a config with 2 reqs.
2. Create a job with 40 bots with this config.
3. Wait 5-10 mins and try stopping it.

**Expected behavior**
Stopping a job in only a few seconds like OB1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser brave
 - Version 89

**Comment by openbullet** [comment]
The STOP button will wait until ALL current jobs are over. If your data is stuck in a ban loop (with no or high ban loop evasion) caused for example by bad proxies or missing keys in your keychains it will give this behaviour.
Please use the ABORT button. OB1 only had abort functionality, not soft stopping. So to get the same behaviour as OB1 always use the ABORT button.
