### ISSUE TITLE
[REQUEST] Constant String in Multiline mode

### ISSUE THREAD

**Issue by nonrect** [openbullet/OpenBullet2#177]
Hey

for some times I was dealing with very long data that basically was on 1 line but very long and editing it was hard and every time to edit that part of config I had to copy it to a notepad, edit and paste it back

For “Constant String” function I saw a lot of space under “Value” section.

Is there a possibility to increase “Value” box’s height to look like a multi line textbox (but still act as a single line textbox), so that editing of a value will be easier ?

thanks

**Comment by Cyber-Criminal** [comment]
i think these must be multiline, but not like that
just copy that data to a text editor and enable 'Word wrap' and paste that line inside

**Comment by nonrect** [comment]
I did that as a work around but the app has enough space for that textbox to be multiline in which it makes it easier and quicker to access long texts

**Comment by Cyber-Criminal** [comment]
yes, that makes it quicker and easier to make configs
also in Post data and URL in REQUEST BLOCK
but this all makes it ugly when the value in too big, except if the textbox changes to singleline when user not clicked inside


break line in 'Constant String' is a problem too, \n will translated to \\n in loliscript by default

**Comment by openbullet** [comment]
I added the `MultiLine` attribute for string parameters so now you can make your own blocks (via plugins) and add this attribute to make OB2 display the string input as a text area. If you want you can suggest the built-in blocks that need this feature. I added this attribute to the built-in blocks for Constant String and Execute Js (puppeteer and selenium).
