### ISSUE TITLE
[REQUEST]RESIZE OB TO 80%  FROM 100 % SCREEN SIZE 

### ISSUE THREAD

**Issue by pasterlevis** [openbullet/OpenBullet2#18]
RESIZE OB TO 80%  FROM 100 % SCREEN SIZE  THEN ONLY ALL ARE HANDY.IF 100%  WE NEED DRAG DOWN  TO SEE LOG AND  NOT HANDY.AND IMPLEMENT SEARCH BAR ON LOG AND REMOVE THAT DRAG OPTION INSIDE LOG.

THIS 
![image](https://user-images.githubusercontent.com/66682022/110473514-a1d6e700-8104-11eb-93c6-e9220f955511.png)

**Comment by openbullet** [comment]
Search bar not needed as you can just CTRL+F in the browser.
As for the other things, no sorry, it's gonna stay as it is.
