### ISSUE TITLE
[BUG] irregular wordlist error

### ISSUE THREAD

**Issue by Teals54** [openbullet/OpenBullet2#182]
first i apologize if i did something wrong without realizing it i wana apologize

maybe this bug happening when your wordlist have some irregular characters like that
![image](https://user-images.githubusercontent.com/81489204/112733419-042b4680-8f51-11eb-986c-f19731e87535.png)

the error is that with ban loop (also huge cpu usage)
![image](https://user-images.githubusercontent.com/81489204/112733422-0a212780-8f51-11eb-8629-cbd2c00a5a97.png)

**Comment by Teals54** [comment]
im sorry again i only opened this acc to say that i can understand if there is no luck to go back tysm for your hardwork ruri

**Comment by openbullet** [comment]
Don't try to get around a ban. You literally posted credentials in cleartext. I am not going to help you.
