### ISSUE TITLE
A Block That Collects Them All.

### ISSUE THREAD

**Issue by KokainUHD** [openbullet/OpenBullet2#183]
Hello, there may be a need for a block next to it showing how many strokes you throw, a sample picture
[picture](https://prnt.sc/10xkbh7)
and if something like this comes, we don't need more than one blog

**it would be perfect.**

**Sorry about the bad English.**

**Comment by openbullet** [comment]
I honestly don't understand anything... can you use more pictures?

**Comment by openbullet** [comment]
Replied on the forum. I cannot add a block to get the current hit count, you have to use global variables, for example by adding this at the end of the config
```csharp
lock (globals)
{
  try
  {
     // This will increase globals.Hits by 1 if it exists
     globals.Hits++;
  }
  catch
  {
     // This will create globals.Hits if it doesn't exist yet
     globals.Hits = 1;
  }
}

// You can for exampel print the value to see it
LOG globals.Hits
```
