### ISSUE TITLE
[REQUEST] Improve DB hits

### ISSUE THREAD

**Issue by Aeternus185** [openbullet/OpenBullet2#184]
It would be very useful to be able to filter the hits as it was done in OB1 to see only HITS, CUSTOM, NONE, etc. and also to be able to eliminate only one of these.
It would also be useful to be able to export the hits to a txt.

**Comment by openbullet** [comment]
You can use filters (click on the filter button in the table header).
This discussion will continue here https://github.com/openbullet/OpenBullet2/issues/26
