### ISSUE TITLE
[REQUEST] Limit OB2 CPU/RAM Usage

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#195]
If it is possible, add ability to limit OB2 ram/cpu usage
it's cool to limit OB2 RAM/CPU usage to 90%, but limiting it to specified ?MB/GB of RAM and ? Cores of CPU is good too

i use OB most of times on VPS and i connect using RDP, but can't connect anymore when CPU or RAM is on 100%

**Comment by Cyber-Criminal** [comment]
also it's great if we could limit each job

**Comment by openbullet** [comment]
It's not possible for me to limit the CPU/RAM usage from the application itself, you have to use an external tool (e.g. on Linux https://linuxhint.com/limit_cpu_usage_process_linux/). So the same applies to jobs.
