### ISSUE TITLE
[REQUEST] Multiple name/variable for same "Slice" in same "Wordlist Type"

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#198]
PLEASE Add ability to set multiple name/variable for same Slice of a Wordlist Type
Something like :

`[WORDLIST TYPE]`
`Name=Credentials`
`Regex=^.*:.*$`
`Verify=True`
`Separator=:`
`Slices0="USERNAME,PASSWORD"`
`Slices1=EMAIL,PASSWORD`

**Comment by Cyber-Criminal** [comment]
After this ability, users can run any config that made in custom environments without editing all variables in the config

**Comment by openbullet** [comment]
No sorry

**Comment by Cyber-Criminal** [comment]
@openbullet why?

**Comment by openbullet** [comment]
> 
> 
> @openbullet why?

Because what you suggested makes absolutely no sense.

**Comment by Cyber-Criminal** [comment]
> > @openbullet why?
> 
> Because what you suggested makes absolutely no sense.

why not? Many users in OB1 and also OB2 changes `Environment.ini`, USERNAME to USER and PASSWORD to PASS to make it short
when we try to use their config, we should change their config
it takes no time for OB to slice them, so it's just a feature, and makes no problem

**Comment by Cyber-Criminal** [comment]
> > > @openbullet why?
> > 
> > 
> > Because what you suggested makes absolutely no sense.
> 
> why not? Many users in OB1 and also OB2 changes `Environment.ini`, USERNAME to USER and PASSWORD to PASS to make it short
> when we try to use their config, we should change their config
> it takes no time for OB to slice them, so it's just a feature, and makes no problem

@openbullet 
this problem wastes a lot of time, add this feature please
