### ISSUE TITLE
[REQUEST] ignore Response Source / Limit Response Source at specified Bytes

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#199]
Many times, we don't need Resp. Source in our configs
is it possible to not download Response Source (not only hiding source from logs)

i think this ability was there in BB or an old V. of OB1

also it's needed on some targets
https://github.com/openbullet/openbullet/issues/491

and also it's good if we could limit getting Resp. source to specified Bytes

**Comment by openbullet** [comment]
https://github.com/openbullet/OpenBullet2/issues/52

**Comment by Cyber-Criminal** [comment]
@openbullet 
this issue is not duplicate of that
i mean not downloading the source, not only hiding it from debugger log
if i wanted to only hide debugger thing, i could use `data.Logger.Enabled`

But you said why we don't use HEAD method instead, when we don't need the SOURCE
1. Because a HEAD request does not accept post data.
2. HEAD may not be allowed [405]
3. Using HEAD instead of GET makes our requests detectable..

**Comment by openbullet** [comment]
Okay fine I'll add it
