### ISSUE TITLE
[BUG] Cant logout as admin

### ISSUE THREAD

**Issue by Matsverheyen** [openbullet/OpenBullet2#2]
When clicking logout when autheticated as admin, it doesnt log out.

Log in as admin
goto home tab
click logout

I expected the admin to logout

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Versie 88.0.4324.190 (Officiële build) (64-bits)

**Comment by openbullet** [comment]
You have to enable "require administrator login" in OB Settings > Security in order to be able to log out.
