### ISSUE TITLE
[BUG] a little problem in Jobs tab

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#200]
![image](https://user-images.githubusercontent.com/41063376/113403842-86d25c80-93bc-11eb-8448-50222308b9af.png)

sometimes i click on a Job and it does not redirect. only i should exactly click on the text to redirect
please fix it, when i click even on empty part or a little under text, it should redirect

**Comment by Cyber-Criminal** [comment]
and also SORRY FOR MY BAD ENGLISH ☹️

**Comment by Cyber-Criminal** [comment]
@openbullet 

![image](https://user-images.githubusercontent.com/41063376/113460501-40b5e100-942e-11eb-89ce-94d29e8bd77c.png)
will you change Log's background color from deep black to color of other boxes?
that pure black kills my eyes when i scroll, because my Monitor have VA panel
it's anonying on non IPS/TN panels

i know it can be done by themes .css
but i just asked if you like to change it for everyone

**Comment by openbullet** [comment]
https://github.com/openbullet/OpenBullet2/commit/790ed56441f8905c17cad14562dd01b9f7a41db3
