### ISSUE TITLE
[BUG] Only get Errors with different Configs

### ISSUE THREAD

**Issue by Susilein69** [openbullet/OpenBullet2#201]
Hello, i cant scan with OB2, i only get Errors see Screenshot.
Its Version 0.1.10, i also try older Version but is the same.

Thanks for Help

![screenshot](https://user-images.githubusercontent.com/81819646/113436747-9023ef00-93e5-11eb-9336-56fc9c5f8451.jpg)

**Comment by openbullet** [comment]
Let's continue here https://github.com/openbullet/OpenBullet2/issues/91
