### ISSUE TITLE
[REQUEST] add empty variable option to parse

### ISSUE THREAD

**Issue by shkarpro** [openbullet/OpenBullet2#203]
add the option to create the variable empty while using parse block 
or any other blocks that can be put into IF statement 
because if they dont get created the config will give out errors

**Comment by openbullet** [comment]
This is not possible because everything gets translated to C# in the end, and in C# if you declare a variable inside an if statement it only lives in the scope of the statement and not outside.
So you have to DECLARE the variable OUTSIDE of the statement and then ASSIGN its value INSIDE.
