### ISSUE TITLE
Proxylist not updating info

### ISSUE THREAD

**Issue by FilterUnfiltered** [openbullet/OpenBullet2#205]
I am having an issue where the proxies list doesn't update the working/not working status of proxies after a proxy check. That is, when the proxy check even finishes since right now it always gets stuck on like 97%. I am completely new to all this but I can guess that the getting stuck part isn't intended.

**Comment by Robaxman** [comment]
yes a bug

**Comment by openbullet** [comment]
To update the page just press F5, as the browser caches it to load it faster and by using F5 you reload the page.
Please open a separate issue for the jobs getting stuck when they're almost completed as this happens with every job (so it's an issue of the parallelizer) and not of the proxy check job specifically. Thanks.
