### ISSUE TITLE
[REQUEST] suggestions about Stacker UI

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#210]
![image](https://user-images.githubusercontent.com/41063376/113722815-04bc9d80-9706-11eb-94ad-f6f37480514b.png)

i many times delete block instead of disabling it!
also sometimes i forget to save config! because save button in not in a good place
so i suggest you to change oi-x to oi-minus
and add another button to save config beside of other buttons (icon = oi-check)

![image](https://user-images.githubusercontent.com/41063376/113724900-1010c880-9708-11eb-8e41-72d3ff0e3dda.png)

this one is more like OB1 [oi-ban changed to oi-x] :
![image](https://user-images.githubusercontent.com/41063376/113725383-80b7e500-9708-11eb-9006-959d848c9771.png)

**Comment by openbullet** [comment]
You can do CTRL+S to save, it's very quick and you don't need to click anything. Also I don't really like your change, across the entire program the X symbol means remove.

**Comment by Cyber-Criminal** [comment]
Ahhh, Add that Save button PLEASE :(
@openbullet
