### ISSUE TITLE
[REQUEST] Discord Webhook

### ISSUE THREAD

**Issue by CodingBeaner** [openbullet/OpenBullet2#214]
If possible allow us to use our own format for the message for discord webhook such as put it in message embed because it would make it look better rather than have a bunch of spam text stuck together

**Comment by openbullet** [comment]
You mean as hit output or in the actions of the job monitor? Or both?

**Comment by crazygamer96** [comment]
I want to be able to have the hit output to send to the webhook as a embed like have one of the parse captures as the title or something like that 
![image](https://user-images.githubusercontent.com/33612551/116647398-4b7d6c00-a92f-11eb-8860-c51bf185c5d2.png) like this

**Comment by tcortega** [comment]
@openbullet pretty sure the less annoying and easiest solution for this is creating an util block for webhooks.

**Comment by openbullet** [comment]
> 
> 
> I want to be able to have the hit output to send to the webhook as a embed like have one of the parse captures as the title or something like that

You could use a simple Http Request block inside your configs and send a request with the correct json content for embeds to get around this limit of OB2. I will consider adding this in the future but it's low priority.

**Comment by crazygamer96** [comment]
Whenever I try to send a POST request through OB to the webhook with the content it always responds with {"message": "400: Bad Request", "code": 0} but when i put the same stuff in https://reqbin.com/ it works not sure why

**Comment by openbullet** [comment]
@crazygamer96 did you use `application/json` as Content-Type instead of the default one? Could you maybe show an example of LoliCode so we can replicate the issue?

**Comment by crazygamer96** [comment]
Yes I did use application/json. 
`BLOCK:HttpRequest
  url = "https://discord.com/api/webhooks/[webhook]"
  method = POST
  customHeaders = {}
  TYPE:STANDARD
  "{\"content\":null,\"embeds\":[{\"title\":\"<ItemName>\",\"color\":65290,\"fields\":[{\"name\":\"name\",\"value\":\"3303\\n3305\\n3304\"}],\"author\":{\"name\":\"name\"},\"image\":{\"url\":\"https://www.denofgeek.com/wp-content/uploads/2019/11/star-wars-the-mandalorian-baby-yoda.png?resize=768%2C432?size=pdhi\"}}]}"
  "application/json"
ENDBLOCK
`

**Comment by openbullet** [comment]
> 
> 
> Yes I did use application/json.
> 
> ```
> BLOCK:HttpRequest
>   url = "https://discord.com/api/webhooks/[webhook]"
>   method = POST
>   customHeaders = {}
>   TYPE:STANDARD
>   "{\"content\":null,\"embeds\":[{\"title\":\"<ItemName>\",\"color\":65290,\"fields\":[{\"name\":\"name\",\"value\":\"3303\\n3305\\n3304\"}],\"author\":{\"name\":\"name\"},\"image\":{\"url\":\"https://www.denofgeek.com/wp-content/uploads/2019/11/star-wars-the-mandalorian-baby-yoda.png?resize=768%2C432?size=pdhi\"}}]}"
>   "application/json"
> ENDBLOCK
> ```

Keep the User-Agent header because usually sites require you to send it, and also you want to use the `</>` (interpolated) mode instead of constant mode, so basically put a `$` at the start of your content string like `$"{\"content...`

**Comment by crazygamer96** [comment]
I've tried that already even when I do it on reqbin without any headers it still works

**Comment by crazygamer96** [comment]
Ok well I figured out why sending the request for the webhook doesn't work and its because whenever you turn on the interpolated string option it doesn't work for some reason and it only works when you have  the fixed input option

**Comment by Br4uNTr** [comment]
Meanwhile you can use this plugin as workaround, until Ruri made a proper solution
https://discourse.openbullet.dev/t/discord-plugin/2740

**Comment by Br4uNTr** [comment]
> I've tried that already even when I do it on reqbin without any headers it still works

Meanwhile you can use this plugin as workaround, until Ruri made a proper solution
https://discourse.openbullet.dev/t/discord-plugin/2740
