### ISSUE TITLE
[BUG] Puppeteer Submit not working

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#215]
![image](https://user-images.githubusercontent.com/41063376/114268351-e1e7fd00-9a15-11eb-9c2c-612a12a18af8.png)

**Comment by openbullet** [comment]
Submit only works on `form` elements. If you want to target a button, use the Click block instead.

**Comment by Cyber-Criminal** [comment]
> Submit only works on `form` elements. If you want to target a button, use the Click block instead.

Can i use click in Headless mode?

**Comment by openbullet** [comment]
@Cyber-Criminal No clue, try xD
