### ISSUE TITLE
[BUG] Websocket wrong http proxy crash bug

### ISSUE THREAD

**Issue by MaviReiz** [openbullet/OpenBullet2#216]
Websocket blocks giving crash with wrong http proxies not working like normal http requests

![image](https://user-images.githubusercontent.com/44947741/114271138-9551f100-9a18-11eb-9269-9cb489dfd040.png)

**Comment by openbullet** [comment]
Fixed in https://github.com/openbullet/OpenBullet2/commit/0260dcb175a5718e1cfdc0b9e9f6a6c92e0b4245
