### ISSUE TITLE
[BUG] ERROR ON TLS 1.3

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#219]
![image](https://user-images.githubusercontent.com/41063376/114320032-4d6ebf00-9b29-11eb-83ac-012886cc93df.png)

![image](https://user-images.githubusercontent.com/41063376/114319996-17c9d600-9b29-11eb-8ea2-b21c43753b86.png)

THERE IS NO PROBLEM WHEN USING 1.2 ON THE SAME URL
TARGET SUPPORTS TLS 1.2 and TLS 1.3, NP

**Comment by openbullet** [comment]
Which operating system are you using? Did you try the "system default" option?

**Comment by Cyber-Criminal** [comment]
> Which operating system are you using? Did you try the "system default" option?

There is no problem with 'System Default'
i just tried TLS 1.3 and got the ERROR, and i reported here

also i can't use 'HTTP 2.0' but you said it's not supported yet, is TLS 1.3 not supported yet too?

**Comment by Cyber-Criminal** [comment]
also after trying TLS 1.3 :
![image](https://user-images.githubusercontent.com/41063376/114320176-f9180f00-9b29-11eb-9a88-d43ca99341c9.png)

**Comment by openbullet** [comment]
System Default is actually TLS 1.3
Windows has problems with the TLS 1.3 option, it's meant for mac/linux. Please use the System Default option on windows.

**Comment by Cyber-Criminal** [comment]
it's weird
will fixed in future or no?
