### ISSUE TITLE
[BUG] ProxyChecker Infinity loading

### ISSUE THREAD

**Issue by UnknowUsername** [openbullet/OpenBullet2#22]
https://i.imgur.com/nLPC5e5.gif
loading every time at 100% and no checked proxies in proxy list
Solved after changing settings and starting again JOB task
Then my proxies list updated

**Comment by openbullet** [comment]
Hey, please test again in update 0.1.7 and see if it's solved

**Comment by openbullet** [comment]
Closing since the issue creator is not replying
