### ISSUE TITLE
[REQUEST] Add list of Variables in 'KEY CHECK' BLOCK

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#221]
![image](https://user-images.githubusercontent.com/41063376/114321252-156a7a80-9b2f-11eb-902c-6391e4a1df14.png)
Add something like this to OB2

**Comment by Cyber-Criminal** [comment]
@openbullet 
914f62796e403a053f74caea9ac5cc39c6cbf908
c5c8c2752364ce0651dcd8490e2176c7f8c1dc2d
![image](https://user-images.githubusercontent.com/41063376/125524333-57a55429-a9b9-4453-85a7-5eb8b45a1416.png)
After adding STRING / Bool / Dictionary
input is 'data.SOURCE' by default, and after click on it, can't see list of all suggestions
i think it's better to remove this default value, because suggestions is there and can pick any easily

also better to remove `input.DATA`, `data.STATUS` and `data.RAWSOURCE` from suggestions to make it more clean

**Comment by openbullet** [comment]
The fact is that the suggestions are shown in every variable field of every block, not just the keycheck block. So that's why I put all the values, also to let users know that they exist. I also don't like the suggestion of removing data.SOURCE as default, since it's what is used in 99% of cases.

**Comment by Cyber-Criminal** [comment]
@openbullet 
Good!, so add `data.Line.Data` to suggestions too, it's useful, i use it in +30% of my configs

**Comment by openbullet** [comment]
Alright I will add it
