### ISSUE TITLE
[BUG] OpenBullet2.exe/Updater.exe does not find dotnet.exe from current path

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#222]
When dotnet.exe is there, in the ROOT of OB2 Folder, OpenBullet2.exe and ALSO Updater.exe can't detect is and it's just looking for dotnet.exe in the global %PATH% and not in it's folder

**Comment by openbullet** [comment]
If you want to have the framework in the same place as OB2, then compile OB2 yourself using the self-contained option. I don't have any control on the thing you said.
