### ISSUE TITLE
[BUG] Can't access a link until i uncheck read response content

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#225]
**Describe the bug**
the request timeout when i am trying to access main page of Mega nz https://mega.nz/
when i disable read response content, it works, it shows the response headers along with response cookies

one more thing: the bot display the sent headers + extra cookie (i am not sending any custom cookies)
<img width="917" alt="Screen Shot 2021-04-13 at 6 09 18 PM" src="https://user-images.githubusercontent.com/80313339/114600277-aeaaa580-9c83-11eb-82f0-4912a55c9855.png">

**Comment by openbullet** [comment]
@RydjGit sorry to ping you. If you have some time could you help me on this please? I'm struggling to find the cause of the issue...

**Comment by RydjGit** [comment]
Hey , 
Let me take a look and I will report back to you.
