### ISSUE TITLE
[REQUEST] Keycheck

### ISSUE THREAD

**Issue by crazygamer96** [openbullet/OpenBullet2#226]
Add an option to only send Parse Captures above the check if the keycheck=success 
![image](https://user-images.githubusercontent.com/33612551/114705491-a6cb1f80-9cdc-11eb-845a-c32788e900fe.png)
I have that repeating about 250+ times yes its dumb but it was the only way I could find that it would work anyways if possible add like a check mark or something to only send parse capture chain above it if that keycheck=success

**Comment by openbullet** [comment]
I'm not sure I follow... can you please provide an example of what is happening and what you want to happen? Maybe with some LoliCode as well?

**Comment by crazygamer96** [comment]
so I have 
![image](https://user-images.githubusercontent.com/33612551/114707368-fdd1f400-9cde-11eb-87d6-a92d1e305094.png)
so that when one keycheck is failed or success it doesn't instantly end I want it to only send the captures above that keycheck until it reaches the next different block if the keycheck succeeds if that makes sense. Basically I have like 250+ configs in one so that I don't have to run 250+ jobs at once 
![chrome_mPyl1sbyb3](https://user-images.githubusercontent.com/33612551/114708298-04ad3680-9ce0-11eb-96f3-0f055c02de82.png)

**Comment by openbullet** [comment]
There's no need for a new checkbox in the keycheck block, you can already do this with some LoliCode.
```
// Here is your keycheck
IF STRINGKEY @data.STATUS EqualTo "SUCCESS"
JUMP #REQUEST2
END

// Here are the parse blocks you want to skip if success

#REQUEST2
// Here is your second request
```
Replicate this for every request and you're done.

**Comment by crazygamer96** [comment]
I don't want to skip any if success. If the keycheck=fail I want it to basically delete the captures that were above it so it doesn't send them in the discord webhook also if any keycheck gets marked as success in the config send all the success keycheck captures. also if the last keycheck gets marked as fail it doesn't mark the whole thing as failed .

**Comment by openbullet** [comment]
```
IF STRINGKEY @data.STATUS EqualTo "FAIL"
// Put some lines like the one below to remove captures, where MYCAPTURE is the name of your capture
data.MarkedForCapture.Remove(nameof(MYCAPTURE));
END
```

**Comment by crazygamer96** [comment]
![image](https://user-images.githubusercontent.com/33612551/114723887-e0f1ec80-9cef-11eb-97b4-480f45f8f14a.png)

**Comment by openbullet** [comment]
You have to put it after the ENDBLOCK of the keycheck, on a new line, not inside the block

**Comment by crazygamer96** [comment]
ok now how do I make it not FAIL the whole thing if the last keycheck gets marked as fail so if only 1 so even if 1 keycheck gets marked as success it will be marked as success in general

**Comment by openbullet** [comment]
```csharp
// At the start of the config
bool anySuccess = false;

// After every keycheck
IF STRINGKEY @data.STATUS EqualTo "SUCCESS"
anySuccess = true;
END

// At the end of the config
IF BOOLKEY @anySuccess Is True
data.STATUS = "SUCCESS";
END
```

**Comment by crazygamer96** [comment]
> ```cs
> // At the start of the config
> bool anySuccess = false;
> 
> // After every keycheck
> IF STRINGKEY @data.STATUS EqualTo "SUCCESS"
> anySuccess = true;
> END
> 
> // At the end of the config
> IF BOOLKEY @anySuccess Is True
> data.STATUS = "SUCCESS";
> END
> ```

K sorry for bringing this back but I guess because the END thing is there is cancels out all the other captures after 
![chrome_ae0JmoIxnv](https://user-images.githubusercontent.com/33612551/114797925-14ad3080-9d49-11eb-8a34-900cb553abf6.png)

**Comment by openbullet** [comment]
`END` is just like `ENDIF` in OB1. It's just to close the previous IF statement.
Also, just put all the lines inside a single IF like this
```csharp
IF ...
data.MarkedFor...
data.MarkedFor...
END
```
there's no need to have 1 IF for each one. Anyways I cannot help further without having a sample config, so maybe put together a sample config with test blocks for me so I can see exactly what you're doing wrong.
