### ISSUE TITLE
[REQUEST] Add Recaptcha v2 Entreprise in solve captcha solutions

### ISSUE THREAD

**Issue by JeanMenage** [openbullet/OpenBullet2#228]
**Is your feature request related to a problem? Please describe.**
Yes, some captcha solving services have an option for solving recaptcha v2 entreprise, unfortunetly that's not available on openbullet 2.

**Describe the solution you'd like**
Like a checkbox on recaptcha v2 block to specify that it's recaptcha v2 entreprise.

**Describe alternatives you've considered**
Don't know honestly.

**Additional context**
My english is really bad, i hope you understood what i've been trying to explain tho. Thanks for all you did with openbullet 1 & 2.

**Comment by mastercho** [comment]
OB2 uses library for it you must open issue in library github https://github.com/openbullet/CaptchaSharp

**Comment by openbullet** [comment]
I'll close this since the other one is open on the CaptchaSharp repo
