### ISSUE TITLE
[REQUEST] buttons as inputbox

### ISSUE THREAD

**Issue by sweder725** [openbullet/OpenBullet2#229]
I'm a lazy user, I don't want to write so many times a day in the inputbox and I would like to automate it with a simple button that can be set from the configuration settings.

I have prepared an image that explains my request
![2021-04-17_013444](https://user-images.githubusercontent.com/82685387/115095232-cfdbf200-9f20-11eb-9cb8-25c4519612c4.png)

I thank you if you will consider my request, have a nice day.

**Comment by Cyogenus** [comment]
Yes this would be nice 👍 I recommend up to 3 or 4 buttons. ;) This should be easy for Rurri I'm sure when he's done with his new project he will add it unless he starts another huge project.

**Comment by openbullet** [comment]
This will be reworked in the new client
