### ISSUE TITLE
[REQUEST]AES Encrypt should not only accept Plain Text

### ISSUE THREAD

**Issue by meinname** [openbullet/OpenBullet2#233]
but also for example HEX
example with this script for a common task
See the included comment...

```
BLOCK:Script
INTERPRETER:NodeJS
INPUT 
BEGIN SCRIPT
var password = "123456";
var crypto = require('crypto');
var md5pass = crypto.createHash('md5').update(password).digest("hex");
var sha256v1 = crypto.createHash('sha256').update(md5pass).digest("hex");
var key = new Buffer(sha256v1, 'hex')
var src = new Buffer(md5pass, 'hex')
cipher = crypto.createCipheriv("aes-256-ecb", key, '')
cipher.setAutoPadding(false)
result = cipher.update(src).toString('hex');
result += cipher.final().toString('hex');
END SCRIPT
OUTPUT String @result
OUTPUT String @sha256v1
ENDBLOCK

//result: e10adc3949ba59abbe56e057f20f883e should be same with that one (key taken from sha2556v1) - but it is not. Problem is likely that the plainText is Text and not accepting input as Hex

BLOCK:HashString
  input = "123456"
  => VAR @hashStringOutput
ENDBLOCK

BLOCK:AESEncrypt
  plainText = @hashStringOutput
  key = zfSgB+KwKgxJ/Jt8z7uKEMZE9jXhdl3PKnq3lN3H7aw=
  mode = ECB
  => VAR @aESEncryptOutput
ENDBLOCK
```

**Comment by qMMMp** [comment]
to make the code less messy and more readable, i did change all the hex values to base64. Because i want to focus here on making the input be not just string.
this code can enable the input to be byte[]

the example is for AES ecb pkcs7

`        public static void Main()
        {
            byte[] password = Convert.FromBase64String("4QrcOUm6Wau+VuBX8g+IPg==");
            byte[] key = Convert.FromBase64String("zfSgB+KwKgxJ/Jt8z7uKEMZE9jXhdl3PKnq3lN3H7aw=");
            byte[] iv = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

            byte[] encrypted = Encrypt(password, key, iv);

            Console.WriteLine(Convert.ToBase64String(encrypted));

        }

        public static byte[] Encrypt(byte[] input, byte[] key, byte[] iv)
        {
            var aesAlg = new AesManaged
            {
                KeySize = 128,
                Key = key,
                IV = iv,
                BlockSize = 128,
                Mode = CipherMode.ECB,
                Padding = PaddingMode.PKCS7
            };

            ICryptoTransform encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);
            return encryptor.TransformFinalBlock(input, 0, input.Length);
        }`

i hope this can help
regards

ps for mein, in the node code, you change the cipher update and final to hex then you concat the two hex results
i guess you should concat the buffers from update and final, then get the hex value

**Comment by openbullet** [comment]
Tested and working with this code
```
BLOCK:Script
INTERPRETER:NodeJS
INPUT 
BEGIN SCRIPT
var password = "123456";
var crypto = require('crypto');
var md5pass = crypto.createHash('md5').update(password).digest("hex");
var sha256v1 = crypto.createHash('sha256').update(md5pass).digest("hex");
var key = new Buffer(sha256v1, 'hex')
var src = new Buffer(md5pass, 'hex')
cipher = crypto.createCipheriv("aes-256-ecb", key, '')
cipher.setAutoPadding(false)
result = cipher.update(src).toString('hex');
result += cipher.final().toString('hex');
END SCRIPT
OUTPUT String @result
OUTPUT String @sha256v1
OUTPUT String @md5pass
ENDBLOCK

BLOCK:ConstantString
  value = "123456"
  => VAR @constantString
ENDBLOCK

BLOCK:Hash
LABEL:MD5 to create plaintext
  input = @constantString
  => VAR @plaintext
ENDBLOCK

BLOCK:ByteArrayToHexString
  bytes = @plaintext
  => VAR @plaintext_hex
ENDBLOCK

BLOCK:Hash
LABEL:SHA256 to create key
  input = @plaintext_hex
  hashFunction = SHA256
  => VAR @key
ENDBLOCK

BLOCK:AESEncrypt
  plainText = @plaintext
  key = @key
  mode = ECB
  => VAR @aESEncryptOutput
ENDBLOCK
```
