### ISSUE TITLE
[BUG] Funcaptcha solving using 2Captcha

### ISSUE THREAD

**Issue by Cat5432** [openbullet/OpenBullet2#241]
**2Captcha Funcaptcha badly integrated**
Whenever i try to solve funcaptcha using twocaptcha and openbullet am getting error of 
[Executing block Solve Fun Captcha] TaskCreationException: ERROR_PAGEURL

**To Reproduce**
1. Go to 'stacker'
2. Get make funcaptcha function
3. Make sure u using twocaptcha

**Screenshots**
![image](https://user-images.githubusercontent.com/79338084/116007541-8706f600-a610-11eb-8966-a1961e0e4bcc.png)

![image](https://user-images.githubusercontent.com/79338084/116007354-b6693300-a60f-11eb-8443-56d9748dade1.png)

**Comment by openbullet** [comment]
Are you sure you're writing
```
https://urlwithcaptcha.com/
```
and not
```
https:/urlwithcaptcha.com/
```
?

**Comment by Cat5432** [comment]
Am not

**Comment by Cat5432** [comment]
I removed / accidentaly when making this bug report, it has nothin to do with it, it happens on new ob and also on old one

**Comment by openbullet** [comment]
> 
> 
> Am not

I don't understand this reply, you sent a screenshot with a malformed URL which is missing a `/` character. Can you add it and try again?

**Comment by Cat5432** [comment]
> > Am not
> 
> I don't understand this reply, you sent a screenshot with a malformed URL which is missing a `/` character. Can you add it and try again?

i fixed the screen, as i said it has nothin to do with it, it happens on old ob and also on this one, idk what can be the issue of this

**Comment by Cat5432** [comment]
Its weird, when i try using their api in py or smthing with site where am trying to solve it it works, but tru ob it doesnt, anyway i tried another domain in ob and it worked so idk what can be the issue of this

**Comment by openbullet** [comment]
If the issue is only present on a specific site then there is no way I can debug this without having the site, maybe consider sending me an email.

**Comment by Cat5432** [comment]
sure, goin to do that

**Comment by Cat5432** [comment]
Email sent, thanks !

**Comment by openbullet** [comment]
If you remove the `www` and make it `https://sitewithcaptcha.com` it works in our tests. I don't know what the issue may be, but it's coming from 2captcha so this is not an OB2 related issue. OB2 is just sending exactly what you put, and 2captcha is saying it's invalid.
