### ISSUE TITLE
[BUG] File Write error in macOS

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#242]
**To Reproduce**
Steps to reproduce error1:
```
BLOCK:FileWrite
  path = "UserData/filename.txt"
  content = $"xxxxxxxxxx"
ENDBLOCK
```
2. throw error

to fix the error1, i had to put the full path, but still ...

Steps to reproduce error2:
1.
``` 
BLOCK:FileWrite
  path = "/Users/<user>/Downloads/OpenBullet2/UserData/filename.txt
  content = $"xxxxxxxxxx"
ENDBLOCK
```
2. it works for the first time, but ob2 stop responding without throwing any error

**Comment by meinname** [comment]
Can confirm both

**Comment by openbullet** [comment]
Please check and make sure this is fixed, I tested it a bit but I didn't try all possible things.
