### ISSUE TITLE
OB2 doesen't open

### ISSUE THREAD

**Issue by Superbulzo** [openbullet/OpenBullet2#243]
OB2 is opening and in a millisecond closing

Literally open OB

Maybe requirements?

**Desktop (please complete the following information):**
 - OS: Win
 - Browser chrome
 - Version bro tf i know

**Comment by openbullet** [comment]
Instead of double clicking on the executable, right click on some empty space of the folder explorer while holding Shift and click on "Open PowerShell window here". Then type `dotnet ./OpenBullet2.dll` and press enter, please paste the output error here so I can help further.

**Comment by rayanbdn** [comment]
Hi, This Is the error message It display: dotnet: The term "dotnet" is not recognized as the name of a cmdlet, function, script file, or program
executable. Check the spelling of the name, or if a path exists, verify that the path is correct
and try again.
To Line:1 character : 1
+ dotnet ./OpenBullet2.dll
+ ~~~~~~
     + CategoryInfo: ObjectNotFound: (dotnet:String)[], CommandNotFoundException
     + FullyQualifiedErrorId: CommandNotFoundException

**Comment by openbullet** [comment]
This means you didn't install `dotnet`. Please follow the installation guide, you need to install .NET 6 (install the SDK if unsure) in order to run OB2.
