### ISSUE TITLE
[BUG] `Use Custom Cipher Suites` not works

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#245]
![image](https://user-images.githubusercontent.com/41063376/116384837-78495a80-a82d-11eb-81d0-26eae724158d.png)

it makes no changes in LoliScript
after i change 'Custom Cipher Suites', and i disable `Use Custom Cipher Suites`, it will still use Custom Cipher Suites

**Comment by openbullet** [comment]
This is intended, the LoliCode is just there to keep track of the values you change with respect to the defaults of the block, so if you change something in the Custom Cipher Suites box, it's going to write it so you don't lose your changes. But if you unticked the box, it's not going to use them when executing the block, don't worry.

**Comment by Cyber-Criminal** [comment]
@openbullet
try this :

`BLOCK:HttpRequest`
`  url = "https://example.com"`
`  securityProtocol = TLS12`
`  customCipherSuites = ["TLS_RSA_WITH_AES_256_CBC_SHA256", "TLS_RSA_WITH_AES_128_CBC_SHA256", "TLS_RSA_WITH_AES_256_CBC_SHA", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_3DES_EDE_CBC_SHA", "TLS_RSA_WITH_RC4_128_SHA", "TLS_RSA_WITH_RC4_128_MD5", "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"]`
`  TYPE:STANDARD`
`  $""`
`  "application/x-www-form-urlencoded"`
`ENDBLOCK`

![image](https://user-images.githubusercontent.com/41063376/116543764-879ad780-a903-11eb-8500-2d60cb23b477.png)

OR this one :

`BLOCK:HttpRequest`
`  url = "https://example.com"`
`  securityProtocol = TLS12`
`  customCipherSuites = [""]`
`  TYPE:STANDARD`
`  $""`
`  "application/x-www-form-urlencoded"`
`ENDBLOCK`

![image](https://user-images.githubusercontent.com/41063376/116543609-4e626780-a903-11eb-896d-b69ec18864e6.png)

**Comment by openbullet** [comment]
It literally tells you the issue, if you're not sending cipher suites how is it supposed to negotiate TLS? And `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` is not supported. I am just implementing the official .NET implementation for this, without changing anything, so this is not an issue with OB2.

**Comment by Cyber-Criminal** [comment]
i just added a custom cipher list, and OB2 said that `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` is not supported, and then, i removed them all, then i got another error, while `Use Custom Cipher Suites` was disabled!
and then i had to add new request block and copy ciphers to the old requests to pass this problem

**Comment by Cyber-Criminal** [comment]
so there is a bug here, but
> after i change 'Custom Cipher Suites', and i disable `Use Custom Cipher Suites`, it will still use Custom Cipher Suites
was wrong

and the problem is that when 'Custom Cipher Suites' is disabled, why OB2 checks if cipher list is empty or ciphers not supported or anything else

**Comment by openbullet** [comment]
> 
> 
> so there is a bug here, but
> 
> > after i change 'Custom Cipher Suites', and i disable `Use Custom Cipher Suites`, it will still use Custom Cipher Suites
> 
> was wrong
> 
> and the problem is that when 'Custom Cipher Suites' is disabled, why OB2 checks if cipher list is empty or ciphers not supported or anything else

This is a very minor issue, why can't you just clear the box if you decide you do not want to use custom cipher suites anymore? It's not game breaking in any way
