### ISSUE TITLE
[BUG] Can't open the job with so many hits

### ISSUE THREAD

**Issue by ZEUS-src** [openbullet/OpenBullet2#247]
**Describe the bug**
When the job has so many hits I can't open it, it lags the browser, so it forces me to restarts OB

**Comment by rockyd3vil** [comment]
https://www.upload.ee/files/13597655/hits.mp4.html

https://user-images.githubusercontent.com/75754463/139625118-5afaba93-11b4-4d25-9445-df0fab75c811.mp4

fix this also.

http can't access for clipboard so why don't you change the format for manual copy..
