### ISSUE TITLE
[BUG]File Write Bytes block no longer works in V0.1.13

### ISSUE THREAD

**Issue by HypeMaxers** [openbullet/OpenBullet2#253]
**Describe the bug**
The config fails on the "File Write Bytes" block.
Tested it in 0.1.12 and it works there.

**To Reproduce**
Can't really tell if the issue is on my end or not but here is the error message.

**Expected behavior**
I expected the config to be able to continue and write the bytes.

**Screenshots**
https://user-images.githubusercontent.com/41132838/116956809-8583a080-ac96-11eb-9223-ab9868a8c749.png

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 0.1.13

**Comment by meinname** [comment]
Confirmed for the case when "Allow system-wide file access" is not enabled and file not existing.
If file already exists and/or "Allow system-wide file access" it works.
