### ISSUE TITLE
[BUG] Failed to connect to Nodejs

### ISSUE THREAD

**Issue by krombopulosM** [openbullet/OpenBullet2#254]
**Describe the bug**
Under the script stack with the interpreter set to NodeJS, after running start it gives the output "[Executing block Script] ConnectionException: Failed to connect to NodeJS. Refer to the inner exception for details."

**To Reproduce**
1. Go to Script
2. Click on NodeJS
3. Enter some JS and hit start

if it helps I'm not very knowledable with JS, so here is the script I tried to run. I left type to string:

function uuidv4() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}
var RequestId = uuidv4();
var Date = new Date().toString();

**Comment by openbullet** [comment]
Did you actually install NodeJS? OB2 doesn't come with it, you have to install it separately on your own.
