### ISSUE TITLE
[BUG] CPM limit for config stops checking after X amount of limit

### ISSUE THREAD

**Issue by krombopulosM** [openbullet/OpenBullet2#259]
when you set a CPM limit under the settings of a config and then run a job, it runs until it reaches the CPM limit and then stops.

to reproduce:

make a config, then go to the settings and set the cpm to something like 300
run a job and wait for the cpm to hit 300, and the job will halt.

**Comment by openbullet** [comment]
It's the intended behaviour, it will stop until enough time has passed and then check again a few, then stop, etc. It doesn't adjust speed dynamically right now, it just stops checking in order to fulfill the CPM requirements.
