### ISSUE TITLE
[BUG] Hits DB seems broken

### ISSUE THREAD

**Issue by bfx001** [openbullet/OpenBullet2#26]
cant export hits cant even select more than 1 at once (Ctrl + A dont work too). basically if you save hits to database the only way to get them is exporting database in a third party software.

**Comment by openbullet** [comment]
At the top you can select how many lines to display. If the browser cannot handle that many, please wait until I implement the same component that is in job viewer also in the hits tab, cause that one is virtualized and can handle many many lines.

**Comment by FaceSteel** [comment]
> At the top you can select how many lines to display. If the browser cannot handle that many, please wait until I implement the same component that is in job viewer also in the hits tab, cause that one is virtualized and can handle many many lines.

Thanks for your hard work, sir.  It's really appreciated, I hope you had an excellent run in your exams. ♥

**Comment by openbullet** [comment]
It would be nice to download the hits as txt as suggested in #184 when the user is using HTTP (and copy to clipboard is not allowed)

**Comment by openbullet** [comment]
This has been addressed here https://github.com/openbullet/OpenBullet2/commit/56bc22ee7f2651993f3d0af2ddc4ff6025438411
