### ISSUE TITLE
Can't Download pdf file [BUG]

### ISSUE THREAD

**Issue by ep5tein** [openbullet/OpenBullet2#267]
Can't Download Pdf With OB2 using last version, No Error, no Display of the block, no saved file it just skipping it, or sometime if I put the link directly in the request without using a variable, it is saved , but the size is always the same and the pdf is blank. here my code:
```
BLOCK:HttpRequest
  url = @link
  TYPE:STANDARD
  $""
  ""
ENDBLOCK

BLOCK:FileWrite
  path = "test.pdf"
  lines = @data.SOURCE
ENDBLOCK
```

Same config with same link on OB1 Working Well:
```
REQUEST GET "<link>" 
  
  -> FILE "test.pdf" 
```

Thanks

**Comment by openbullet** [comment]
```
BLOCK:HttpRequest
  url = "your_url"
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK

BLOCK:FileWriteBytes
  path = "myfile.pdf"
  content = @data.RAWSOURCE
ENDBLOCK
```
