### ISSUE TITLE
[BUG] PuppeteerSwitchToTab index give me a random tab everytime

### ISSUE THREAD

**Issue by timolarra** [openbullet/OpenBullet2#269]
Please try to open many tabs and select tab index 0 and every time you will get a random tab from those tabs and sometimes you get this error “Index was outside the bounds of the array.” when I put index 0, I don’t know why but in OB1 I don’t get this issue at all

**Comment by openbullet** [comment]
Could you please provide some LoliCode that I can use to replicate the issue? It would really help, thanks!

**Comment by MrAdhit** [comment]
```
BLOCK:PuppeteerOpenBrowser
ENDBLOCK

BLOCK:PuppeteerNavigateTo
ENDBLOCK

BLOCK:PuppeteerNewTab
ENDBLOCK

BLOCK:PuppeteerNavigateTo
ENDBLOCK

BLOCK:PuppeteerNewTab
ENDBLOCK

BLOCK:PuppeteerNavigateTo
ENDBLOCK

BLOCK:PuppeteerSwitchToTab
ENDBLOCK

BLOCK:PuppeteerSwitchToTab
  index = 1
ENDBLOCK
```

**Comment by timolarra** [comment]
The puppeteer still give a random Tab

**Comment by heav33n** [comment]
yeah still does
