### ISSUE TITLE
[BUG] User without login can change language

### ISSUE THREAD

**Issue by UnknowUsername** [openbullet/OpenBullet2#27]
Unknown user can change language by visiting my server ip and pressing this icon https://i.imgur.com/n4PKY6o.png, a bit un-secure, so maybe make unique cookie id, so every new visitor can set own language, but only that which was logged in?

**Comment by openbullet** [comment]
I was doing it with the cookie but @meinname didn't like it and asked to put it in settings :P

**Comment by meinname** [comment]
Cause cookie didn't work - at least for me :P
If you get it to work, it's fine

**Comment by openbullet** [comment]
Worked perfectly for me U_U but anyways I can make it selectable by users

**Comment by openbullet** [comment]
Partially addressed this but leaving it open so I'll remember to implement a way to set language in cookies as well

**Comment by openbullet** [comment]
Now you can edit `appsettings.json` and set `UseCookie` to `true` in the `Culture` section.
