### ISSUE TITLE
C# Convert but i can still debugg [REQUEST]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#270]
Hey Ruri, 

I have such issue when i convert the config to c# i am still able to debugg if you can fix this for hide config source then it will be helpfull
thanks.

**Comment by openbullet** [comment]
This is an intended feature. If you want to hide the source code, you can:
1. Set up a vps and invite guests to use your config (this completely prevents leaks)
or
2. Wait until I decide to reopen the crowdfunding and buy access to the bot that compiles configs to DLL so they can be obfuscated

**Comment by thanosbin10** [comment]
the first option is not good how should people upload wordlist & and they can upload any thing to vps.
the second sounds. i will wait.

**Comment by openbullet** [comment]
Guests can upload wordlists and proxies, but cannot access the config manager, they can only run configs using jobs. I made that feature for this exact purpose.
