### ISSUE TITLE
[BUG] [TEMP FIX] Proxy check doesn't update proxy status (Untested/Tested)

### ISSUE THREAD

**Issue by e393** [openbullet/OpenBullet2#272]
I saw this was a bug already and suggested to pres F5 to refresh the cache but that doesn't fix the issue, still doesn't change status of the proxy from being tested & untested, always show untested.

this is on 0.1.14 [Beta]

**Comment by e393** [comment]
found what the issue was, i originally had:
"WorkerThreads": 2000,
    "IOThreads": 1000,
    "ConnectionLimit": 1000

changed it back to: 
"WorkerThreads": 1000

now proxy status updates after checking...

**Comment by e393** [comment]
found a temp fix, after proxies are done checking (hanging at the end of the list) exit out OB2.exe and restart it

**Comment by openbullet** [comment]
It works with F5 now, just pushed the fix
