### ISSUE TITLE
[REQUEST] OB2.exe command window [System tray / Hidden]

### ISSUE THREAD

**Issue by e393** [openbullet/OpenBullet2#274]
have a command line option to run OB2.exe as --hidden window similar to selenium --hidden feature. 

OR

Minimize OB2.exe to system tray, really useful for VPS users who want anonymity, so jobs can still run without web browser being open/visible. really prefer option 1 over this though.

**Comment by openbullet** [comment]
I really don't understand this. How is hiding the console going to give you "anonimity"? Also, closing the browser does not stop the jobs, as long as the program is open in the console.
About the system tray icon, as far as I read this is only available in WPF applications on windows, so I'm not sure if this is even possible.

**Comment by e393** [comment]
> I really don't understand this. How is hiding the console going to give you "anonymity"? Also, closing the browser does not stop the jobs, as long as the program is open in the console.
> About the system tray icon, as far as I read this is only available in WPF applications on windows, so I'm not sure if this is even possible.

it gives it a soft anonymity but not having the command window always visible, and yes i know the browser doesn't stop the jobs from running which is good and thats my point, being able to close the browser and not have a command window always visible is a nice feature to have esp on VPS/home pc's. 

To me its just in the way, since we can close the browser and walk away while still have OB2 running in the background doing jobs. just my 0.02. this doesn't have to be a default feature, just make a command line (--hidden) by running OB2.exe from the command line.

system tray not so much needed since OB2 can be ran from other OS's

**Comment by openbullet** [comment]
As I said, it's probably not possible with a console application, just with WinForms/WPF applications. You need to use an external program such as this https://adontec.com/starthidden_e.htm in order to achieve what you want. I'm pretty sure you can also achieve the same with some VBS scripting, but yeah you need external code to achieve this.

**Comment by e393** [comment]
> As I said, it's probably not possible with a console application, just with WinForms/WPF applications. You need to use an external program such as this https://adontec.com/starthidden_e.htm in order to achieve what you want. I'm pretty sure you can also achieve the same with some VBS scripting, but yeah you need external code to achieve this.

it’a possible i’ve done it in C#

**Comment by e393** [comment]
while (running)
            {
                //Hide Server Windows (Set properties to windows application)
                Process.GetCurrentProcess().WaitForExit();

**Comment by openbullet** [comment]
The code you provided is incomplete I think. The method you posted doesn't do anything to hide the console window, https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-5.0

**Comment by e393** [comment]
> The code you provided is incomplete I think. The method you posted doesn't do anything to hide the console window, https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-5.0

sorry its you have to change the "OB2 console" to this
https://prnt.sc/13dfz29

**Comment by openbullet** [comment]
OB2 is cross platform, I cannot change it to a windows application and drop support for other platforms. Sorry but I'm not going to do this as it's not possible without breaking the compatibility with other systems or writing a dedicated build just for windows.
