### ISSUE TITLE
When I try to open OpenBullet2 it immediatelly closes.

### ISSUE THREAD

**Issue by Queirbeer** [openbullet/OpenBullet2#277]
When I try to open OpenBullet2 it immediatelly closes. What can I do to prevent this?

**Comment by Cyogenus** [comment]
Did you follow this guide 


https://discourse.openbullet.dev/t/openbullet-2-installation/329

**Comment by openbullet** [comment]
Launch it using the console command instead of double clicking the exe and you will see the error (usually you miss the runtime).

**Comment by HenryKim2022** [comment]
Iv'e got same probs...
Failed to load the dll from [C:\Add\OpenBullet2\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Add\OpenBullet2\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by openbullet** [comment]
You need the ASP.NET runtime, not the normal .NET runtime.
