### ISSUE TITLE
[BUG] Passing auth-proxy to captcha solving service

### ISSUE THREAD

**Issue by Cat5432** [openbullet/OpenBullet2#279]
**Describe the bug**
Unable to pass proxy parameter to any captcha solving service,
its very annoying as it makes solving captchas on certain site impossible.
**To Reproduce**
1. Go to config, stacker, make sample funcaptcha task
2. Click on UseProxy
3. Enter ur (http) auth proxy to test proxy and click to use it, use any format:
(http)domain.com:1111:user:pass
or
https://domain.com:1111:user:pass even freezes the app, same with http://
or (http)https://domain.com:1111:user:pass etc...
4. See error "[Executing block Solve Fun Captcha] ArgumentException: Requested value 'Http' was not found." or  "An error has occurred. This application may no longer respond until reloaded. Reload"

**Screenshots**
![image](https://user-images.githubusercontent.com/79338084/119738781-8799e300-be81-11eb-8baa-b7df15906ec7.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version new

**Comment by Cat5432** [comment]
More info 
 System.FormatException: The proxy port must be an integer
         at RuriLib.Models.Proxies.Proxy.Parse(String proxyString, ProxyType defaultType, String defaultUsername, String defaultPassword) in D:\a\OpenBullet2\OpenBullet2\RuriLib\Models\Proxies\Proxy.cs:line 103
         at OpenBullet2.Shared.Debugger.Run() in D:\a\OpenBullet2\OpenBullet2\OpenBullet2\Shared\Debugger.razor.cs:line

**Comment by openbullet** [comment]
OB2 splits the proxy according to the `:` character, so in this case it's assigning `https` to the host and `//domain.com` to the port, which fails to be converted to an integer. Please only use the domain without the url schema (`http://` or `https://`) at the start.

I will investigate the reason why it's also happening for proxies formatted as 
```
(http)domain.com:1111:user:pass
```
