### ISSUE TITLE
[BUG] Something wrong with Job stats

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#285]
**Describe the bug**
Sometimes, the Progress number is bypassing the number of loaded lines from a wordlist.

Sometimes, the Start button doesn't respond to the first click event or maybe it is taking much time to respond before locking the button.
which can cause the wordlist to be loaded twice, depends on how many time the button was clicked.

<img width="1689" alt="Screen_Shot_2021-05-29_at_10 21 28" src="https://user-images.githubusercontent.com/80313339/120067361-0e61e200-c073-11eb-93af-c750460b5ce2.png">
(the job already finished)

**Comment by xkeksi** [comment]
Same!

**Comment by openbullet** [comment]
Hopefully these will be fixed in the new client
