### ISSUE TITLE
[REQUEST] Proxy section improvements.

### ISSUE THREAD

**Issue by fastgamer917** [openbullet/OpenBullet2#287]
It could be best to make the following improvements in proxies section:-
1. Keep/Select specific country/ping/checktime and remove the remaining proxies.
2. An option within config settings to use only specific country proxies for that config. So we not need to worry about selecting proxy country. Job itself selects country proxy based on config proxy settings.
3. Move proxies to other group. Like user can make a group "US" and move all USA proxies to this group.
4. Ability to autodetect proxy type (http,https,socks4,socks5,ipv6)
5. [Optional] IPv6 proxies support.

**Comment by openbullet** [comment]
Please do not put all these requests into a single issue, make a separate issue for each of them.
1. I will do this
2. Open a separate issue
3. Open a separate issue
4. I don't know how I can do this honestly, without attempting to connect to each one (which will take a long time)
5. I need an IPv6 proxy to test in order to provide support for this feature, I couldn't find any yet

**Comment by fastgamer917** [comment]
1. Thanks.
2. #Done 
3. #Done  
4. I can help you with this. I have different program which auto detects the type of proxy. I can give you dll of that function. You can figure out from it and implement it. Once implemented, make sure you add option to select proxies based on type(http/socks ..etc). This is very required feature because many proxy provides are giving mixed proxies with different anonymity level, especially free scraped proxies.
5. I will give you access to ipv6 proxies. They are HQ proxies now and users are shifting to use them very fast.

I understand you are busy with your thesis work. But consider these recommendations.

**Comment by openbullet** [comment]
4. Yeah sure, if you want open a new issue and provide some reference code I can use when implementing this.
5. Sure, open an issue and send me a PM with the proxy on the forum thanks!
