### ISSUE TITLE
[BUG] Loli code Source or Header data gave config error

### ISSUE THREAD

**Issue by UnknowUsername** [openbullet/OpenBullet2#29]
if I use this command `IF STRINGKEY @data.HEADERS["Location"] Contains ""` and result will be 302 (redirect), it gave me result, but if it will be 200 Status response, then it give me error, means if data empty it give global error.
Just try to reproduce it on 2 links 
1 url where You are getting redirect, disable auto redirect ("http://google.com") https://i.imgur.com/USFAFDW.png
2 url with out redirect ("https://www.google.com/") https://i.imgur.com/vdypzGT.png
IF STRINGKEY @data.HEADERS["Location"] Contains ""
LOG "Works"
END
I found only 1 solution, parse all headers and if header contain "keyword from location" it will work

IF STRINGKEY @data.HEADERS Contains ""
LOG "Works"
END

or header parsing and

BLOCK:Parse
LABEL:locationMain
  input = @data.HEADERS
  MODE:LR
  => VAR @locationMain
ENDBLOCK

then IF STRINGKEY @locationMain Contains ""
So it means some problem with empty data, if it will not be found in code repsonse
In my way it was happen when I tried to check location header, but it doesnt found on 200 responce status.

**Comment by UnknowUsername** [comment]
> if I use this command `IF STRINGKEY @data.HEADERS["Location"] Contains ""` and result will be 302 (redirect), it gave me result, but if it will be 200 Status response, then it give me error, means if data empty it give global error.
> Just try to reproduce it on 2 links
> 1 url where You are getting redirect ("http://google.com") https://i.imgur.com/USFAFDW.png
> 2 url with out redirect ("https://www.google.com/") https://i.imgur.com/vdypzGT.png
> IF STRINGKEY @data.HEADERS["Location"] Contains ""
> LOG "Works"
> END
> I found only 1 solution, parse all headers and if header contain "keyword from location" it will work
> 
> IF STRINGKEY @data.HEADERS Contains ""
> LOG "Works"
> END
> 
> So it means some problem with empty data, if it will not be found in code repsonse

**Comment by openbullet** [comment]
If there is no `Location` key in the `data.HEADERS` dictionary it will throw an exception.
What you need to do is use a dictionary key (not string) and use the HasKey "Location"

**Comment by UnknowUsername** [comment]
> If there is no `Location` key in the `data.HEADERS` dictionary it will throw an exception.
> What you need to do is use a dictionary key (not string) and use the HasKey "Location"

Then what I`m doing wrong?
https://i.imgur.com/v8ZMJlM.png

**Comment by openbullet** [comment]
I don't understand what you're trying to do

**Comment by ewwink** [comment]
I think OB2 not capture headers if status code `301/302`? but if you want to get redirect URL use `data.ADDRESS`
