### ISSUE TITLE
[BUG] CPU goes to 99% usage, gives error

### ISSUE THREAD

**Issue by whole-egg** [openbullet/OpenBullet2#292]
CPU usage jumps to 99%, OB2 crashes, then I am given this error message:

      An exception occurred while iterating over the results of a query for context type 'OpenBullet2.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

This has occurred anywhere from 30 minutes to 2 hours from starting a job. Not sure what is directly causing it. 
Maybe it's from having multiple Windows profiles logged in on the same system? I have played around with Worker Threads and the amount of bots, but that hasn't seemed to fix the issue.

**Comment by openbullet** [comment]
There is an error in the code because multiple threads are using the same database connection at the same time and EF doesn't like it, I thought I fixed it but apparently I did not. Are you using 0.1.14 or above?

**Comment by whole-egg** [comment]
Yeah, I had just updated to the latest version before it started happening. Not sure if the bug occurred on 0.1.14 because I hadn't run any jobs before updating.

**Comment by whole-egg** [comment]
Update: 
I still got the same error message while using a different config, but OB2 didn't crash and the job continued as normal. Maybe the crashing was job-specific?
