### ISSUE TITLE
[BUG] Error when file path contains double quotes

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#299]
When using "Copy Path" in windows
![image](https://user-images.githubusercontent.com/41063376/121092956-9f6a5300-c801-11eb-9f5f-9c99d73f1a05.png)
there is double quotes is path, no matter if path contains space or not
and then i paste the path in OB2 and this happens

![image](https://user-images.githubusercontent.com/41063376/121092020-2caca800-c800-11eb-95de-6221dfc26585.png)

**Comment by Cyber-Criminal** [comment]
Actually this F***ed up my OB2, and i think i should wipe and reinstall OB2!
i made a job and then, i changed the Data pool to File and inserted a path that contained double quotes
i restarted OB2 dotnet.exe process and now all time :
![image](https://user-images.githubusercontent.com/41063376/121095796-3cc78600-c806-11eb-8bab-24adf26f549d.png)
Log :
https://pastebin.com/PM8YfYqV

**Comment by openbullet** [comment]
But why would you put the quotes in there in the first place? Seems like you want to break it on purpose to me...

**Comment by openbullet** [comment]
Sanitizing the `"` character is not good because it would only be valid for windows, on Linux you can have `"` in a filename. So this solution wouldn't be cross platform. Please take care of removing those characters yourself.

**Comment by Cyber-Criminal** [comment]
can remove only if the path contains double-quotes as the first and last char and the OS is windows, of only when file is not exist and path contains `"` at the first and last char

@openbullet 
can't fix it without making problems for people who use other operation systems?
