### ISSUE TITLE
[BUG] i Don't get the sublist at configs tab

### ISSUE THREAD

**Issue by matsver** [openbullet/OpenBullet2#3]
**Describe the bug**
When i click on the config tab in the menu, A submenu is supposed to open but it doesn't, this way i can't ave the config or edit the settings.

Click on config tab.

It's supossed to open a submenu, i got it before but now it doesn't work for some reason

https://i.imgur.com/R6gGDwy.png

**Desktop (please complete the following information):**
 - OS: Microsoft Windows NT 10.0.18363.0
 - Browser Chrome Versie 88.0.4324.190 (Officiële build) (64-bits)

**Comment by openbullet** [comment]
You have to open a config for the submenu to appear. Have you tried double clicking a config or selecting it and then clicking on the edit button?

**Comment by matsver** [comment]
> You have to open a config for the submenu to appear. Have you tried double clicking a config or selecting it and then clicking on the edit button?

Yes i tried that, i think it totally disappeared when i made a new config

**Comment by XazkerBoy** [comment]
Had the same issue, not sure why this happened, but full page refresh (Ctrl+F5) helped

**Comment by Laiteux** [comment]
Reopening as this seems to be a reproducible issue (even tho low priority), which requires a fix

**Comment by openbullet** [comment]
I fixed this yesterday I think https://github.com/openbullet/OpenBullet2/commit/8d8da5902c2839d8ea938962838de6e1111c3ff2
If it happens again after next update, reopen the issue
