### ISSUE TITLE
REQUEST PROBLEM [REQUEST] [BUG]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#302]
hey i have a proble with request using openbullet, when i request using openbullet is respond 

Access Diend with response code 403

but in Burp Suite it is working fine 
![image](https://user-images.githubusercontent.com/84645543/121196163-8a78d880-c870-11eb-8663-8b9ff51cb5a0.png)

**Comment by thanosbin10** [comment]
![image](https://user-images.githubusercontent.com/84645543/121200094-c3ff1300-c873-11eb-98d4-c8d961f0fc41.png)

**Comment by openbullet** [comment]
Just wondering, is there a specific reason why you're not using a normal HTTP request block to do this?

**Comment by openbullet** [comment]
I noticed the response from burp uses HTTP/2.0 so maybe it's automatically switching your request to HTTP/2.0.
OB2 doesn't do that, as HTTP/2.0 is not supported yet, and will not be supported for sure with the TCP block. Are you able to verify if this is the cause of the issue?

**Comment by thanosbin10** [comment]
Hey, i am used also Http block but not worked and i also used version 1.1 in burp suite but it worked also, so the problem is ssl i think burp suite there is a section which is called server certificates idk i have the feeling its because the certificate. 
![image](https://user-images.githubusercontent.com/84645543/121284865-c6965280-c8dd-11eb-80d4-45405ba6e28a.png)

**Comment by thanosbin10** [comment]
i figured out why its saying error 403,

openbullet2 have problem with self sign certificates/ssl

in burp suite i unchecked the usage of certificate
its gave me 403

![image](https://user-images.githubusercontent.com/84645543/121286049-964fb380-c8df-11eb-8a75-cb91aada8db9.png)

**Comment by openbullet** [comment]
1. Which OS are you on?
2. Which certificate are you using? Did you add a self-signed root CA to the OS?
3. Are you using burp interceptor while making the request with OB2? If you are, can you try without it?

**Comment by thanosbin10** [comment]
1. I am using Windows
2. I dont use any certificates but i think OP2 have problems with ssl because when i use port http:// in burpsuite i am getting same error like Openbullet2 request but when i use 443 the problem get fixed.
3. No i didnt used intercept while making the Request with OB2, there is extra selenium chrome, so i dont need use burp proxy for pc.

**Comment by thanosbin10** [comment]
hey bro, i found out the problem, it is because http version!!! When i use there was one option which auto changed the 1.1 to 2.0 i ticked it off and retried and then it gave me error 403 when i ticked it on it worked again so the problem was because HTTP/1.1.

I hope you add HTTP/2.0 in next version thanks!!

**Comment by openbullet** [comment]
> it is because http version
Yeah that's what I told you above. Follow this issue https://github.com/openbullet/OpenBullet2/issues/88 but don't expect anything soon as it's not a simple thing to implement since HTTP/2.0 uses a completely different way to handle requests with respect to HTTP/1.1
