### ISSUE TITLE
[REQUEST]Add a retry setting

### ISSUE THREAD

**Issue by xkeksi** [openbullet/OpenBullet2#304]
So, As many of you guys know, many services are Silent banning your proxies, and the hit gets marked as "bad", so my idea is to add a retry system in ob2 to fix hits skipping with free proxies!

(e.g)
i would recommend 3-6 and more for Free proxies (proxyscrape etc)
and for paid ones like 1-2 retries

example:
hit goes as bad, it rechecking it with a other proxy (x times, just like the value u set)

btw if you need additional informations what i tried to tell, say it

its for me 4am and im literal braindead so i'm sorry for that bad english lmao

**Comment by thanosbin10** [comment]
huh, your proxies get banned and then hits will marked as bad? do you mean this ?
i never had this problem you didnt any mistake in your setting of config? or keycheck probably.

**Comment by xkeksi** [comment]
?? Do you even know what silent ban'S are? lmaooo

Good example is minecraft..
If you check a good combo with paid proxies, you mostly get over 200 alts, but if you check them with free proxies that are silent banned from minecraft, you would only get like 10 alts

**Comment by xkeksi** [comment]
So it isnt any config issue....

**Comment by openbullet** [comment]
@xkeksi It has become evident that you are performing illegal activity so I'm going to delete the issue and block you from accessing the repository.
