### ISSUE TITLE
HTTP/2.0 [REQUEST]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#305]
Hey bro i have a problem with HTTP/1.1 its response access diened only HTTP/2.0 is working with the request, so my question is can you add HTTP/2.0 asap?
thanks

**Comment by openbullet** [comment]
https://github.com/openbullet/OpenBullet2/issues/88

**Comment by openbullet** [comment]
Remember I am updating OB2 for free so I'll add this whenever I have some time, do not expect this to be implemented soon.

**Comment by thanosbin10** [comment]
okay bro thanks for your help!
