### ISSUE TITLE
Clone config problem [BUG]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#306]
![image](https://user-images.githubusercontent.com/84645543/121412195-b8d7e000-c964-11eb-9509-e3861b7222d5.png)
Clone problem, when clone a config and try to run its give this error.

**Comment by openbullet** [comment]
I don't think this is related to the fact that you're cloning the config. I would really like to see the lolicode. Is there any way you can PM it to me on the forum?

**Comment by thanosbin10** [comment]
i got banned for 3 days :( i need wait for send it to you.

**Comment by thanosbin10** [comment]
Hey Ruri the problem is fixed i restarted openbullet and reinstalled sdk so it got fixed, thanks
