### ISSUE TITLE
Database not recording after Purge

### ISSUE THREAD

**Issue by Kuhicop** [openbullet/OpenBullet2#307]
After running some tasks:
![image](https://user-images.githubusercontent.com/27239965/121480911-e441e580-c9cb-11eb-88b2-b717dc1ddf46.png)

My hits database is empty. It was working before I pressed “Purge”. Now it’s not saving hits anymore neither writting anything to hard drive folder.

I’ve checked all columns and there aren’t filters applied.

**Comment by openbullet** [comment]
We tested this and couldn't reproduce, we tried
- Start job / Stop job / Purge / Start again
- Start job / Purge

and in both cases it works, the hits are there.
As a side note, if the hits fail to be stored in the DB they also fail to be stored to all following hit outputs, but it should log the exception to the console.

Can you please check if you have errors in the OB2 console?

**Comment by Kuhicop** [comment]
Well, I've reinstalled OB2 and trying to reproduce the issue, it's working now... 

What I did to "fix" this:

- Export configs

- rm -rf <openbullet2 folder>

- git clone https://github.com/openbullet/OpenBullet2.git

**Comment by Kuhicop** [comment]
Ok, just managed to reproduce it and get the error from the console:
![image](https://user-images.githubusercontent.com/27239965/121555384-4114be80-ca13-11eb-815f-cab1b19ff90c.png)

`fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'OpenBullet2.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Could not reload proxies from unknown source`

**Comment by openbullet** [comment]
It's the same exception that is being tracked on another issue https://github.com/openbullet/OpenBullet2/issues/292 please follow that one
