### ISSUE TITLE
[BUG] iframe error with non-headless puppeteer

### ISSUE THREAD

**Issue by EduMoreno142** [openbullet/OpenBullet2#308]
Switching and clicking elements inside iframe works fine in headless mode, but it doesn't work with the puppeteer window open.
Example:
```
BLOCK:PuppeteerOpenBrowser
ENDBLOCK

BLOCK:PuppeteerNavigateTo
  url = "https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php"
ENDBLOCK

BLOCK:PuppeteerWaitForElement
  findBy = XPath
  identifier = "/html/body/main/form/fieldset/div/div/div/iframe"
ENDBLOCK

BLOCK:PuppeteerSwitchToFrame
  findBy = XPath
  identifier = "/html/body/main/form/fieldset/div/div/div/iframe"
ENDBLOCK

```

**Comment by openbullet** [comment]
As you can read here this is due to CORS
https://stackoverflow.com/questions/58741745/how-to-fill-a-form-inside-an-iframe-with-puppeteer-sharp

Add these arguments to the puppeteer command line args in the config settings
```
--disable-web-security --disable-features=IsolateOrigins,site-per-process
```
