### ISSUE TITLE
[BUG] File Append Lines: LockRecursionException

### ISSUE THREAD

**Issue by thepasto** [openbullet/OpenBullet2#310]
The execution of the block FileAppendLines hangs only if the output file already exists. After several minutes a dilog shows:

![image](https://user-images.githubusercontent.com/593416/121675423-aae4a500-cab3-11eb-8fb6-a35a87542e78.png)

My os is archlinux arm, on Rpi 4. This happens with docker image and even with the arm release.
Anything is showed on the log. If you need more don't esitate to ask.
Thanks

**Comment by openbullet** [comment]
To clarify, the error only happens on linux, tested on windows and it works fine. I will research this soon, I have to set up a linux VM for debugging.

**Comment by openbullet** [comment]
Workaround while I work on this: write the following snippet in the LoliCode section (where you would have placed the block)
```cs
System.IO.File.AppendAllLines("path-to-file.txt", myList);
```
where `myList` is the variable which you want to write. This also works for WriteAllLines, WriteAllText and AppendAllText (just swap the name of the function).

**Comment by openbullet** [comment]
Should be fixed now (at least the exception). Please reopen if it happens again or if it takes forever to get a handle to the file.

**Comment by thepasto** [comment]
after a few days of testing, i can say nothing is changed, i can't write in file after the first time. Anyway using c# it works as expected. It's good enough for my purposes. Btw using c# in lolicode it's a cool feature, thank you

**Comment by openbullet** [comment]
Do you get the same exact exception (LockRecursionException) or another one? Let me know so I can properly address the issue.

**Comment by thepasto** [comment]
I updated to v0.1.19, i have any exception raised, the bot ends with success state, but it waits a lot before it ends (about 50 minutes).

BOT ENDED AFTER 3077819 ms WITH STATUS: SUCCESS

**Comment by openbullet** [comment]
If you want you can open a new issue since this exception doesn't appear anymore, but I'm not sure I will be able to reproduce it sadly.

**Comment by thepasto** [comment]
Don't mind, i can use System.IO.File.AppendAllLines, it's enough for me. Thanks once again

**Comment by openbullet** [comment]
I managed to fix this issue, it was an issue with `ReaderWriterLockSlim` on linux and mac, worked just fine on windows. Wrote my own helper class. This fix will be part of the next release (it's currently on a private repo).
