### ISSUE TITLE
Translate Block [BUG]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#311]
![image](https://user-images.githubusercontent.com/84645543/121682058-e2574f80-cabb-11eb-98de-622d78387596.png)

When i add to loliscript this 
BLOCK:Translate
LABEL:Sex
  input = @Gender
  translations = {("0", "Male"), ("1", "female")}
  => CAP @Sex
ENDBLOCK
and go to stacker come to loliscript back it shows me this error.

**Comment by openbullet** [comment]
This has been solved in 0.1.16 please update your OB2

**Comment by thanosbin10** [comment]
I think your update isnt working please fix this issue because many settings getting loose when i install and delete openbullet!!

**Comment by openbullet** [comment]
I don't understand what your issue is. Do you have trouble updating OB2? Just redownload the full build from github and replace everything, your settings will not be deleted if you overwrite.
