### ISSUE TITLE
Updater.exe isnt working [BUG]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#312]
Hey, i am updated openbullet2 with update its now on last version but update isnt updated correct thats why translate block still giving issue, Updater.exe isnt working!
Thanks.

**Comment by openbullet** [comment]
You have to close OB2 completely (also the terminal window) before running the updater otherwise it will not be able to update properly. Please redownload the full build (or the patch) from github and replace all old files.
