### ISSUE TITLE
block specific url in puppeteer [REQUEST]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#313]
i can code javascript/c# to block specific urls but if you could add a block for it which doing it automaticly it would help me really much thanks!

**Comment by openbullet** [comment]
I cannot understand what you mean, please provide an example or some code.

**Comment by thanosbin10** [comment]
if (
  // ...
  req.url() === "https://cdn-prod.securiti.ai/consent/sdk-stub.js"
) {
  req.abort();
}

**Comment by thanosbin10** [comment]
for make Puppeteer faster, when i go to setting and click load only documents and javascripts site isnt working so the only way is to block a site custom like the example that i made

**Comment by openbullet** [comment]
Okay I understood now, I can implement this.

**Comment by thanosbin10** [comment]
Okay, thanks!
