### ISSUE TITLE
[BUG]Cannot put new line between username and password variables 

### ISSUE THREAD

**Issue by alonetrifle** [openbullet/OpenBullet2#314]
Hello
Dear OB2 staff!
I can't put new line between password and username , which is essential for post data ,
I have tried \n but its not working here's a screenshot of what I'm talking about :
https://ibb.co/NnDhnZ9

Thanks for your great piece of software

**Comment by openbullet** [comment]
Are you sure you're not meant to send a literal `\n` character? Usually it works that way.
If you want to send a literal `\n` you need to write `\\n`. Anyways both were tested and they work so I'm closing this.

**Comment by alonetrifle** [comment]
> Are you sure you're not meant to send a literal `\n` character? Usually it works that way.
> If you want to send a literal `\n` you need to write `\\n`. Anyways both were tested and they work so I'm closing this.

No i just need to send each in a separate line orelse server won't recognise it i don't need \n ,the form should be like 
User=
Password=
And openbullet2 does not accept it

**Comment by openbullet** [comment]
```
BLOCK:HttpRequest
  url = "https://httpbin.org/post"
  method = POST
  TYPE:STANDARD
  "username:blabla@bla.test\\npasswort"
  "application/x-www-form-urlencoded"
ENDBLOCK
```
This code produces the following request (in fiddler)

![immagine](https://user-images.githubusercontent.com/48930622/121818541-1bdcb600-cc88-11eb-8d9a-fb917fff0514.png)

As you can see everything works as expected.
