### ISSUE TITLE
Ban keycheck contiune blocks [BUG]

### ISSUE THREAD

**Issue by thanosbin10** [openbullet/OpenBullet2#315]
Ban If No Match not working
![image](https://user-images.githubusercontent.com/84645543/122136237-58541180-ce42-11eb-97de-255a68885a3c.png)
the ban keycheck continue working with other blocks i dont know why

**Comment by openbullet** [comment]
Please check in the config settings if you have "BAN" in the statuses for which the bot should continue execution.
