### ISSUE TITLE
[BUG] Jobs seems to not work fine for me

### ISSUE THREAD

**Issue by FakeException** [openbullet/OpenBullet2#316]
When i start the job it spams an error like this in console and it seems that its not finding/testing anything, i tried both Spotify and Minecraft configs but none of them is working.

![image](https://user-images.githubusercontent.com/51448775/122185703-99bdde80-ce8d-11eb-83dd-a7f6fcdeff39.png)

![image](https://user-images.githubusercontent.com/51448775/122185679-932f6700-ce8d-11eb-81b9-03f2b69e3f47.png)

Version 0.1.16

 - OS: Windows 10
 - Browser Brave
 - Version 1.23.73

**Comment by EduardoProjects** [comment]
same thing is happening to me and i dont know what to do
