### ISSUE TITLE
[BUG] Disable LoliCode Block?

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#317]
In Stacker we can disable a Lolicode block
but it will automatically enabled after we go to Lolicode tab [`http://127.0.0.1:5000/config/edit/lolicode`] and then we come back in the Stacker tab

**Comment by openbullet** [comment]
If you want to "disable" a LoliCode block you need to comment out the code like this
```cs
/*
LoliCode here
*/
```

**Comment by Cyber-Criminal** [comment]
Ah, it was a good ability
I thought you going to make disable button to add `/*` and `*/` before and after the selected lolicode block xd

**Comment by openbullet** [comment]
No because adding it is easy but automatically removing it is hard and could screw up everything so I don't want to deal with that. It's better to disable it manually.

**Comment by openbullet** [comment]
Also if inside your LoliCode you already have multi-line comments, this will happen
```
/*
// Code 1
/*
*/
// Code 2
*/
```
as you can see it will stop commenting after the first `*/` and Code 2 will actually be executed, which is wrong! The only good way would be to add `//` at the start of each line, but it's still a bad solution in my opinion.
