### ISSUE TITLE
[BUG] Can't go back to Stacker after adding a function!

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#318]
Add a Compute / Date to Unix ... BLOCK
go to another tab and try to come back in Stacker
![image](https://user-images.githubusercontent.com/41063376/122241153-93545480-ced7-11eb-8d13-4207a7feb658.png)

**Comment by openbullet** [comment]
This is intended, you're leaving the variable name empty, which is invalid. Those blocks have fields that default to the "VAR" mode (instead of constant or interpolated) so you need to put something in there in order for them to be valid. It makes perfect sense.
