### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EduardoProjects** [openbullet/OpenBullet2#321]
So I keep getting these errors which have been happening if I run the program. I don't know how to resolve them.

![image](https://user-images.githubusercontent.com/86130548/122652371-710c4200-d136-11eb-8041-4542452a90d2.png)
![image](https://user-images.githubusercontent.com/86130548/122652377-77022300-d136-11eb-9485-b3d23367ca12.png)

 - OS: Windows 10 Pro
 - Browser: Chrome
 -Version: 20H2

**Additional context**
![image](https://user-images.githubusercontent.com/86130548/122652486-14f5ed80-d137-11eb-89c3-673ca9200445.png)
This is what I used to get but now it wont even show fails

**Comment by openbullet** [comment]
Those errors are already present in these issues 
https://github.com/openbullet/OpenBullet2/issues/316
https://github.com/openbullet/OpenBullet2/issues/292
