### ISSUE TITLE
[REQUEST] Add option to filter from Complete Log 

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#33]
there is no option to filter from Complete Log.

**Comment by openbullet** [comment]
Can you please explain what exactly do you mean by filter? If you mean search, just use CTRL+F since you're in a browser.

**Comment by Rohan4412s** [comment]
yes I meant that. search

**Comment by Rohan4412s** [comment]
but I want that search tab like OB1

**Comment by openbullet** [comment]
Why though? Isn't the browser's search function good enough?

**Comment by Rohan4412s** [comment]
yes, it's good too.

**Comment by openbullet** [comment]
Then sorry but I'm gonna close this as it's not vital to have a separate search ^^
