### ISSUE TITLE
[REQUEST] BOTNUM Variable (Parallelizer Type = ThreadBased)

### ISSUE THREAD

**Issue by thisisthelongestusernameyouhaveeverseen** [openbullet/OpenBullet2#332]
Add BOTNUM Variable and force the runner to use ThreadBased parallelizer type when this variable used in a config
or

**Comment by openbullet** [comment]
This would be too much of a strong dependency between a config and the parallelizer type in my opinion. I think it would be better to implement a different approach, where there is a pool of bot numbers, and when a new operation starts the task will take the first available number and then free it up again once finished.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
low priority or lowest priority ☹️💔

**Comment by openbullet** [comment]
BOTNUM is going to be implemented sooner or later, but for now there is no way to use it in OB2.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
i saw this commit today, thanks for your time
from next release, we can use BOTNUM variable in all parallelizer types or only in specified parallelizer type?
@openbullet

**Comment by openbullet** [comment]
Every parallelizer as it's not based on threads but on data line indices modulo'ed by bots
