### ISSUE TITLE
[REQUEST] A major feature is missing at OB2

### ISSUE THREAD

**Issue by bofizim** [openbullet/OpenBullet2#334]
While OB2 comes with some great new features, it has a major feature missing.

Missing feature: Custom line input to start from isn't available.

Example: Suppose I have a text file of 1000 lines, and I want to start it from line number 501. But OB2 is missing this feature while OB1 has the feature available.

I guess you got my point. Thanks to consider my request as a high priority :)

**Comment by openbullet** [comment]
This is already present, it's called `Skip` now. You can configure it in the job options.
