### ISSUE TITLE
[REQUEST] SSH Auth methods available

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#335]
Add a block to check if a ssh server, supports publickey or password or both auth methods

**Comment by openbullet** [comment]
I will add the block for the other authentication method. You can try to connect via password first, and then if it fails (use SAFE mode and make an IF statement on the `data.ERROR` variable) you can try to login with the private key.

**Comment by Cyber-Criminal** [comment]
@openbullet 
is that like `ssh -v` or 'ssh-auth-methods.nse' script in Nmap?
can i get an output like :
>debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password

or

>\> nmap.exe -p 22 --script ssh-auth-methods scanne.nmap.com
>
>Starting Nmap 7.70 ( https://nmap.org ) at ...
Nmap scan report for scanne.nmap.com (45.33.49.119)
Host is up (0.16s latency).
rDNS record for 45.33.49.119: ack.nmap.org
> 
>PORT   STATE SERVICE
22/tcp open  ssh
| ssh-auth-methods:
|   Supported authentication methods:
|     publickey
|     gssapi-keyex
|     gssapi-with-mic
|_    password
> 
>Nmap done: 1 IP address (1 host up) scanned in 10.18 seconds

i mean can i get a list of all available auth methods?

**Comment by openbullet** [comment]
No, you can only authenticate via username/password or username/key. I did not add other methods, and I don't think the library lets me verify which ones are accepted before actually attempting to authenticate. So since there are 2 blocks for 2 methods, just use one and catch the exceptions, in case of an error you know it's most likely the other one, recreating exactly the behaviour you want.

**Comment by Cyber-Criminal** [comment]
@openbullet

i found how can get list of accepted auth methods on ssh
`Attempt "none" authentication which usually will (and should) fail. As part of the failure, this function will return an array of accepted authentication methods.` (https://www.php.net/manual/en/function.ssh2-auth-none.php)

https://net-ssh.github.io/net-ssh/classes/Net/SSH/Authentication/Methods/None.html

You can add another block in SSH blocks as 'None Auth Method', or just change 'Password Auth Method' to 'None Auth Method' when Username and Password is Empty

**Comment by Cyber-Criminal** [comment]
@openbullet 
because when i do password auth, i can't get all available auth methods

if you don't want to add another block, just change 'pass auth' to 'none auth' when both Username and Password is empty in 'Pass Auth Block'
![image](https://user-images.githubusercontent.com/41063376/125472810-4b5bfa08-2743-47d3-9220-f030225bec79.png)

**Comment by openbullet** [comment]
Fine, I added the new block. It still requires a username though, you cannot log in at all without a username.

**Comment by Cyber-Criminal** [comment]
OK, thank you, i will try it

**Comment by Cyber-Criminal** [comment]
@openbullet 
![image](https://user-images.githubusercontent.com/41063376/125696673-361db1cd-1c61-433d-bdb4-c61f1852b7fa.png)
is this text stored in a variable?

**Comment by openbullet** [comment]
No. If it's successful it will go to the next block, if not it will fail with an error. Enable SAFE mode and do a keycheck on `data.ERROR` as usual.
