### ISSUE TITLE
[BUG] SolveCaptcha.com won't work

### ISSUE THREAD

**Issue by nillenalle4** [openbullet/OpenBullet2#338]
**Describe the bug**
Basically that SolveCaptcha won't work

**To Reproduce**
1. Go to RL-Settings
2. Click on Captcha
3. Scroll down to Solvecaptcha & enter Api-Key

**Expected behavior**
I'd expect it to actually work, like the twocaptcha api

**Screenshots**
https://discourse.openbullet.dev/uploads/default/optimized/2X/c/c0d423dbd4120b8f1afcc402f6eeb08440e8bfab_2_690x420.png

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Chrome
 - 22

**Comment by openbullet** [comment]
Fixed
