### ISSUE TITLE
[BUG] Openbullet 2 forzen after I left it running for a night

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#34]
it forzes and the cmd tab was open but couldn't able load http://localhost:5000/  I left 2 configs running for a night.

**Comment by openbullet** [comment]
Did you perhaps click inside the cmd? Because windows puts a process in "paused" state if you click inside the terminal window, can you make sure it doesn't say something like "Selection" in the title of the terminal console? If it does, you can press any key to unpause it again.

**Comment by Rohan4412s** [comment]
no, I didn't click inside the cmd.

**Comment by Rohan4412s** [comment]
![1Capture](https://user-images.githubusercontent.com/53138230/110595969-b9fe4300-81a4-11eb-9d71-0d072ba385a1.PNG)

**Comment by Cyber-Criminal** [comment]
![image](https://user-images.githubusercontent.com/41063376/110626913-917f4480-81b6-11eb-89eb-b64da2738123.png)
Change 'Turn off hard disk after' to '0' and 'Apply' to solve this problem

**Comment by openbullet** [comment]
We would like some new feedback on this. Also mind that if the page ever freezes you can try reloading it (maybe it just lost connection to the backend).

**Comment by openbullet** [comment]
Closing for no reply from the user
