### ISSUE TITLE
high CPU usage even after the job is finished[BUG]

### ISSUE THREAD

**Issue by shakshak12** [openbullet/OpenBullet2#341]
after the job is finished in the runner the CPU is still more than 40% even after removing the job while it was less than 10% without the job so logically it should go to 10% after finishing the job
![image](https://user-images.githubusercontent.com/87039966/124830747-05720380-df83-11eb-8921-eee8d75ea902.png)

**Comment by openbullet** [comment]
Closing this in favor of https://github.com/openbullet/OpenBullet2/issues/341 which provides more info about this
