### ISSUE TITLE
[REQUEST] Ban proxy after good status

### ISSUE THREAD

**Issue by rasch0r** [openbullet/OpenBullet2#342]
If possible, I'd like to see this option in OB2 as well.
Thanks and keep up the good work! :) 

![prev](https://user-images.githubusercontent.com/87143359/124962421-1f0c5d00-e00e-11eb-847b-f645c46db2af.png)

**Comment by openbullet** [comment]
This is already implemented, it's in the config settings page.

**Comment by rasch0r** [comment]
Oh, thank you for the explanation
