### ISSUE TITLE
[REQUEST] Custom Proxy for Request Block

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#346]
Add 'Proxy Type / IP / PORT / Proxy Auth Creds' in Request Block

**Comment by Cyber-Criminal** [comment]
good if you add three option inside request block :

- DEFAULT (if proxy for the job is OFF, then req without proxy, or use the bot's proxy if it's ON)
- ADD CUSTOM PROXY
- DON'T USE ANY PROXY (Even if proxy is ON for the Job)

**Comment by openbullet** [comment]
https://discourse.openbullet.dev/t/setting-a-temporary-proxy/1728

**Comment by Cyber-Criminal** [comment]
@openbullet 
i tried that and also this one :
https://discourse.openbullet.dev/t/add-block-use-proxy-and-other-block-proxyless/921/3

But none of them works,
Can you send me a screenshot of lolicode you used and worked in openbullet2?
or share the lolicode

**Comment by openbullet** [comment]
Everything works correctly, please write your LoliCode so I can see what you're doing wrong.

**Comment by Cyber-Criminal** [comment]
@openbullet 
i just pasted your code
![image](https://user-images.githubusercontent.com/41063376/125695826-440df5db-d465-4e9d-91b5-a57fef7302c9.png)
![image](https://user-images.githubusercontent.com/41063376/125696047-cf8887a3-f7ad-4831-bf50-38b2963fa5c3.png)
https://discourse.openbullet.dev/t/setting-a-temporary-proxy/1728

**Comment by Cyber-Criminal** [comment]
![image](https://user-images.githubusercontent.com/41063376/125696429-c24f2356-77a4-469e-8f2a-1b1667e6442a.png)
![image](https://user-images.githubusercontent.com/41063376/125696530-98639569-a5e8-4810-b031-bece934aae36.png)
https://discourse.openbullet.dev/t/add-block-use-proxy-and-other-block-proxyless/921/3

**Comment by openbullet** [comment]
Replace `ProxyType` with `RuriLib.Models.Proxies.ProxyType`. This error happens because you don't have the namespace `RuriLib.Models.Proxies` imported above in the "usings" section. Also remember to properly set up the port, username and password when you run otherwise nothing will work ^^

**Comment by Cyber-Criminal** [comment]
@openbullet 
still not works :'(
![image](https://user-images.githubusercontent.com/41063376/125698520-1d0d949d-0c4c-49b7-b359-0ccb8798af70.png)

**Comment by openbullet** [comment]
Because you started without a proxy. This code is only to change the proxy if you already have one. If you don't have a proxy you have to use the other code

```csharp
data.Proxy = new RuriLib.Models.Proxies.Proxy("127.0.0.1", 9050, RuriLib.Models.Proxies.ProxyType.Socks5, "username", "password");
data.UseProxy = true;

// Here put the request block

data.UseProxy = false;
```
If you want me to add some syntax sugar for LoliCode to do this because you don't want to use C# then open a separate issue.

**Comment by Cyber-Criminal** [comment]
Finally... problem solved
thank you
