### ISSUE TITLE
[BUG] IMAP cant catch bad credentials in keycheck

### ISSUE THREAD

**Issue by sero01000** [openbullet/OpenBullet2#347]
Safe mode didnt help.

i have this code:
************************************************
BLOCK:ImapLogin
LABEL:Login_imap
  email = @input.USER
  password = @input.PASS
  openInbox = False
ENDBLOCK

BLOCK:Keycheck
LABEL:Keycheck_imap_login
  banIfNoMatch = False
  KEYCHAIN FAIL OR
    STRINGKEY @data.ERROR Contains "MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected"
    STRINGKEY @data.ERROR Contains "Exception caught and saved to data.ERROR: System.IO.IOException: The read operation failed, see inner exception"
    STRINGKEY @data.ERROR Contains "Invalid login or password"
    STRINGKEY @data.ERROR Contains "The IMAP server has unexpectedly disconnected."
  KEYCHAIN SUCCESS OR
    STRINGKEY @data.ERROR Contains ""
ENDBLOCK
************************************************

**ERROR**:
Connected to imap.mail.ru on port 993. SSL/TLS: True

>> Keycheck_imap_conn (CheckCondition) <<

Matched key Contains

>> Login_imap (ImapLogin) <<

[Executing block Login_imap] ImapProtocolException: The IMAP server has unexpectedly disconnected.

BOT ENDED AFTER 2856 ms WITH STATUS: ERROR
************************************************

Desktop :
 - OS: windows 10
 - Version 0.1.20

**Comment by openbullet** [comment]
It seems like it's something wrong with the server
https://stackoverflow.com/questions/54503496/the-imap-server-has-unexpectedly-disconnected-on-mailkit-getmessage-method
Maybe try again later? Or change proxy / VPN.

**Comment by openbullet** [comment]
Please use the Imap Get Log block, it's all in there. Closing the issue.
