### ISSUE TITLE
HTTP/2.0 Problem! OpenBullet2 [Feature]: 

### ISSUE THREAD

**Issue by Fankybowesly** [openbullet/OpenBullet2#350]
Openbullet 2 doesnt have HTTP/2.0 it is a big problem, because many sites upgraded to HTTP/2.0 and openbullet2 always get detected by sites as a bot request because HTTP/1.1.
I think this update is really important for openbullet2 please do this update in the next update releases.

Thanks to Ruri!

**Comment by openbullet** [comment]
Please next time search before you open an issue, thanks https://github.com/openbullet/OpenBullet2/issues/88
