### ISSUE TITLE
How to input text field in iframe ?

### ISSUE THREAD

**Issue by jinmvp** [openbullet/OpenBullet2#351]
For example : i have a site that render text field in iframe. I cant make Puppeteerto input it.
I got error like below

`Exception caught and saved to data.ERROR: System.IndexOutOfRangeException: Index was outside the bounds of the array.`

**Comment by Fankybowesly** [comment]
You must use Switch to Frame block and then do your work. 
![image](https://user-images.githubusercontent.com/87569004/126072266-93b1c5fe-75e9-4715-b60c-37ddaa2181ac.png)

**Comment by openbullet** [comment]
As answered above, switch to the frame first (you have to target the iframe element) and then you will be able to input what you want. To switch out, there is another block to return to the main frame.
