### ISSUE TITLE
Need help why is it saying banned or error 

### ISSUE THREAD

**Issue by TheExxotik** [openbullet/OpenBullet2#354]
Need help why is it saying banned or error 

yes i have put my word list a Credentials

**Comment by TheExxotik** [comment]
Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'OpenBullet2.ApplicationDbContext'.
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
      System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         
         the code the ob2 is giving me

**Comment by openbullet** [comment]
Which version of OB2 are you using? I think I fixed this issue one of the past few days so you might want to wait for 0.1.21 and it should be solved, but it's not a game breaking bug. Are you sure the config you're using is made using the same Credentials wordlist type and not another one? Because some people edit the Environment.ini and use a modded version so that might be why you're getting bans and errors.

**Comment by TheExxotik** [comment]
ill just wait bc it does supprt credential

**Comment by openbullet** [comment]
Okay I am going to close this then, reopen if it happens again after 0.1.21
