### ISSUE TITLE
CONTROL+ S [Bug]: 

### ISSUE THREAD

**Issue by Fankybowesly** [openbullet/OpenBullet2#357]
### Version of the software

0.1.20

### Operating system

Any

### Browser

Any

### What happened?

When i am change the config name and enter CONTROL + S its says saved the config but when i reload the configs it isnt saved.
and with the save button to save is working perfectly.

**Comment by openbullet** [comment]
Literally just tried exactly what you said and worked without any problem. Cannot reproduce.

**Comment by openbullet** [comment]
Okay I managed to reproduce the bug, if you hit CTRL+S while you're still editing the field it doesn't work, but if you click away from the field and then CTRL+S it does work. I don't consider this a bug worth fixing to be honest, just click outside of the box before saving, cause the data binding updates the value only on focus out and not on type.

**Comment by Fankybowesly** [comment]
Okay, can you maybe make a warning or something because its really confusing(isnt required it would just help) if it says saved and it isnt saved.

**Comment by openbullet** [comment]
Detecting this is way more complex than actually fixing it, so no. Sorry. Maybe one day I will fix it but it's low priority, just remember as a general rule to click outside of the boxes before saving after you typed some text. This applies to stacker too.
