### ISSUE TITLE
[BUG] Not asking for password

### ISSUE THREAD

**Issue by Generation88** [openbullet/OpenBullet2#36]
i enabled the password for admin option & set a password last night.

now it dosen't seem to work. it logs in without a password.

also maybe i noticed the ob settings were reset automatically after i shutdown openbullet last time.

let me know if you need any logs

**Comment by Cyber-Criminal** [comment]
![image](https://user-images.githubusercontent.com/41063376/110590158-a810a600-818c-11eb-8998-242f77329069.png)

Change password, then enable 'Require admin login', and then click on 'Save'
now go to 'Home' tab and enter you Username and Password
after you logged in, your season will saved as Cookie, so next time you run OB, you will not be asked for your credentials except when Cookies cleared or expired (You can set Cookie expire time in settings too)
if you wanna be sure user management system is working, open 'Incognito Windows' in your browser then see if it's asking to login or not

if it's not working, maybe the OB2 folder have bad permissions, you have to change files permission or open ASPnetCoreRuntime as Administrator

**Comment by openbullet** [comment]
Remember to save the settings. Also you can log out from the current session in the homepage of the program.

**Comment by Generation88** [comment]
worked Perfectly
