### ISSUE TITLE
[REQUEST] ABOUT HIT VIEW

### ISSUE THREAD

**Issue by LittlePrinceOB** [openbullet/OpenBullet2#360]
I created topic here:
https://discourse.openbullet.dev/t/about-hit/3477
thanks.

**Comment by JReming85** [comment]
Why not just use the filter?
![image](https://user-images.githubusercontent.com/21246660/126208807-094b8c81-eeb0-4c90-8a21-2f2cdb756609.png)
or export to csv or something and sort from there

**Comment by shakshak12** [comment]
you can query the local database just use  https://sqlitebrowser.org/
