### ISSUE TITLE
[Bug]: Job tested count during a server restart/shutdown.

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#361]
### Version of the software

0.1.20

### Operating system

Windows 10

### Browser

Cent Browser

### What happened?

I'm running it on a RDP. And since this hoster is a bit unreliable, it just shuts down my server for no apparent reason.

When I restart, OB2's tested count goes back to 0.

Is there a way to know where I should continue? Is there a log somewhere?

Thanks Ruri.

**Comment by openbullet** [comment]
There is currently an issue related to this, I partially fixed it but I still need to do this https://github.com/openbullet/OpenBullet2/issues/355 follow that issue and when it's closed it should be fixed.
