### ISSUE TITLE
[Bug]: Hits -> Edit -> X = Save

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#362]
### Version of the software

0.1.20

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser

Chrome 91 / Opera 77.0.4054.203

### What happened?

If you try and edit any record and then try to press the X to back out it will save the changes

**Comment by openbullet** [comment]
I think it will only change them for the cached version, it will not write them to the databse, can you please check if when you press F5 you get back the original hit? Thanks

**Comment by JReming85** [comment]
You are correct, its just on the local cache and gets restored after however if you edit another one it saves both
