### ISSUE TITLE
[Bug]: not playing hit sound

### ISSUE THREAD

**Issue by moutsa** [openbullet/OpenBullet2#365]
### Version of the software

0.1.20

### Operating system

windows 10

### Browser

chrome

### What happened?

I have enabled to play a sound at hit but not working. At settings menu when i click at speaker icon i can hear the sound. At scaning when i have a hit not working.

**Comment by openbullet** [comment]
Another guy had this bug but I could not reproduce it on my end, tried on every system and every browser and still fine. The only workaround I found is to add this piece of LoliCode at the end of every config. This will play the sound on the computer that is running OB2 so it only works if you access OB2 from the same PC where you opened the program (and not from remote).

```csharp
IF STRINGKEY @data.STATUS EqualTo "SUCCESS"
System.Media.SoundPlayer myPlayer = new System.Media.SoundPlayer();
myPlayer.SoundLocation = @"wwwroot/sounds/hit.wav";
myPlayer.Play();
END
```

**Comment by moutsa** [comment]
Thanks for the answer...with LoliCode it's working perfectly.

**Comment by openbullet** [comment]
Should be ok in the new web client, otherwise the workaround is still valid
