### ISSUE TITLE
[REQUEST] Block delete confirmation?

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#366]
**Is your feature request related to a problem? Please describe.**
I'm working with an RDP and things can get laggy sometimes. It would be very helpful if there's a confirmation modal or something whenever you delete a block. I lost 2 blocks where I really worked hard on.

**Describe the solution you'd like**
A great solution would be a simple modal confirmation for deletion or make "Delete" delete the block without confirmation. However, clicking the X button should show a confirmation.

**Describe alternatives you've considered**
I haven't thought of any as this is the only way I know how to remove blocks.

**Additional context**

**Comment by openbullet** [comment]
If you delete a block you can press the undo button (in grey, above the stack) and it will come right back, no need to confirm deletion as it can quickly become annoying.
