### ISSUE TITLE
[Bug]: PuppeteerNewTab automatically close tab

### ISSUE THREAD

**Issue by jinmvp** [openbullet/OpenBullet2#373]
### Version of the software

0.1.21

### Operating system

Windows 10 x64

### Browser

Chrome 92.0.4515.107 (Official Build) (64-bit)

### What happened?

A bug happened! PuppeteerNewTab got problem, it automatically close my current tab and open a new page.

**Comment by jinmvp** [comment]
Can someone address this?

**Comment by openbullet** [comment]
I am on vacation, I will try to check it out once I'm back

**Comment by jinmvp** [comment]
> I am on vacation, I will try to check it out once I'm back

All good, enjoy your vacation Ruri :)
