### ISSUE TITLE
[Bug]: Job Details -> Showing Proxy Group (x) instead of Proxy Group Name

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#374]
### Version of the software

0.1.21

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser

Chrome 91 / Opera 77.0.4054.203

### What happened?

When viewing a job's details it no longer displays the proxy groups name, now it just displays the index number.

**Comment by openbullet** [comment]
I don't think it ever displayed the group name 🤔 but ye sure I can make it so that it shows the name

**Comment by JReming85** [comment]
My apologies I guess I wasnt paying attention before the update
