### ISSUE TITLE
Converting PDF files to text files

### ISSUE THREAD

**Issue by theamericans47** [openbullet/OpenBullet2#379]
**Is your feature request related to a problem? Please describe.**
I use OB2 to download a lot of PDF to parse them after having converted in text files. I usually use a bash script after downloading PDF files with OB2 but I would like avoiding this and use 100% OB2 because text parsed in pdf files are used after with POST requests on other website etc.

**Describe the solution you'd like**
A block with input path to pdf file, and output a string variable of the pdf. You can make an option to save directly to a txt file if you want to.

**Describe alternatives you've considered**
I tried using my bash command directly in shell block, but I failed, still some error with pdf file not found whereas it has been download by OB2.
I also tried a python script but impossible to import PyPDF2

**Comment by openbullet** [comment]
Please refer to the solutions we gave you
https://github.com/openbullet/OpenBullet2/issues/378#issuecomment-889328808
https://discourse.openbullet.dev/t/shell-code-cant-find-my-file/3600/10
