### ISSUE TITLE
[BUG] OB2 froze after I put Show 4000 Items in http://localhost:5000/proxies/groups

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#38]
it froze after I put 4000 in the show items in proxies group

**Comment by Rohan4412s** [comment]
total proxies are 4000

**Comment by openbullet** [comment]
It's a browser, it has trouble displaying that much data. Why are you displaying all 4000 proxies in a single page anyways?

**Comment by dontbanmeplz** [comment]
Prob just sys overload b/c that is reasaaly stupid

**Comment by openbullet** [comment]
Closing this as it's pointless to just display 4000 proxies on a webpage for no reason at all
