### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Znunu** [openbullet/OpenBullet2#380]
I like openbullet so far. The stack especially is fun! But I've had issues :(
Is there a matrix/IRC/telegram/slack/discord thing where I can get help?
(Sorry for asking here, if it's not super appropriate)

**Comment by theamericans47** [comment]
https://discourse.openbullet.dev/

**Comment by Fankybowesly** [comment]
Please go to https://discourse.openbullet.dev/ and ask questions. github is there to report bugs or request for Features.
