### ISSUE TITLE
[REQUEST] Add more versions of OB2 on docker.hub

### ISSUE THREAD

**Issue by Carontes** [openbullet/OpenBullet2#382]
**Describe the solution you'd like**
Could be useful, for people who have issues with new versions, to roll back to the previous version or to another version they would like to install. Right now it's only possible to install the latest version of OB2 via docker.hub

**Comment by meinname** [comment]
Ok, i changed the build script here https://github.com/openbullet/OpenBullet2/commit/c4648fc862978efe4848eba97ef26f8d0888847
i think/hope starting with 0.1.22 it should also be uploaded with an extra tag which is the version number.
