### ISSUE TITLE
[REQUEST] Multi-line support for regex.

### ISSUE THREAD

**Issue by omimic12** [openbullet/OpenBullet2#394]
Could you please add support for multi-line regex? I usually have to make 2-3 separate parse blocks with regex when i'm unable to use multi-line, which would simplify it to a single block.

**Comment by its5Q** [comment]
I will look into that, should be easy to implement

**Comment by Cyber-Criminal** [comment]
You can combine multiple RegEx formulas in one :
https://stackoverflow.com/questions/869809/combine-regexp

**Comment by omimic12** [comment]
> You can combine multiple RegEx formulas in one :
> https://stackoverflow.com/questions/869809/combine-regexp

Currently, you're unable to use the `does not match` method as mentioned in that link you provided. 
https://i.gyazo.com/8c2bd4bf11a93fa5a64bd905f3eb7f6a.mp4

With multiline support, this can be done. Data slicing options only have MatchesRegex, so this RegEx expression is important in being recognised.

**Comment by openbullet** [comment]
> With multiline support, this can be done. Data slicing options only have MatchesRegex, so this RegEx expression is important in being recognised.

Multiline support is only getting added for the parse block. It will not be supported in data slicing.

**Comment by openbullet** [comment]
Merged
