### ISSUE TITLE
[REQUEST] Shuffle wordlist option in Job settings

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#397]
Shuffle Wordlist
a good option,
no matter if can't resume anymore
although it is not impossible to have resume ability with this

**Comment by its5Q** [comment]
That would be a good feature, but currently, the wordlist is not being loaded into memory, but it's read line by line. If you would want that to be added, it would require to load the entire wordlist into memory. Maybe I'll look into that later, after the native UI branch will be merged with current version.

**Comment by openbullet** [comment]
Honestly I think he just wants to click a button and edit the source file directly. Am I wrong @Cyber-Criminal ?
Loading the entire wordlist into memory is not a good idea, some people use wordlists of a few gigabytes. I was doing this with OB1 and it was an issue ^^ Maybe in the future I will add a section with some tools to process wordlists but it's low priority right now.

**Comment by Cyber-Criminal** [comment]
@its5Q 
@openbullet 

can't load a chunk, shuffle and use, and then another chunk?
then can even resume after stop, by setting chunk size, and number of tested chunks

**Comment by openbullet** [comment]
@Cyber-Criminal no sorry, this is out of scope for this software. It would add too much complexity on top of the current wordlists system. Use an external tool to shuffle.

**Comment by Cyber-Criminal** [comment]
@openbullet 
yes, i agree you about that idea
but still you can add a tiny option to do this (with a warning about high ram usage of this feature and that can't use SKIP to resume the shuffled job that stopped before)

and, do you want to add a Tools section in OB2 in future?
