### ISSUE TITLE
[Bug]: AggregateException

### ISSUE THREAD

**Issue by giannitv** [openbullet/OpenBullet2#398]
### Version of the software

0.1.21

### Operating system

Windows 10

### Browser

Chrome

### What happened?

A bug happened!it doesn't make me start the jobs anymore, I restart the console and it works but then it happens again a few times

here is the error

AggregateException
One or more errors occurred. (A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.)

**Comment by Fankybowesly** [comment]
in my case the openbullet2.exe is closing idk why

**Comment by openbullet** [comment]
I changed some things in the last few versions. Please open again if you exprience this issue in the latest version or provide more information to replicate. Thanks!
