### ISSUE TITLE
[REQUEST] Add Support For Downloading All Hits

### ISSUE THREAD

**Issue by usdogu** [openbullet/OpenBullet2#399]
**Is your feature request related to a problem? Please describe.**
Please add an option to download all hits selecting one by one is a pain

**Describe the solution you'd like**
A button to Hits section to download all hits would be awesome

**Additional context**
[there](https://discourse.openbullet.dev/t/suggestion-adding-download-hits/1501) is already a question in ob forum (not mine)

**Comment by openbullet** [comment]
This was already implemented. Simply select filtered instead of selected in the dropdown and then, without setting any filters, download the hits.
