### ISSUE TITLE
[BUG] Webpage times out

### ISSUE THREAD

**Issue by dontbanmeplz** [openbullet/OpenBullet2#4]
**Describe the bug**
I run the file and the webpage times out

**To Reproduce**
1. Run the program

**Expected behavior**
The setup

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu server
 - Browser safari
 - Version 1

**Smartphone (please complete the following information):**
 - Device: 

**Additional context**

**Comment by openbullet** [comment]
Gonna need more context here. Which page did you try to load exactly? Have you tried `http://localhost:5000`?

**Comment by dontbanmeplz** [comment]
Well it was the ip of the server then 5000

**Comment by openbullet** [comment]
Yes if you're hosting this on remote then you need to do that ^_^

**Comment by dontbanmeplz** [comment]
But that didnt work

**Comment by openbullet** [comment]
If you're running it locally then you have tro try `localhost:5000` or `127.0.0.1:5000`
If you're running it from remote, then you have to open the port 5000 for TCP in the firewall of the host (inbound and outbound) and use `your_server_ip:5000`

**Comment by dontbanmeplz** [comment]
Welp off to use ngrok ig

**Comment by openbullet** [comment]
Yes ngrok should work

**Comment by dontbanmeplz** [comment]
Ok lemi test then ill say solved

**Comment by dontbanmeplz** [comment]
Fixed
