### ISSUE TITLE
[Bug]: Using high amount of banned ip's + 0 Ban Evasion = job lock/freeze

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#401]
### Version of the software

0.1.21

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser

Chrome 91 / Opera 77.0.4054.203

### What happened?

Was testing a custom config which works fine when I have Ban Evasion set to anything other then 0

When I set it to 0, after 30mins - 1 hour it just stops progressing and wont even stop on its own (without being forced)

I have had it stay on Stopping for a few days before I kill it.

I am using proxies with the majority of them being banned/blocked by the website.

If you have anything you want me to try or additional information let me know.

Basic breakdown

Tried attacking a site with a large amount of banned proxies which result in a 400/406 response.
After a short period of time, the OB2 job locks up and stops trying new attempts and is unable to finish the running threads.
When I press stop, it just stays on stopping and wont progress

* large amount of banned proxies - 15 bots = 4 CPM when set to 0 | 50 CPM when not set to 0

**Comment by openbullet** [comment]
So... you're saying that ban loop evasion is doing its job, and is preventing the exact thing for which it was added. Cool ^^
