### ISSUE TITLE
[Bug]: Keycheck throws ERROR when looking for an value in a header key that does not exist

### ISSUE THREAD

**Issue by thisisthelongestusernameyouhaveeverseen** [openbullet/OpenBullet2#404]
### Version of the software

0.1.21

### Operating system

Windows 10

### Browser

Chrome

### What happened?

A bug happened!

Keycheck throws ERROR when looking for an value in a header key that does not exist
it does not check next rule in keycheck, and ruins the block (even if user use try catch)

### Relevant LoliCode if needed

```shell
BLOCK:HttpRequest
  url = "https://example.com"
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK

BLOCK:Keycheck
  banIfNoMatch = False
  KEYCHAIN FAIL OR
    STRINGKEY @data.HEADERS["x-status"] Contains "failed"
  KEYCHAIN SUCCESS OR
    STRINGKEY @data.SOURCE Contains "Example Domain"
ENDBLOCK
```

**Comment by openbullet** [comment]
Easy fix while this is not implemented yet: please add another key like this, so it will fail if the headers don't have a key called x-status and the following line of the keycheck will not be checked since the first one is already true.

```
BLOCK:Keycheck
  banIfNoMatch = False
  KEYCHAIN FAIL OR
    DICTKEY @data.HEADERS DoesNotHaveKey "x-status"
    STRINGKEY @data.HEADERS["x-status"] Contains "failed"
  KEYCHAIN SUCCESS OR
    STRINGKEY @data.SOURCE Contains "Example Domain"
ENDBLOCK
```

**Comment by openbullet** [comment]
Please use the workaround described above, closing the issue
