### ISSUE TITLE
[Bug]: Commenting BLOCKs

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#406]
### Version of the software

0.1.21

### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/41063376/129284267-a259be7d-0aa6-45e3-a144-7464a72d7a84.png)
![image](https://user-images.githubusercontent.com/41063376/129284469-121197a4-8cd3-4f8b-a0e1-5a22f42e6e71.png)

TRY THIS :
```
/*
BLOCK:HttpRequest
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK
*/

BLOCK:ConstantString
LABEL:something to do
  value = "12345"
  => VAR @somethingtodo
ENDBLOCK

```
AND THIS ONE :
```
/*
BLOCK:ConstantString
LABEL:something not to do
  value = "54321"
  => VAR @somethingnottodo
ENDBLOCK
*/

BLOCK:ConstantString
LABEL:something to do
  value = "12345"
  => VAR @somethingtodo
ENDBLOCK

```

**Comment by openbullet** [comment]
You cannot comment blocks, just add a DISABLED keyword inside them (or use Stacker directly). Comments only work on C# code.

**Comment by Cyber-Criminal** [comment]
sad
