### ISSUE TITLE
[Bug]: remove gif background when setup openbullet

### ISSUE THREAD

**Issue by churongcon** [openbullet/OpenBullet2#409]
### Version of the software

Lastest

### Operating system

Linux

### Browser

Chrome

### What happened?

Hello I have used VPS so I can't setup Openbullet 2 because i have poor connection
Can you remove gif background on setup theme

**Comment by openbullet** [comment]
You can connect directly from your own PC's browser, you don't need to use remote desktop as it can lag due to the background.

**Comment by Cyber-Criminal** [comment]
i think it's a better idea to have an option to disable all animations, effects

**Comment by churongcon** [comment]
Please remove all animations effect for smoothly
