### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HenryCross1** [openbullet/OpenBullet2#414]
### Version of the software

1.4.4 ANOMALY /  1.2.2  / 2 

### Operating system

Windows 10

### Browser

Chrome

### What happened?

Hello ,

Deathbycaptcha is not working in openbullet used same info worked in another application how cani fix this?

**Comment by openbullet** [comment]
OB1 (1.2.2) and mods (anomaly 1.4.4) are NOT supported.
As for OB2, we just tried and it works

![immagine](https://user-images.githubusercontent.com/48930622/129640016-67675ddf-f666-4d8a-88e2-236e2b323676.png)

**Comment by HenryCross1** [comment]
https://prnt.sc/1pyfi67
Check this

**Comment by openbullet** [comment]
The only thing I can tell you is to send me the credentials (e.g. via email) and we will try with your credentials. Our account works fine.

**Comment by HenryCross1** [comment]
Can you send me your email please?

**Comment by openbullet** [comment]
You can find it at the bottom of this page https://github.com/openbullet/OpenBullet2

**Comment by HenryCross1** [comment]
Sent
