### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Velka-DEV** [openbullet/OpenBullet2#415]
### Version of the software

0.1.21

### Operating system

Windows 10

### Browser

Edge (Chrome) Last version

### What happened?

Var (Here is: <randomUserAgentOutput>) is not replaced by it's value inside Headers.

(See the attached lolicode)

The request is then sent with `User-Agent: <randomUserAgentOutput>` without any replacement by the variable.

### Relevant LoliCode if needed

```shell
BLOCK:RandomUserAgent
  => VAR @randomUserAgentOutput
ENDBLOCK

BLOCK:HttpRequest
  url = "URL"
  customHeaders = {("User-Agent", "<randomUserAgentOutput>"), ("Pragma", "no-cache"), ("Accept", "*/*"), ("Accept-Language", "en-US,en;q=0.8")}
  TYPE:STANDARD
  $""
  "text/html; charset=UTF-8"
ENDBLOCK
```

**Comment by openbullet** [comment]
This is not a bug, you have to use interpolated mode. In stacker, click on the button next to the field until the background of the textbox turns dark green. In lolicode simply add a $ at the start of the value of the dictionary.
```
BLOCK:RandomUserAgent
  => VAR @randomUserAgentOutput
ENDBLOCK

BLOCK:HttpRequest
  url = "URL"
  customHeaders = ${("User-Agent", "<randomUserAgentOutput>"), ("Pragma", "no-cache"), ("Accept", "*/*"), ("Accept-Language", "en-US,en;q=0.8")}
  TYPE:STANDARD
  $""
  "text/html; charset=UTF-8"
ENDBLOCK
```
