### ISSUE TITLE
[REQUEST] Automaticaly go to the Lolicode's part

### ISSUE THREAD

**Issue by theamericans47** [openbullet/OpenBullet2#418]
When I select a block and then I switch to the Lolicode section, I would like to go automaticaly to the part of the code. It will be much more convenient, especially when you deal with huge config ...

Thanks

**Comment by openbullet** [comment]
OB Settings > On config edit navigate to > LoliCode

**Comment by openbullet** [comment]
Sorry I misread the issue and closed it by mistake 😅

**Comment by openbullet** [comment]
Sorry I don't think I will do this, please give labels to blocks and then simply CTRL+F to find it. Implementing this would take too much time for the small benefit it will give.
