### ISSUE TITLE
[BUG] Cannot use Input Variables directly in Request URL like in old Openbullet

### ISSUE THREAD

**Issue by Testtest455** [openbullet/OpenBullet2#42]
Lets say I have an URL with a GET Request like: https://www.speedtest.net/api/js/result.php?result_id=<input.USERNAME>

(I wanna scan some speedtest results through the Api, so nothing illegal)

Input.USERNAME is the speedtest ID for example: 10190837926

https://www.speedtest.net/api/js/result.php?result_id=10190837926

However, Openbullet V2 is not putting the input from my test data into the request url (That worked in the Old Openbullet)
It sliced my Test Data correctly.

Th log says: 
Address: https://www.speedtest.net/api/js/result.php?result_id=%3Cinput.USERNAME%3E

A post request with the content in the "content" field works.

**Comment by openbullet** [comment]
You have to edit the field from fixed input to interpolated input (click on the blue button until you see `</>` and a green background)
