### ISSUE TITLE
[Bug]: Int keycheck don't accept negative int

### ISSUE THREAD

**Issue by Velka-DEV** [openbullet/OpenBullet2#420]
### Version of the software

Lastest

### Operating system

Windows 10

### Browser

Lastest 

### What happened?

Negative int's are not accepted in int fields (This should not be an unsigned integer)

### Relevant LoliCode if needed

```shell
BLOCK:Keycheck
  banIfNoMatch = False
  KEYCHAIN RETRY OR
    INTKEY @code EqualTo -4
  KEYCHAIN CUSTOM OR
    INTKEY @code NotEqualTo -6
  KEYCHAIN SUCCESS OR
    BOOLKEY @isOK Is True
  KEYCHAIN FAIL OR
    BOOLKEY @isOK Is False
ENDBLOCK
```

**Comment by openbullet** [comment]
Known issue related to how numbers are parsed, I just need to make a small change. Thanks!
