### ISSUE TITLE
[Bug]: Wordlist position is not saved on jobs

### ISSUE THREAD

**Issue by mastercho** [openbullet/OpenBullet2#422]
### Version of the software

0.1.21

### Operating system

Windows 10

### Browser

Chrome  92

### What happened?

When i stop job and try to reload wordlist i can see that position is not saved, i tried to close and reopen OB and still issue exist. Tried to stop job, close it clone and run again and stop and still wont save the position. Did not have it in previous versions.  And no error logs in CMD window

Issue when stop the job https://ruri.please-fuck.me/580URquqs

**Comment by mastercho** [comment]
Fun fact its happens only when running multiple jobs, when running just 1 job its working fine

**Comment by openbullet** [comment]
Please can you see if this issue was fixed in latest version? Thanks

**Comment by mastercho** [comment]
ITs fixed thanks!
