### ISSUE TITLE
[REQUEST] Select all blocks above from a given block

### ISSUE THREAD

**Issue by theamericans47** [openbullet/OpenBullet2#424]
A way to select all blocks below a given block to disable all of them instead of selecting them manually one by one

**Comment by openbullet** [comment]
Please see here
https://github.com/openbullet/OpenBullet2/issues/317

**Comment by openbullet** [comment]
You can use CTRL+click to select multiple blocks, I will add SHIFT+click eventually as well

**Comment by theamericans47** [comment]
Yes, but you have to select one by one.

**Comment by openbullet** [comment]
Yes, I said I would add SHIFT+click didn't I?

**Comment by openbullet** [comment]
Closing since #258 is already open
