### ISSUE TITLE
[REQUEST] Fast comment/uncomment in 'LoliCode Editor'

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#426]
add a button in 'LoliCode Editor' to comment/uncomment selected lines by adding/removing `//` first of each line

**Comment by openbullet** [comment]
Since OB2 web UI uses monaco editor, you can use these shortcuts I think
https://docs.monaca.io/en/products_guide/monaca_ide/editor/
Please close the issue if it worked

**Comment by Cyber-Criminal** [comment]
would you add this in right click menu or as a button?

**Comment by openbullet** [comment]
I'm using a third party component I don't even think I can change it
