### ISSUE TITLE
[REQUEST] Monitor - Trigger "every x minutes"

### ISSUE THREAD

**Issue by theamericans47** [openbullet/OpenBullet2#427]
I would like to reload my proxies every x minutes or x hours, but nothing like this exists in "triggers" (time elapsed = multiple of 5min for example) or I don't see how to do it with "time elapsed" and its logic conditions

**Comment by openbullet** [comment]
There is a checkbox in the job options directly to reload proxies every X seconds, no need to set up a triggered action for this.
