### ISSUE TITLE
[Bug]: [Visual+QOL] Proxy status not updated after check until page refresh

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#429]
### Version of the software

0.1.21

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser

Chrome 91 / Opera 77.0.4054.203

### What happened?

Just a visual bug that should be bottom tier low priority.

After performing a proxy check, the proxy fields are not updated until after the the page is refreshed. 

Everything still works as you can clear the nonworking ones when its like that, its just a visual bug.

**Comment by openbullet** [comment]
This is fixed in the new web client
