### ISSUE TITLE
[REQUEST] adding things missing in OB2

### ISSUE THREAD

**Issue by Thughers** [openbullet/OpenBullet2#430]
Hi I wanted you to add these things that are missing in OB2 web version that are present in OB1

-delete wordlist files not found as the option on OB1
-add checkbox for enable url encode on parse block as OB1

Extra request:
-add snippets to simplify writing code in lolicode

Thanks for everything, have a nice day.

**Comment by openbullet** [comment]
> add snippets to simplify writing code in lolicode

This was already done, just type BLOCK: and a letter and the editor will suggest a few blocks, you can then select which one you want and it will insert a block with the default options you can edit manually in LoliCode.

As for the other two things, I added the button to delete wordlists with a non existant path in the native UI and I will be adding it to the web UI as well soon. The checkbox for URL encoding is coming as well.

**Comment by Thughers** [comment]
> > add snippets to simplify writing code in lolicode
> 
> This was already done, just type BLOCK: and a letter and the editor will suggest a few blocks, you can then select which one you want and it will insert a block with the default options you can edit manually in LoliCode.
> 
> As for the other two things, I added the button to delete wordlists with a non existant path in the native UI and I will be adding it to the web UI as well soon. The checkbox for URL encoding is coming as well.

no, i mean user defined snippets as ATOMIC editor

**Comment by JReming85** [comment]
Just a alternative idea for you @Thughers until your request can be reviewed by Ruri.

There are plenty of clipboard helpers/alternatives that offer this feature.  You can store snippets, replies, etc. and use them anywhere you can rightclick paste.
