### ISSUE TITLE
HELP,0 HITS

### ISSUE THREAD

**Issue by Zamv0** [openbullet/OpenBullet2#431]
### Version of the software

0.1.20

### Operating system

Kali Linux

### Browser

Firefox

### What happened?

hi guys, i'm trying to use different wordlists and proxies, but it always gives me 0 hit and bans almost all bots, any suggestions?

**Comment by openbullet** [comment]
https://discourse.openbullet.dev/t/how-to-debug-ban-error-issues-in-a-job/3055

Please use the forum for these things, it's not a bug of the application it's surely something wrong with what you're doing.
