### ISSUE TITLE
[Bug]: Editing Job when there are similar named configs can cause issue

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#432]
### Version of the software

0.1.21

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser

Chrome 91 / Opera 77.0.4054.203

### What happened?

Not sure whats triggering this but when you have multiple configs with similar names i.e. Site, Site API, etc and your job is set to Site API it will change the config when you goto edit the job to make adjustments to wordlist, proxies, etc.

This has happened a few times to me where the config has been switched to an older config without me changing it.

I also deleted the old config to try and prevent this but the last time I went to change the wordlist it straight up removed the config from the job.

Its not a game breaking bug but more of a nuisance but can cause issue if the user is not paying attention requiring rerunning jobs.

**Comment by openbullet** [comment]
Is this still happening? Are you able to find a way to reliably reproduce the issue?

**Comment by openbullet** [comment]
Closing stale issue
