### ISSUE TITLE
[Bug]: Can't Change Skip value 

### ISSUE THREAD

**Issue by ZEUS-src** [openbullet/OpenBullet2#438]
### Version of the software

0.1.22

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

I Can't change Skip value for Config

**Comment by openbullet** [comment]
There is currently a known issue when editing a job from the "Change" button inside the job viewer page. Please return back to the job manager (click on Jobs in the top menu) and edit with the blue button with the pencil on it. That works until I fix the other one.
