### ISSUE TITLE
[OB2 Native] Icon & updater changes

### ISSUE THREAD

**Issue by nonrect** [openbullet/OpenBullet2#440]
Hey, Some minor improvements if possible

• Make a small change in Native's Icon so we don't mix it up with Web version
• Add a "Check for update" button in home page for quick access
• Button "Delete all proxies" is missing in Native version

With current configuration I currently have 4 OB2 icons on my taskbar with same appearance (It's good for some mind practice though)
- OB2 Native
- OB2 Native Updater
- OB2 Web UI Console
- OB2 Web UI Updater

**Comment by openbullet** [comment]
I can change the icons a little bit to recognize them, yeah.

The "check for updates" is not needed as it already checks for updates by itself once a day as you can see here https://github.com/openbullet/OpenBullet2/blob/master/OpenBullet2.Native/Services/UpdateService.cs#L45

The "delete all proxies" can easily be done with CTRL+A and Delete so I'm not sure if this is a vital thing to have 😅

**Comment by Thanosbin00** [comment]
I recommend you to use openbullet2 web-based its much better and faster. there some problems but its still working fine!

**Comment by openbullet** [comment]
> 
> 
> I recommend you to use openbullet2 web-based its much better and faster. there some problems but its still working fine!

Let people use whatever they want
