### ISSUE TITLE
[REQUEST] Save 'sort by' preference of config list

### ISSUE THREAD

**Issue by omimic12** [openbullet/OpenBullet2#442]
**Problem:**

Previously in OB1, if you sorted the config list by e.g. Last Modified, so the most recent edited config is positioned at the top, this preference was saved every time you returned to the config panel. Currently, it is reset every time you returned to the panel and would have to keep sorting by Last Modified, Name, Author etc.

**Solution:*
Save the preference of sorting.

**Comment by openbullet** [comment]
I tried and it's saved correctly in the Configs section, maybe you mean the "select config" dialog that opens?

**Comment by omimic12** [comment]
Yeah, that section sorry. Whenever that dialog pops up, it's reset.
