### ISSUE TITLE
Improve Stacker

### ISSUE THREAD

**Issue by OpenBullet-Checker** [openbullet/OpenBullet2#443]
Hello, Openbullet 2 is Very complicated. I have try to create an config in OpenBullet2 but it so complicated. Such as input data in OpenBullet 1 is <USER> but the OpenBullet2 is <input.USER>. Or SOURCE in OB1 is <SOURCE> but in OB2 is data.SOURCE. Can you make it simpler?

**Comment by openbullet** [comment]
Sorry this is just not going to happen, OB1 used a completely different system while OB2 compiles to C# directly so these changes are needed to make it work properly. You get more speed in return, so I guess you can make a little sacrifice? 😅
