### ISSUE TITLE
security issue and ram problem

### ISSUE THREAD

**Issue by meisuj815** [openbullet/OpenBullet2#449]
ref: https://discourse.openbullet.dev/t/function-request-and-others-questions/4259

security issue1: allow root user to disable guest save wordlist file and hit on server, just save in ram cache

security issue2: disable guest allow to read the system file in combo check list

ram issue1: just four running job, then 4G ram used..

https://img.onl/ot1nDG
https://img.onl/dacBPc

My OB2 website:
vipsperks.com

can I donate and show my username or website in Donators and Supporters? 
thank alot!

**Comment by openbullet** [comment]
It would be really good to have 1 separate issue for each problem, so I can track them better.
As for the ram usage, please can you take a memdump of the process and send it to me so I can take a look at what's using all the RAM? Thanks!

**Comment by meisuj815** [comment]
@openbullet 
Hi, thanks for reply. Okay let me close this issue first and separate them.
