### ISSUE TITLE
[BUG] RSA PKCS1PAD2

### ISSUE THREAD

**Issue by Tsunade1337** [openbullet/OpenBullet2#45]
Ruri u told me to open an issue here on github, so here I am
Apparently u can't input.PASSWORD directly to a block that takes byte array.

**Comment by openbullet** [comment]
Ah now I remember why I couldn't do this. I cannot cast variables directly from an expando object.
https://github.com/openbullet/OpenBullet2/blob/245683ffdf55e9a3641fee8de4eba2bc5b53b1bd/RuriLib/Helpers/CSharp/CSharpWriter.cs#L137-L139
So you have to use an intermediate variable without passing it directly, sorry.
