### ISSUE TITLE
geetest type captcha problem

### ISSUE THREAD

**Issue by JehadBasharFatooh** [openbullet/OpenBullet2#451]
### Version of the software

openbullet2

### Operating system

windows 10

### Browser / Native

chrome 10

### What happened?

I face this problem when solving a geetest captcha, although 2caprcha offers a solution for this type, how can this issue be resolved.
The error message is as follows: [Executing block Solve Gee Test Captcha] TaskSolutionException: Exception of type ‘CaptchaSharp.Exceptions.TaskSolutionException’ was thrown.
![Screenshot_111](https://user-images.githubusercontent.com/86165496/132944842-48d5a8b9-7b18-4c37-88f2-64f6684ecbc1.png)

**Comment by meinname** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/16181408/132947645-086087e1-304e-4702-9956-0ac71ddefb7d.png)

Maybe the data for GT and Challenge are outdated? If i remember right these are valid only for 1 use and a short timeframe.

**Comment by JehadBasharFatooh** [comment]
> يعمل لدي:
> ![صورة](https://user-images.githubusercontent.com/16181408/132947645-086087e1-304e-4702-9956-0ac71ddefb7d.png)
> 
> ربما تكون بيانات GT و Challenge قديمة؟ إذا كنت أتذكر حقًا ، فهذه صالحة للاستخدام مرة واحدة فقط ولإطار زمني قصير.

I want to communicate with you 5 minutes do you have a telegram

**Comment by JehadBasharFatooh** [comment]
> Works for me:
> ![image](https://user-images.githubusercontent.com/16181408/132947645-086087e1-304e-4702-9956-0ac71ddefb7d.png)
> 
> Maybe the data for GT and Challenge are outdated? If i remember right these are valid only for 1 use and a short timeframe.

![image](https://user-images.githubusercontent.com/86165496/132951125-05ff1caf-ea9a-4b7c-ae7d-c646536304d5.png)
How are the variables written directly in the post data that appears in the image?

**Comment by openbullet** [comment]
It will create a variable called (in this case) solveGeeTestCaptchaOutput with the 3 values serialized as json, so you have to parse them manually. This is due to a limitation in OB2 where blocks cannot return more than 1 value. Anyways marking this as solved since there is no issue with GeeTest.

**Comment by JehadBasharFatooh** [comment]
> It will create a variable called (in this case) solveGeeTestCaptchaOutput with the 3 values serialized as json, so you have to parse them manually. This is due to a limitation in OB2 where blocks cannot return more than 1 value. Anyways marking this as solved since there is no issue with GeeTest.

Is it possible to form a script to make each variable separately?

**Comment by openbullet** [comment]
As I said you have to use the PARSE block 3 times and parse each one of them to a separate variable.

**Comment by JehadBasharFatooh** [comment]
> As I said you have to use the PARSE block 3 times and parse each one of them to a separate variable.

ok thank you
