### ISSUE TITLE
[REQUEST] Disable guest permission of reading the system file in combo check list

### ISSUE THREAD

**Issue by meisuj815** [openbullet/OpenBullet2#453]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when guest allow to read the system file in wordlist select, that is a very important security issue.

**Describe the solution you'd like**
Guest only allow to upload/use their own wordlist without permission read the system file directly.

**Comment by bestisben-xyz** [comment]
Hi
@openbullet 
My main account @meisuj815 is disabled, I will using this account for now
Please fix this security as soon as possible, leaked so many data.

https://img.onl/Qe6Vm
https://img.onl/KXGalE
