### ISSUE TITLE
[REQUEST] GUEST VARIABLE ACCESS

### ISSUE THREAD

**Issue by OBK-OPENBULLET** [openbullet/OpenBullet2#46]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Having accces to GUEST global variable (USERNAME, IPS, EXPIRATION ACCESS API TOKEN...)

**Describe alternatives you've considered**
No alternatives.

**Additional context**
https://prnt.sc/10i4l5n <- Talking about this guest variable

**Comment by openbullet** [comment]
Closed due to no response from the user.
