### ISSUE TITLE
[REQUEST] Updater added functionality

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#460]
Running the updater while having the latest version will result in the following:
`[3/6] Comparing versions... Already up to date!`
And the updater will remain open until manually closed.
My request is to add an auto-close countdown to the updater if it's already up to date.

Running the updater while having a lower version will result in the updater requesting to manually restart the OB2 instance.
My request is to add an option to auto-restart the OB2 instance (and will close the updater along with it).
This setting could be changed in the .json file.

Running the updater while OB2 is running could cause issues with the update, therefor I would request to add the updater the option to auto-close the OB2 instance in order to avoid issues.

**Comment by openbullet** [comment]
Are you talking about OB2 web or native here? Because on web this is not feasible, and on native it's already implemented.

**Comment by ObsessedHacker** [comment]
> Are you talking about OB2 web or native here?

Uh, sorry, my bad, I was talking about OB2 Native.

> on native it's already implemented.

The updater does NOT close when already up to date

**Comment by openbullet** [comment]
You should not click on the updater by itself, when an update is available there will be a button in the Home tab of OB2. By clicking the button, it will automatically
1. Close OB2
2. Start the updater
3. Finish and close the updater
4. Restart OB2

All by itself. So don't click on the updater manually! I do not intend to change this.
