### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by JehadBasharFatooh** [openbullet/OpenBullet2#461]
### Version of the software

openbullet2

### Operating system

windows 10

### Browser / Native

chrome 10

### What happened?

Problem when requesting a request post and the content type is :application/json

{"statusCode":400,"message":"Unexpected end of JSON input","error":"Bad Request"}

**Comment by openbullet** [comment]
I have no idea what you're sending the website, you didn't provide enough info how am I supposed to debug this?

**Comment by JehadBasharFatooh** [comment]
> I have no idea what you're sending the website, you didn't provide enough info how am I supposed to debug this?

I want to send you the config. It contains a captcha. Where can I send it to you with a key solver to do the experiment?

**Comment by JehadBasharFatooh** [comment]
> I have no idea what you're sending the website, you didn't provide enough info how am I supposed to debug this?

Is there a place I can send it to you privately that won't bother you at all?

**Comment by openbullet** [comment]
Sorry I don't provide personal help and this doesn't seem like an OB2 issue, it seems like your json is invalid so I'm going to go ahead and close the issue.
