### ISSUE TITLE
[Bug]: "Create Multi Jop" Window is bigger than my screen !

### ISSUE THREAD

**Issue by ZEUS-src** [openbullet/OpenBullet2#462]
### Version of the software

0.1.23

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

this happens when i choose Config and Wordlist 
Accept botton become under the TaskBar
![Untitled](https://user-images.githubusercontent.com/83480310/133018117-b5d3ad52-0365-415a-ba8f-c5741ea13a19.png)

**Comment by nero-0** [comment]
Same thing happens on my screen... making it resizable seems a good idea.
