### ISSUE TITLE
Buttons For Input :)

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#464]
Rurri can you add buttons for input? This should take you about 15 minutes to implement as you're a guru coder...

**Comment by Cyogenus** [comment]
![image](https://user-images.githubusercontent.com/80471318/133419458-b43f98a4-61ed-48e8-a0e5-47cabe33e150.png)

**Comment by openbullet** [comment]
There are issues that have been open for months and they're not complaining 😛

**Comment by Cyogenus** [comment]
Rurri I just had to tease you lol 😆

**Comment by openbullet** [comment]
Done, it's enough to write values separated by a comma in the "default answer" textbox and they will appear as options that the user can select. The user can also write his own of course.
