### ISSUE TITLE
[Bug]: Unhandled exception

### ISSUE THREAD

**Issue by anotheralias** [openbullet/OpenBullet2#465]
### Version of the software

0.1.22 beta

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

When I start running it always appears these alarms

Unhandled exception thrown on 14/09/2021 09:37:32
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Este anfitrião não é conhecido.)
 ---> System.Net.Sockets.SocketException (11001): Este anfitrião não é conhecido.
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
![Sem Título](https://user-images.githubusercontent.com/79483195/133234845-d8035f54-8096-451f-92c9-8e8d7cb68962.png)

**Comment by openbullet** [comment]
This bug was fixed in 0.1.23 please update.
