### ISSUE TITLE
[REQUEST] show dns

### ISSUE THREAD

**Issue by anotheralias** [openbullet/OpenBullet2#466]
hello
there are more important things but I think it contributes to a better UI Native add the (Host:DNS) for universal configuration similar to the browser version

**Comment by openbullet** [comment]
I don't think I understand what you mean, can you send a screenshot?

**Comment by anotheralias** [comment]
![Sem Título](https://user-images.githubusercontent.com/79483195/133265812-4abce6bd-fd79-4305-8631-6a21abf3857f.png)

**Comment by anotheralias** [comment]
![Sem Título](https://user-images.githubusercontent.com/79483195/133265901-b2543b6e-fc38-4593-85a6-378ff476f27a.png)
