### ISSUE TITLE
[REQUEST] Show custom input values in MultiRunJobViewer

### ISSUE THREAD

**Issue by anotheralias** [openbullet/OpenBullet2#468]
hello
there are more important things, but I think it contributes to a better UI Native add the (Host:DNS) for universal config ,
similar to the browser version

![Sem Título](https://user-images.githubusercontent.com/79483195/133268025-4dadad32-5c73-4184-a7a0-f40e2a4fae33.png)

sorry repeat the post but the other are closed

**Comment by Cyogenus** [comment]
When you use inputs does your host show blank also ???
