### ISSUE TITLE
Question Regarding the source.

### ISSUE THREAD

**Issue by JReverse** [openbullet/OpenBullet2#470]
What editor are using to preview razor while editing I'm trying to contribute but Visual-Studio 2022 Preview makes me force compile to view page

**Comment by openbullet** [comment]
There is currently no hot reload in blazor, you have to compile every time. I think hot reload was planned for vs 2022 but maybe they didn't ship it yet in the preview 😅

**Comment by openbullet** [comment]
I think it will only be supported for webasm blazor though
https://stackoverflow.com/questions/58172922/is-there-any-hot-reload-for-blazor-server-side
