### ISSUE TITLE
[Bug]: Importing 30k Proxy List. Causes Error

### ISSUE THREAD

**Issue by JReverse** [openbullet/OpenBullet2#472]
### Version of the software

0.1.24

### Operating system

Windows 10

### Browser / Native

Chrome 93

### What happened?

Cannot read properties of null (reading '_blazorFilesById') TypeError: Cannot read properties of null (reading '_blazorFilesById') at a (https://snip.snip.com/_framework/blazor.server.js:8:84767) at s (https://snip.snip.com/_framework/blazor.server.js:8:84907) at Object. (https://snip.snip.com/_framework/blazor.server.js:8:86846) at https://snip.snip.com/_framework/blazor.server.js:8:84566 at Object.next (https://snip.snip.com/_framework/blazor.server.js:8:84671) at https://snip.snip.com/_framework/blazor.server.js:8:83583 at new Promise () at r (https://snip.snip.com/_framework/blazor.server.js:8:83328) at Object.readFileData (https://snip.snip.com/_framework/blazor.server.js:8:86748) at https://snip.snip.com/_framework/blazor.server.js:1:70055

**Comment by openbullet** [comment]
Note for self: read this https://stackoverflow.com/questions/65973850/cannot-read-property-blazorfilesbyid-of-null-error-with-blazor-inputfile-co

**Comment by openbullet** [comment]
I am trying but cannot reproduce the issue :/

**Comment by JReverse** [comment]
@openbullet your server is on ubuntu 20.04 right?

**Comment by openbullet** [comment]
I'm using it on Chrome + Windows but I don't think this is platform specific since it runs in a browser. Are you using Firefox maybe?

**Comment by JReverse** [comment]
@openbullet i use chrome i just tried windows it works on ubuntu it dosent hmm

**Comment by openbullet** [comment]
Could you be so kind to try firefox on windows please? Cause maybe it's browser-specific. Thanks!

**Comment by JReverse** [comment]
JSException
e is null a@https://*.*.to/_framework/blazor.server.js:8:84765 s@https://*.*.to/_framework/blazor.server.js:8:84908 readFileData/


Heres more information btw:

OpenBullet2 is running on ubuntu 20.04 dotnet 5
Browsers tried both chrome / firefox on windows 10

**Comment by meinname** [comment]
Tested on Ubuntu 20.04 on Server and Window with chrome in an other VM.
Importing over 34k proxies from file worked and also pasting these worked

**Comment by JReverse** [comment]
[A.txt](https://github.com/openbullet/OpenBullet2/files/7193005/A.txt)

Dosen't for me

**Comment by meinname** [comment]
imported your File:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/16181408/133945801-cd19af10-bab5-4180-853d-b4f0d7ea4b6d.png">

**Comment by rockyd3vil** [comment]
if I used it remotely then it pops unless if it is local admin then it is not pops.
due to unable to found the path it seems
(IP:5000/__framework/blazor.server.js:8:84767)
(IP:5000/_framework/blazor.server.js:8:84907) at Object. (IP:5000/_framework/blazor.server.js:8:86846) at IP:5000/_framework/blazor.server.js:8:84566 at Object.next (IP:5000/_framework/blazor.server.js:8:84671) at IP:5000/_framework/blazor.server.js:8:83583 at new Promise () at r (IP:5000/_framework/blazor.server.js:8:83328) at Object.readFileData (IP:5000/_framework/blazor.server.js:8:86748) at IP:5000/_framework/blazor.server.js:1:70368

**Comment by JReverse** [comment]
Yes, I'm using Remote to @meinname  @openbullet

**Comment by openbullet** [comment]
@rockyd3vil are you also using a Linux VPS or something like that?

**Comment by rockyd3vil** [comment]
> @rockyd3vil are you also using a Linux VPS or something like that?

yes windows VPS.
