### ISSUE TITLE
[REQUEST] Improve OB2

### ISSUE THREAD

**Issue by Pro-Checker** [openbullet/OpenBullet2#480]
Hello, Openbullet 2 is Very complicated. I have try to create an config in OpenBullet2 but it so complicated. Such as input data in OpenBullet 1 is <USER> but the OpenBullet2 is <input.USER>. Or SOURCE in OB1 is <SOURCE> but in OB2 is data.SOURCE. Can you make it look like OpenBullet 1?

**Comment by OpenBullet-Checker** [comment]
> Xin chào, Openbullet 2 rất phức tạp. Tôi đã cố gắng tạo ra một cấu hình trong OpenBullet2 nhưng nó rất phức tạp. Chẳng hạn như dữ liệu đầu vào trong OpenBullet 1 là nhưng OpenBullet2 là <input. Người dùng>. Hoặc NGUỒN trong OB1 là nhưng trong OB2 là dữ liệu. NGUỒN. Bạn có thể làm cho nó trông giống như OpenBullet 1?

I hope Ruri will do it. My group members said they will continue using SilverBullet because Make Config in OpenBullet2 is difficult

**Comment by openbullet** [comment]
Absolutely not going to do this.
But support for old config formats is coming, and also a video tutorial on how to use OB2.

**Comment by fairysubsteam** [comment]
If you guys are dumb enough not to understand a mere documentation, I suggest you stop using OB as a whole. The features added to OB2 are worth the upgrade. And it ain't that hard to learn.
