### ISSUE TITLE
Custom input combo box clicking fix

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#484]
Sup Ruri this is a easy fix for you ;) In the custom input combo box it has a issue it's hard to click on the items to choose from the combo box just one click should make the item be chosen. Currently you have to click an item multiple times for it to work.

**Comment by tcortega** [comment]
@Cyogenus It is one click, can't reproduce your issue

**Comment by Cyogenus** [comment]
Yes it works fine on the native ob2 but try it on the web versions

**Comment by Cyogenus** [comment]
> @Cyogenus It is one click, can't reproduce your issue

It's not working right for me are you using web client ??? Because it works correctly on the openbullet 2 native but has issues on the web version of openbullet 2

**Comment by Cyogenus** [comment]
![image](https://user-images.githubusercontent.com/80471318/135369128-f65b6ae0-7abe-4f0c-a8cd-99e6c15c1ddc.jpeg)

**Comment by tcortega** [comment]
I tried investigating the issue myself, and what is happening is, sometimes
when you click in the div of the answer you want to select, blazor is not
always firing the onclick event. Couldn’t figure out why, proposed to Ruri
a few changes to make it work but in a different way, but he said there is
no need and he will investigate when he has more time. Just be patient.

**Comment by Cyogenus** [comment]
> I tried investigating the issue myself, and what is happening is, sometimes when you click in the div of the answer you want to select, blazor is not always firing the onclick event. Couldn’t figure out why, proposed to Ruri a few changes to make it work but in a different way, but he said there is no need and he will investigate when he has more time. Just be patient.

Thanks bro 😎

**Comment by Cyogenus** [comment]
![image](https://user-images.githubusercontent.com/80471318/137581085-4a2f0d8c-4b64-4e8b-b129-d4b62c8fe344.gif)

**Comment by openbullet** [comment]
This issue will continue in #579 since it is more complete and descriptive
