### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ufoevangel** [openbullet/OpenBullet2#497]
### Version of the software

0.1.25

### Operating system

win 10

### Browser / Native

firefox

### What happened?

hi
in selenium,when using WaitForElement block,if it get timeout,the bot get end with Error Result and it will not continue the next blocks like ob1.2.2
fix if possible
thanks

**Comment by openbullet** [comment]
1. OB2 has puppeteer not selenium
2. Click on the SAFE checkbox at the top of the block and it will not throw an error even if it fails
