### ISSUE TITLE
[REQUEST] Creating a list of sequential numbers 1 to N (Ex: [1, 2, 3, …, 98, 99, 100])

### ISSUE THREAD

**Issue by JustDaixD** [openbullet/OpenBullet2#498]
Hello sir, I want to create a list in which there is an array of sequential numbers.

Example:-

`n = 9`

Then

`list = [1,2,3,4,5,6,7,8,9]`

As you @Ruri have suggested in the official forum that the solution to be

`List<string> theNumbersMason = Enumerable.Range(1, 9).Select(i => i.ToString()).ToList();`

I want you to create a separate Block for all of those who need it, this will be useful in searching some text in search engines, and we get a lot of pages like gives below.

![image](https://user-images.githubusercontent.com/91605441/135259713-7e15b8c5-63ef-44e2-9324-f19af961bc3a.png)

We can parse the maximum number of pages, generate a sequel number of lists, and Then create a loop of Requests to parse all of the requests. 🙂

And I think we can use it in many other ways too, so kindly, sir consider sparing some time for this block.

**Comment by JReming85** [comment]
Instead of having a set amount of numbers why not just take advantage of the pagination and just click "Next" until it is no visible or until the html/numbers do not change anymore.

That way no matter how many pages it will also hit them all?

**Comment by openbullet** [comment]
Or, since you know the amount of total pages, you can do a for loop in C#
But I told him I would add this as a block since it might be useful for other purposes, so I will add it

**Comment by JustDaixD** [comment]
> Instead of having a set amount of numbers why not just take advantage of the pagination and just click "Next" until it is no visible or until the html/numbers do not change anymore.
> 
> That way no matter how many pages it will also hit them all and it could all be done via a while loop.

Yes sir I have thought of that way before and also tried to implement it, but haven't found an exact way to do so. Anyways This Block can also be useful for various purposes for many people so I have posted the suggestion.

**Comment by JReming85** [comment]
It would be different depending on if you were using puppeteer or rurilib but its essentially the same

Start a loop
check if element exists (next button) either using the puppeteer block or a parse block
if visible then scrape and click next
if not end/break loop
