### ISSUE TITLE
Http Proxy not work, Failed SSL connect[Bug]: 

### ISSUE THREAD

**Issue by ZEUS-src** [openbullet/OpenBullet2#501]
### Version of the software

0.1.25

### Operating system

Win10

### Browser / Native

Browser & Native

### What happened?

for reason i don't know no HTTP Proxy are work with OB2[ Browser & Native ], i tested proxy from STORMPROXY and PROXYSCRAPE and buth are not working, when i try to use it in debugger i get this error
![Failed_SSL_connect](https://user-images.githubusercontent.com/83480310/135996994-d6c40409-23a2-4831-8bdc-1b93e8c3f102.png)
Proxy are working fine in OB1 !

**Comment by openbullet** [comment]
There was a PR that messed this up, the fix is already up on the repo but you will have to compile yourself if you want to use it, otherwise just fallback to 0.1.24 until I drop the new release which will include the fix.
