### ISSUE TITLE
Unhandled exception thrown on[Proxy issue]

### ISSUE THREAD

**Issue by paul745** [openbullet/OpenBullet2#504]
Version of the software
0.1.25 [Beta] Native

Operating system
Windows 10 x64 build 19042.1110

Browser / Native
Opera

What happened?
Proxy bug
Unhandled exception thrown on
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.)
 ---> System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at OpenBullet2.Native.ViewModels.ProxiesViewModel.RefreshList()
   --- End of inner exception stack trace ---

Screenshoot:
![2021-10-08_133929](https://user-images.githubusercontent.com/38107289/136543863-e3493334-8b8f-4490-8d16-a0044c358573.jpg)

**Comment by openbullet** [comment]
This should be fixed in the next version as task exceptions are now being ignored

https://github.com/openbullet/OpenBullet2/commit/30d2b526b9559ccd2fcfaa00f8f367608c6431e7

**Comment by openbullet** [comment]
If you're actually having problems deleting proxies from the DB (and it's not just an annoying error) then I need a way to reproduce this as I could not figure out how to make the bug happen in my client. Please reopen and post some more information, thank you!
