### ISSUE TITLE
[REQUEST] DUPLICATE CONFIG OPTION

### ISSUE THREAD

**Issue by OBK-OPENBULLET** [openbullet/OpenBullet2#51]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Option to duplicate a config in the config section

**Describe alternatives you've considered**
It's borring to copy c# config content and create a new config to "dupe" a config

**Additional context**

**Comment by openbullet** [comment]
Workaround: click on the Download button to download a .opk file, then change its name and reupoad it. There you go, config cloned.

**Comment by Generation88** [comment]
Yes we would love a config clone option

**Comment by Generation88** [comment]
Thanku so much for this feature...More bugs reports & requests coming soon

**Comment by openbullet** [comment]
> 
> 
> Thanku so much for this feature...More bugs reports & requests coming soon

Now you're scaring me 👀
