### ISSUE TITLE
[Bug]: Unix time Block Function does not accepte <variable name> !

### ISSUE THREAD

**Issue by aymenmerabta124** [openbullet/OpenBullet2#511]
### Version of the software

0.26

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

A bug happened!
Last time i create a config but when I parse a unix time variable to translate it to date I found that the unix date function block does not accepte the </> feature so fix that please as soon as possible its important.
king of regards 
Aymen

**Comment by openbullet** [comment]
It accepts an integer, you can just use the VAR mode and put the name of your parsed timestamp (just the name of the variable without `<these>`) and it will automatically cast from string to int.
