### ISSUE TITLE
[Bug]: PKCS2PAD1 is wrong

### ISSUE THREAD

**Issue by openbullet** [openbullet/OpenBullet2#517]
### Version of the software

0.1.26

### Operating system

Any

### Browser / Native

Any

### What happened?

The `RSAPkcs1Pad2` function needs to take byte arrays in two's complement with little endian, since a BigInteger is parsed like that as can be seen in the official source code

https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System.Numerics/System/Numerics/BigNumber.cs#L368

The method can be fixed like this (for future reference) but since these values are usually sent by a server in plaintext I will probably go back to the old OB1 signature of this method (which takes 3 strings instead of 3 byte arrays).

```cs
public static byte[] RSAPkcs1Pad2(byte[] message, byte[] modulus, byte[] exponent)
{
    var reversedModulus = modulus.Reverse().ToArray();
    var signedModulus = new byte[modulus.Length + 1];
    signedModulus[modulus.Length] = 0x00;
    Array.Copy(reversedModulus, 0, signedModulus, 0, modulus.Length);

    var reversedExponent = exponent.Reverse().ToArray();
    var signedExponent = new byte[exponent.Length + 1];
    signedExponent[exponent.Length] = 0x00;
    Array.Copy(reversedExponent, 0, signedExponent, 0, exponent.Length);

    // Convert the public key components to numbers
    var n = new BigInteger(signedModulus);
    var e = new BigInteger(signedExponent);

    // (modulus.ToByteArray().Length - 1) * 8
    // modulus has 256 bits multiplied by 8 bits equals 2048
    var encryptedNumber = Pkcs1Pad2(message, (2048 + 7) >> 3);

    // And now, the RSA encryption
    encryptedNumber = BigInteger.ModPow(encryptedNumber, e, n);

    //Reverse number
    return encryptedNumber.ToByteArray().Reverse().ToArray();
}
```

### Relevant LoliCode if needed

```shell
BLOCK:ConstantString
LABEL:password
  value = "kepalsapi"
  => VAR @password
ENDBLOCK

BLOCK:ConstantString
LABEL:exp
  value = "010001"
  => VAR @exp
ENDBLOCK

BLOCK:ConstantString
LABEL:mod
  value = "b2e57ad93d6f2e3e856d30749f615c6be8987103db510e6cfd372c5bb228fb81205c27bbf63ff4d6a0963c40b93cd5d47781a0b817ec8698989de049148079e732aae3281b7b58cdb89412b91df6f3907f1ecc10bfa88f9d92554c3456ffcd082a0a1e1509611d71a160ac8d06490197fb444057303064586c399a367f4c49ca77e832e7d38b5149f73fd9300d8c59a23432a531f56c957f7cd3a68c3af3d90eda6b08208cc24ec67399f660db322f439eedd47e7cb74f50dc86754d971029658a5619985492f1acd8e758644c211afe993c62c9ea67398f574c9871f2bffe550abd78f897aa915f4db347e49422729e4c3ec11454bf4f91d61ed655acae23f1"
  => VAR @mod
ENDBLOCK

BLOCK:HexStringToByteArray
LABEL:exp (bytes)
  hexString = @exp
  => VAR @expBytes
ENDBLOCK

BLOCK:HexStringToByteArray
LABEL:mod (bytes)
  hexString = @mod
  => VAR @modBytes
ENDBLOCK

BLOCK:RSAPkcs1Pad2
LABEL:RSA (bytes)
  plainText = @password
  modulus = @modBytes
  exponent = @expBytes
  => VAR @rsa
ENDBLOCK

BLOCK:ByteArrayToBase64String
LABEL:RSA (b64)
  bytes = @rsa
  => VAR @rsaBase64
ENDBLOCK
```

**Comment by openbullet** [comment]
Yes it's been solved, make sure you're on the latest version, redownload if needed. If you don't get the same result, please post some sample LoliScript for OB1 and LoliCode for OB2.

**Comment by beyto0o** [comment]
OB1
`
FUNCTION RSAPKCS1PAD2 "b9600fbf627333dfcadc098dea8f299608964691d033fe155e71c9478c07ab182e82f1d39c868d4b71a0bd0c870d61eeec3d9aa488d234fc8b25f884212123265a0a8860643dc8b8a3ac20809ae886afa79f8f94e9695bc121638ba338a541d43978f292ec10b5aa298e8a7105192b86b9b4a0684f4df343636b84f5597d8d795813a0d76fb7f2317fb78c123b5b04307dee72b7f56961c92b421aa4a432085b9b4dc02dc63c6587a354e5d2d718bc5be55275aba56f44619059b7a488a013dc94c4ce7b4d6373faf9a1a27a71c1b74ef400513ef300a6834a72403afff3d9c2c9b095f455879486270edf6d235bcc4ddc82db80c0c0e7d4f9d1ba4df5af5585" "010001" "Bosko1403" -> CAP "RSA" 

Result
T1hgVMT6D4Yz9+T6qoNzt6bJfPwxbDpjt5vc9Eqp0ukfJJLOeUUCB1hzTFmGUnPCOoLlTjmCdEnWh+n2EdyO5Js8ByWdwpsn2jcONGThyI7K5N4ipxt2add57ZitaAA8WuNguLaU3OT8zdyIdcxylzqeGPg+xLxgqnyv45gwmoJj53VVsvXywWoqwHci6aGki+Leu1j4uC3R5VR3WExfV9yNoyoOnfrfNBtvl4vK9wIFqLNqaG0XB8O2DN77AVsd7zlmFp8kN/Aj7X9VJsQBiJQ1aiZ7qHcja8PMvAX+yqfSl9c3ZF6KvFt+AcqlVPb5VLQqy4ApLArTap+67sUF+w==
`

OB2 v 0.23 (I downloaded it again)
`
BLOCK:RSAPkcs1Pad2
  plainText = "Bosko1403"
  hexModulus = "b9600fbf627333dfcadc098dea8f299608964691d033fe155e71c9478c07ab182e82f1d39c868d4b71a0bd0c870d61eeec3d9aa488d234fc8b25f884212123265a0a8860643dc8b8a3ac20809ae886afa79f8f94e9695bc121638ba338a541d43978f292ec10b5aa298e8a7105192b86b9b4a0684f4df343636b84f5597d8d795813a0d76fb7f2317fb78c123b5b04307dee72b7f56961c92b421aa4a432085b9b4dc02dc63c6587a354e5d2d718bc5be55275aba56f44619059b7a488a013dc94c4ce7b4d6373faf9a1a27a71c1b74ef400513ef300a6834a72403afff3d9c2c9b095f455879486270edf6d235bcc4ddc82db80c0c0e7d4f9d1ba4df5af5585"
  hexExponent = "010001"
  => CAP @RSA
ENDBLOCK

Result
00a1a95c8cc0254b9deb11a35ce19b3d02f075efb70e23acb0dd952dae1985fa5dabaa0c5cb0f00bc1717bcb63a6560d0e2593b0b2c437a8846346c2bf190ef1b23dcc5fd536c54d8836ec42cbcf20bc4552665681f24e38714f52d41b8f357d7dd80406bb5552aa27d061ee2b3d8dbcdec27e1f597981842fa3ecdeddbb905f77f235ee9bc03a9be5ea4feaeee44189aa3b50a99d2571b075a77e60c6fcec5544d82c8f5852176c62fc1524c1e3fddae5ee99fb9c43381f6b5d32256c014491f766d64c808fd5eff094e81c0ffa8b31875ce44c9fee2e31cf746a37b9db564d3e4bc7b87305a3ae8776c02dd10a2a430a713a8dd19477b7f4d1ee544bb94bcc52
`
