### ISSUE TITLE
[REQUEST] Read response source toggle in request block

### ISSUE THREAD

**Issue by beer15** [openbullet/OpenBullet2#52]
Hi ruri, first of all thank you for the work you do,

Here are some functions that were really useful in OB1 that I don't see in OB2 and I think it's a good thing to put them in version 2, here is the list.

- Read Resp. Source toggle, request block
- search in the debugger
- HTML View not always available, a bug ? 
- Put the proxy API function of ob1, so we don't need to enter it anymore, the link to update the proxies at each launch is done automatically, it's a really practical option that saves a lot of time
- I also noticed one thing, sometimes in OB2 when I make a request I get the error "Operation cancelled
BOT ENDED AFTER 15120 ms WITH STATUS: ERROR"

while in OB1 I have the same block no problem, a bug or the problem comes from me? 

thanks 

OB2 Version 0.1.1

**Comment by openbullet** [comment]
Search in debugger = just use CTRL + F from browser
HTML View is available at the end of every source after a request block, it's intended like this
For proxies see #25 
Operation cancelled is because you set the `Content-Length` header manually, just remove it and it will work

**Comment by beer15** [comment]
> Search in debugger = just use CTRL + F from browser
> HTML View is available at the end of every source (with more than 1 line) after a request block, it's intended like this
> For proxies see #25
> Operation cancelled is because you set the `Content-Length` header manually, just remove it and it will work

ok thanks i can put some suggestions here ? or i have to make another issue

**Comment by openbullet** [comment]
Please open 1 issue for each thing otherwise it's a mess. We will keep this open to impement the "read response source" checkbox, although I would still like to know the purpose of having that when you can just send a HEAD instead of a GET.

**Comment by openbullet** [comment]
Please let me know why this setting needs to be implemented. I assume it's for when a website sends a massive source, but it can be prevented in 2 ways.
If it's a GET request, just send a HEAD request instead so the server will only send headers and not the source.
Otherwise you can use this snippet, which only disables the log for that specific block (all the variables are set regardless, only the log is not printed)
```csharp
data.Logger.Enabled = false;
// Your HTTP request block here
data.Logger.Enabled = true;
```
Please let me know if this setting is essential, and why the 2 alternatives I proposed won't work. Thank you ^_^

**Comment by fairysubsteam** [comment]
Since we can get off with a mere disabling the logger function, I guess there's no need for the implementation of Read Source.
