### ISSUE TITLE
[REQUEST] Wordlist check method 

### ISSUE THREAD

**Issue by ZEUS-src** [openbullet/OpenBullet2#521]
i don’t know how to explane this but i want to check the Wordlist not like this

LEFT1:RIGHT1
LEFT2:RIGHT2
LEFT3:RIGHT3
LEFT4:RIGHT4
LEFT5:RIGHT5

but like this

LEFT1:RIGHT1
LEFT1:RIGHT2
LEFT1:RIGHT3
LEFT1:RIGHT4
LEFT1:RIGHT5
LEFT2:RIGHT1
LEFT2:RIGHT2
LEFT2:RIGHT3
LEFT2:RIGHT4
LEFT2:RIGHT5

**Comment by openbullet** [comment]
Create a new Wordlist with an external tool and then import that one
