### ISSUE TITLE
[Bug]: cannot automatically cast it, it needs an explicit cast

### ISSUE THREAD

**Issue by mastercho** [openbullet/OpenBullet2#522]
### Version of the software

0.1.26

### Operating system

Windows 10

### Browser / Native

Chrome  92

### What happened?

Throws Cannot implicitly convert type 'float' to 'int'. An explicit conversion exists (are you missing a cast?)
for compute block

### Relevant LoliCode if needed

```shell
BLOCK:ConstantInteger
  value = 5
  => VAR @myInt
ENDBLOCK

BLOCK:Compute
  input = $"9 - <myInt>"
  => CAP @myInt
ENDBLOCK
```

**Comment by openbullet** [comment]
There's not much I can do here, the Compute block is outputting a float while myInt was initialized as an integer. Use an additional variable as output and then transfer it to the original integer by using a constant block and passing the float variable in variable mode.

```
BLOCK:ConstantInteger
  value = 5
  => VAR @myInt
ENDBLOCK

BLOCK:Compute
  input = $"9 - <myInt>"
  => VAR @myFloat
ENDBLOCK

BLOCK:ConstantInteger
  value = @myFloat
  => VAR @myInt
ENDBLOCK
```
