### ISSUE TITLE
[Bug]: Report captcha need update

### ISSUE THREAD

**Issue by mastercho** [openbullet/OpenBullet2#524]
### Version of the software

0.1.26

### Operating system

Windows 10

### Browser / Native

Chrome  92

### What happened?

On report captcha block in recaptchas returns 

`Could not report the solution of task 654305535 to the service: Captcha not found or expired
`

something in apiside must change here https://anti-captcha.com/apidoc/methods/reportIncorrectRecaptcha they have report options

also be aware your account might be banned

https://ruri.please-fuck.me/5dOoNS9Rv

**Comment by rockyd3vil** [comment]
and exclude report captcha in settings for capmonster.

**Comment by openbullet** [comment]
> 
> 
> and exclude report captcha in settings for capmonster.

Just use SAFE mode so even if it fails it doesn't matter at all and the config continues as normal.

**Comment by rockyd3vil** [comment]
> > and exclude report captcha in settings for capmonster.
> 
> Just use SAFE mode so even if it fails it doesn't matter at all and the config continues as normal.

ok don't change anything...

**Comment by meinname** [comment]
Just tried it with recap (v2)
Report goes to https://api.anti-captcha.com/reportIncorrectImageCaptcha
According to[ Api docu](https://anti-captcha.com/de/apidoc/methods/reportIncorrectRecaptcha) it should be 
https://api.anti-captcha.com/reportIncorrectRecaptcha

**Comment by openbullet** [comment]
Thanks @meinname can you open this in the CaptchaSharp repo please? Thanks
