### ISSUE TITLE
Not supported encoding format 

### ISSUE THREAD

**Issue by Heatcliff688** [openbullet/OpenBullet2#53]
i tried to make some old configs one of them give me none not supported as an encoding format and i want some help here
picture show the error
https://prnt.sc/10i7v5x
and thanks advance for help

**Comment by Laiteux** [comment]
Please add the LoliCode to your message so we can help you better

**Comment by Heatcliff688** [comment]
> Please add the LoliCode to your message so we can help you better

and how i can do that  do you mean sharing my config here or what

**Comment by Laiteux** [comment]
Go to the LoliCode editor and copy the part of code that's broken

**Comment by Heatcliff688** [comment]
> Go to the LoliCode editor and copy the part of code that's broken

its a variable link can i pm you

**Comment by Laiteux** [comment]
Please wait for @openbullet as I'm unsure about how he wants such info to be shared

**Comment by Heatcliff688** [comment]
anyway here is all the lolicode and the broken request is the last one cause in response header there is no encoding format 
BLOCK:ConstantString
LABEL:kk
  value = @input.CODE
  => VAR @kk
ENDBLOCK

BLOCK:HttpRequest
  url = $"http://login.qhdtvpro.info/act.php?login=<kk>"
  customHeaders = {("Host", "login.qhdtvpro.info"), ("Connection", "close"), ("Accept-Encoding", "gzip, deflate"), ("User-Agent", "okhttp/3.8.1")}
  TYPE:STANDARD
  $""
  $"application/octet-stream"
ENDBLOCK

BLOCK:Keycheck
  banIfNoMatch = False
  KEYCHAIN SUCCESS AND
    STRINGKEY @data.SOURCE Contains "msg\":\"Welcome"
    STRINGKEY @data.SOURCE Contains "\"status\":\"001"
  KEYCHAIN FAIL OR
    STRINGKEY @data.SOURCE Contains "msg\":\"Welcome"
    STRINGKEY @data.SOURCE Contains "status\":\"000\""
ENDBLOCK

BLOCK:Parse
  input = @data.SOURCE
  leftDelim = "status\":\"001\",\"msg\":\"Welcome, "
  rightDelim = "\""
  caseSensitive = False
  MODE:LR
  => CAP @ExpirationMSG
ENDBLOCK

BLOCK:HttpRequest
  url = $"http://cdnq.vcdn.tn/iptv/ch30?code=<kk>"
  autoRedirect = False
  customHeaders = {("User-Agent", "QHDTV PRO/2.1.9 (Linux;Android 5.1.1) ExoPlayerLib/2.8.1"), ("Accept-Encoding", "gzip, deflate"), ("Host", "cdnq.vcdn.tn"), ("Connection", "close")}
  TYPE:STANDARD
  $""
  $""
ENDBLOCK

BLOCK:Keycheck
  KEYCHAIN SUCCESS OR
    STRINGKEY @data.HEADERS["Location"] Exists ""
  KEYCHAIN FAIL OR
    STRINGKEY @data.HEADERS["Location"] DoesNotExist ""
ENDBLOCK

BLOCK:Parse
  input = @data.HEADERS["Location"]
  MODE:LR
  => VAR @link1
ENDBLOCK

BLOCK:Parse
  input = @data.HEADERS["Location"]
  leftDelim = "http://"
  rightDelim = "/"
  MODE:LR
  => VAR @host
ENDBLOCK

BLOCK:HttpRequest
  url = $"<link1>"
  autoRedirect = False
  securityProtocol = TLS13
  customHeaders = ${("User-Agent", "QHDTV PRO/2.1.9 (Linux;Android 5.1.1) ExoPlayerLib/2.8.1"), ("Host", "<host>")}
  TYPE:STANDARD
  $""
  $"application/octet-stream"
ENDBLOCK

**Comment by openbullet** [comment]
User blocked for posting illegal content
