### ISSUE TITLE
Custom input Bug  fix ;)

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#533]
Yo Rurri how you doing good man. Hey I know your busy but when you get time can you put this combo box that I have attached as an image for the custom input box. This will fix all the current clicking bug issues that's on the web client. ![image](https://user-images.githubusercontent.com/80471318/139944050-bfc146cb-c22c-4d08-b79a-43925a983861.png)

**Comment by openbullet** [comment]
That's a native WPF combobox. It's made for WPF. The web client is Blazor, what does it have to do with it? You cannot just plug one component from one framework into another one 🤣
