### ISSUE TITLE
Mutliple captures can't download

### ISSUE THREAD

**Issue by rockyd3vil** [openbullet/OpenBullet2#535]
### Version of the software

0.1.26

### Operating system

windows 2019 server

### Browser / Native

chrome

### What happened?

When I capture multi variables , If I download them from hits tab , I can't see the captures from 2nd variable . Instead of that in txt file \n ( next line ) is printing.

**Comment by openbullet** [comment]
You have to give some sample code to replicate the issue otherwise how can I possibly figure out what you mean?

**Comment by rockyd3vil** [comment]
you can try yourself capture mutli captures in jobs, then after download those hits with multi-capture from hits tab.

**Comment by rockyd3vil** [comment]
I made 2 variables captures BAL and API. 
when I downloaded BAL is printing and API is not printing anything
![image](https://user-images.githubusercontent.com/75754463/140330199-33d14af2-ef4b-41d5-8f5c-f3ae110a0bf0.png)
in hits
![image](https://user-images.githubusercontent.com/75754463/140330417-c03518c9-6f04-4269-939f-14643143b127.png)

**Comment by rockyd3vil** [comment]
is this enough ?

**Comment by openbullet** [comment]
There is an option in the config to remove empty captures, maybe disable it. The API capture is not printed to the capture string in the database because it's probably empty.

**Comment by rockyd3vil** [comment]
no I didn't enable anything. in database it is stored but when downloaded it prints \n ( next line operation )..

**Comment by rockyd3vil** [comment]
and Add multi files in DATA POOL in job. only 1 file it is supported.

**Comment by openbullet** [comment]
Closing stale issue, cannot repro
