### ISSUE TITLE
Issue Big Boner custom combox.input

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#539]
This message is for my homeboy Rurri only. Everyone one else stfu. 

- [x] Mr.Amzing Guru coder my homeboy Ruri please fix the custom input box with the what ever the F$&@ it's called combobox in the image below so it will work right. ![image](https://user-images.githubusercontent.com/80471318/140292452-2e8bf33c-acc0-46ba-a25d-366adfbe08be.png) oh don't forget the same combobox problem in the keycheck on the left of the image has the same issue.

**Comment by Cyogenus** [comment]
This problem only is the the web client issue.

**Comment by openbullet** [comment]
Please stahp

https://github.com/openbullet/OpenBullet2/issues/484
