### ISSUE TITLE
[EXCEPTION]: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property

### ISSUE THREAD

**Issue by MrPres1dent** [openbullet/OpenBullet2#540]
### Version of the software

0.1.25

### Operating system

Win 11

### Browser / Native

Native

### What happened?

not always, but often
the error appears despite the fact that all blocks were executed successfully

Unhandled exception thrown on 04.11.2021 11:59:52
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Timeout of 15000 ms exceeded)
 ---> System.TimeoutException: Timeout of 15000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0()
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**Comment by openbullet** [comment]
This was solved a few versions ago so I'm closing the issue
