### ISSUE TITLE
[Bug]: 520 Error when using Cloudflare HOST HTTPS

### ISSUE THREAD

**Issue by bestisben-xyz** [openbullet/OpenBullet2#543]
### Version of the software

0.1.26

### Operating system

Linux Debian

### Browser / Native

Firefox

### What happened?

A bug happened! When I am using the OpenBullet 2 in Cloudflare, the previous version is fine, but new version keep pop Up the error

![image](https://user-images.githubusercontent.com/90732027/140612443-3a6c65a0-6b60-46b1-9ba1-b80e62d4dc2a.png)

**Comment by openbullet** [comment]
Can you try again with the old version (you can find it in the releases on this repo) and see if it really works? Because maybe the site changed something.

**Comment by bestisben-xyz** [comment]
hi @openbullet 
sure not a problem, I will try it later, btw I have saw some error showing in the terminal like : " set up behind a reverse proxy..."

**Comment by openbullet** [comment]
This should be fixed now, closing
