### ISSUE TITLE
Navigate To, block, throws an expectation error

### ISSUE THREAD

**Issue by blueeeeer** [openbullet/OpenBullet2#545]
### Version of the software

0.1.2 beta

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Expectation error will pop up on job runner, if the 'bot' don't connect to the navigated url in a needed time 'Timeout'

**Comment by openbullet** [comment]
Please wait for the next update and this will not be a problem anymore as task exceptions will be ignored

https://github.com/openbullet/OpenBullet2/commit/30d2b526b9559ccd2fcfaa00f8f367608c6431e7
