### ISSUE TITLE
[REQUEST] Capmonster.cloud captcha support

### ISSUE THREAD

**Issue by JustDaixD** [openbullet/OpenBullet2#548]
Hey, OpenBullet can you add cap monster.cloud option in the captchas section?
![image](https://user-images.githubusercontent.com/91605441/141606256-b9b8761c-aa15-4b18-92e1-291bd6820bf0.png)
I was using Custom two captcha to use capmonster.cloud solver but in some cases like geetest captcha it shows error even if the response is correct like this
![image](https://user-images.githubusercontent.com/91605441/141606266-a4f60ff6-06f6-489b-9ca8-0f0218a59f31.png)
HERE there is a valid response from the server but it shows as an error, I know I can just ignore that and just use data.ERROR to parse it but it would be handy if you can add it to the list because capmonster.cloud is a famous website and many people would like to buy captchas from them as they are really cheap compared to other services like 2captcha.

**Comment by openbullet** [comment]
Please open this issue also in the CaptchaSharp repository, thanks

**Comment by JustDaixD** [comment]
> Please open this issue also in the CaptchaSharp repository, thanks

Actually sir i have just noticed that there is one request about this already made by some guy with the same issue https://github.com/openbullet/CaptchaSharp/issues/5 Have a Look

**Comment by openbullet** [comment]
I will check everything as soon as I have some free time available.
