### ISSUE TITLE
[Bug]: Cannot schedule job to start at a certain time

### ISSUE THREAD

**Issue by malaVydra** [openbullet/OpenBullet2#552]
### Version of the software

0.1.26

### Operating system

Windows 10

### Browser / Native

Chrome 95

### What happened?

When I try to schedule a job to "Start at" a certain date and time it doesn't work. The "Start in" function works though. Am I doing something wrong?

**Comment by openbullet** [comment]
Is your OB2 on a vps in a different timezone? Are you setting the start time correctly with respect to the server's timezone?

**Comment by malaVydra** [comment]
No, I'm running OB2 on my PC. I'm setting the time correctly. When I start the job after setting up the schedule, it just starts immediately.

**Comment by openbullet** [comment]
Okay I will check it out

**Comment by openbullet** [comment]
Fixed the issue

https://github.com/openbullet/OpenBullet2/commit/8b804252109eced21f20cbe66de3a17d6fb7f0ba
