### ISSUE TITLE
[Bug]: Imap

### ISSUE THREAD

**Issue by thanhlouis** [openbullet/OpenBullet2#553]
### Version of the software

0.1.26

### Operating system

Windows 10 Pro

### Browser / Native

Native

### What happened?

After run job with 25 bots, can't connect to the imap server with BLOCK:ImapAutoConnect, wordlist is only 1 host

```
>>Trying imap.**.com on port 993...

>>Failed!

>>Failed to query https://live.mozillamessaging.com/autoconfig/v1.1/**.com

If I use BLOCK:ImapConnect

Can connect but too long...

>> Connected to imap.**.com on port 993. SSL/TLS: True

>> Keycheck (CheckCondition) <<

>>Matched key  EqualTo 

>> Imap Login (ImapLogin) <<

>>Authenticated successfully

>> Keycheck (CheckCondition) <<

>>Matched key  EqualTo 

>>BOT ENDED AFTER 22460 ms WITH STATUS: SUCCESS 

Test with OB1 its ok and very fast

>>Succesfully connected to host imap.**.com on port 993. The server says:
>> * OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 NAMESPACE] **Mail XMIMAP4Server ready

>> > A01 LOGIN "823425145@**.com" "PASSWORD"\r\n
>> > A01 OK Success login ok

>> Saved Response in variable response.
>> <--- Executing Block KEY CHECK --->
>> ===== DEBUGGER ENDED AFTER 0.793 SECOND(S) 
```

Try download new openbullet2 (both WebUI and native) and restart the computer still 20000ms....
Hope you understand, my english is not good :(

**Comment by openbullet** [comment]
What do you mean "test with OB1"? OB1 does not have IMAP blocks, it just has a TCP block just like OB2, so maybe you should use the TCP block here as well?

**Comment by thanhlouis** [comment]
tcpblock openbullet 2 response Operation canceled

**Comment by openbullet** [comment]
Well if you don't tell me how to reproduce the issue how can I fix it? 🤣
