### ISSUE TITLE
[REQUEST] Manual Input

### ISSUE THREAD

**Issue by crazygamer96** [openbullet/OpenBullet2#554]
**Is your feature request related to a problem? Please describe.**
Having to modify my config every time I start my job to replace a id

**Describe the solution you'd like**
Have manual input when you start a job that is static throughout the entire job 
I think this would be nice for configs that require something to be changed every time you want to run it again such as for special ids when scraping or something so you don't have to edit the job every time you start it again
maybe the variable format can be <input.MANUAL>[input name that gets prompt at start of job]

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by openbullet** [comment]
This is already a feature. Config > Settings > Custom Inputs. See this guide

https://discourse.openbullet.dev/t/how-to-use-custom-inputs/1352
