### ISSUE TITLE
Unhandle exception  puppeteer

### ISSUE THREAD

**Issue by pasterlevis** [openbullet/OpenBullet2#556]
### Version of the software

0.27

### Operating system

win 10

### Browser / Native

native

### What happened?

![image](https://user-images.githubusercontent.com/66682022/143688853-138a3d85-432b-4702-8735-4f9bb2c2f29b.png)
[crash.log](https://github.com/openbullet/OpenBullet2/files/7612024/crash.log)

```
Unhandled exception thrown on Sat, Nov 27, 21 9:38:36 PM
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Timeout of 30000 ms exceeded)
 ---> System.TimeoutException: Timeout of 30000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0()
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Comment by openbullet** [comment]
What happens when you click the Ok button? Does OB2 close itself or does it keep running?

**Comment by pasterlevis** [comment]
> What happens when you click the Ok button? Does OB2 close itself or does it keep running?

keeps running

**Comment by pasterlevis** [comment]
keeps running
