### ISSUE TITLE
[Bug]: missing "Not Contain" in filter hits list

### ISSUE THREAD

**Issue by churongcon** [openbullet/OpenBullet2#558]
### Version of the software

Lastest

### Operating system

Linux

### Browser / Native

Chrome

### What happened?

Hello
![image](https://user-images.githubusercontent.com/26823364/144731031-48f2330e-1668-4415-855e-aa67356c038c.png)
Can you add 'Not Contain' in in filter hits lists

**Comment by openbullet** [comment]
Hey sorry this is a 3rd party component I have no control over it, and I do not want to fork it. Maybe you should ask on their repository directly. If you do that and they implement this, and release an updated nuget package, then open a new issue here and let me know about it so I can update the nuget package. Thanks!

https://github.com/gustavnavar/Grid.Blazor
