### ISSUE TITLE
[Bug]: PuppeteerGetCookies

### ISSUE THREAD

**Issue by w0205** [openbullet/OpenBullet2#559]
### Version of the software

0.1.27

### Operating system

window10

### Browser / Native

Native

### What happened?

>> Execute JS (PuppeteerExecuteJs) <<

Evaluated document.cookie

Got result: ps=%7B%22bid%22%3A%2261ae19ab21fda200087e7db2%22%2C%22extvid%22%3A%22ext1%3A90567621-c0e2-4d19-94e0-56f5c3347838%22%7D; _csrf=ToI0g9TuL9HkxazFznte-OYs; _dd_s=rum=0&expire=1638800691095

>> Get Cookies (PuppeteerGetCookies) <<

Got 0 cookies for  

Why PuppeteerGetCookies cannot get cookies???

![cookie](https://user-images.githubusercontent.com/37750206/144862252-266a1159-0f7f-46a6-83cb-4fefec50b27c.jpg)

**Comment by openbullet** [comment]
Did you write the correct domain in here? For example if you're on a page with URL `https://example.com/test?blah=blah` you need to write `example.com` otherwise it will not work.

![immagine](https://user-images.githubusercontent.com/48930622/144932192-a67cd6b5-116d-4d54-bf5e-7f13a330cce6.png)

**Comment by w0205** [comment]
Yes, I'm sure I filled in the correct domain. I only opened a website and checked the domain name of cookie with the browser .

**Comment by w0205** [comment]
![cookie](https://user-images.githubusercontent.com/37750206/144962133-886e72ac-93ca-4710-bf32-dd8d35d4885e.jpg)

**Comment by w0205** [comment]
Sorry, No bug, just **Admin Permissions**

**Comment by openbullet** [comment]
Could you elaborate? And please close the issue after you do that, thanks

**Comment by w0205** [comment]
Sorry, I forgot that I am using selenium now. BUG still exists
