### ISSUE TITLE
[Bug]: Cannot start the driver service on http://localhost:51737/

### ISSUE THREAD

**Issue by JustDaixD** [openbullet/OpenBullet2#561]
### Version of the software

0.1.27 [Beta]

### Operating system

Windows 11

### Browser / Native

Microsoft Edge Version 96.0.1054.43 (Official build) (64-bit)

### What happened?

The same thing happens with Selenium as I mentioned in #560 
![image](https://user-images.githubusercontent.com/91605441/145426343-9c95d450-8bbd-4aae-aec3-4504c2bf60f8.png)
![image](https://user-images.githubusercontent.com/91605441/145426812-9d6b5477-68de-4923-b72c-1cb32bf18dcf.png)

```
>> Open Browser (Open Browser) <<

[Executing block Open Browser] WebDriverException: Cannot start the driver service on http://localhost:51756/

BOT ENDED AFTER 21536 ms WITH STATUS: ERROR
```

### Relevant LoliCode if needed

```shell
BLOCK:SeleniumOpenBrowser
ENDBLOCK
```

**Comment by RifHut** [comment]
i think u already changed the port to create two servers in same time , the problem in ob2 structure u can't use 2 chrome drivers in one time
, i think reserved only one time , try to copie Openbullet2 folder in different disk in D:\ as exemple and try
