### ISSUE TITLE
[Bug]: Error while parsing "<" in variable

### ISSUE THREAD

**Issue by tntd2k2** [openbullet/OpenBullet2#563]
### Version of the software

0.1.27

### Operating system

10

### Browser / Native

Native

### What happened?

it parse JSON
`{"a":"<email>", "password":"IL0v3LinhChucamo<3","captcha_key":"<fey_captcha>"}`
to C# code
`string constantStringOutput = ConstantString(data, $"{{\"a\":\"{email}\", \"password\":\"IL0v3LinhChucamo{3 ","  captcha_key  ":" < fey_captcha }\"}}");`

`[IDLE] CompilationErrorException: (3,107): error CS1073: Unexpected token '","'`

### Relevant LoliCode if needed

```shell
BLOCK:ConstantString
  value = $"{\"a\":\"<email>\", \"password\":\"IL0v3LinhChucamo<3\",\"captcha_key\":\"<fey_captcha>\"}"
  => VAR @constantStringOutput
ENDBLOCK
```

**Comment by openbullet** [comment]
Please see the link below for a workaround, currently there is no way to escape `<` and `>`

https://discourse.openbullet.dev/t/how-do-i-apply-such-type-of-a-post-data/4970/12

**Comment by openbullet** [comment]
For reference, I still plan to implement this one day, I will reopen this original issue https://github.com/openbullet/OpenBullet2/issues/66
