### ISSUE TITLE
[Bug]: error 10000 and error 10100

### ISSUE THREAD

**Issue by gabriel9010** [openbullet/OpenBullet2#564]
### Version of the software

1.27

### Operating system

Debian11

### Browser / Native

FireFox

### What happened?

Hello.

Find the broblem error 1000 and error 10100 pls help me 
![Uploading IMG20211214145223.jpg…]()

**Comment by openbullet** [comment]
Please reupload the image, I cannot see anything

**Comment by gabriel9010** [comment]
![Uploading IMG20211214145223.jpg…]()

**Comment by openbullet** [comment]
Same thing... can you upload it on imgur and link it?

**Comment by gabriel9010** [comment]
https://imgur.com/a/TPd1r9C

**Comment by gabriel9010** [comment]
Ho mandato tutto

Il gio 16 dic 2021, 20:53 openbullet ***@***.***> ha scritto:

**Comment by openbullet** [comment]
There is already another issue open for this error, please watch that one until it's resolved https://github.com/openbullet/OpenBullet2/issues/483
