### ISSUE TITLE
2Capthaca not solving Geetest captcha

### ISSUE THREAD

**Issue by prowler123** [openbullet/OpenBullet2#567]
### Version of the software

0.1.27

### Operating system

Windows 10

### Browser / Native

Chrome

### What happened?

whenever i use the service of 2capthca to solve geetest captcha i alyways get this

ERROR_CAPTCHA_UNSOLVABLE

i was asked by u to post my issue and can anyone else Help me out??

**Comment by meinname** [comment]
🤔 
Works for me
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/16181408/146641506-e18a8b3b-f0f4-489b-8987-d1b66a1e5afe.png">

**Comment by EdwardN97** [comment]
it is working without problems
![image](https://user-images.githubusercontent.com/83040418/147161290-42594ea5-1b35-4f7c-a1de-edaab10099dd.png)
