### ISSUE TITLE
[Bug]: Crashing when Switching Tabs

### ISSUE THREAD

**Issue by omgnobody121** [openbullet/OpenBullet2#568]
### Version of the software

Latest

### Operating system

Windows 10

### Browser / Native

Browser

### What happened?

Crashing when Switching Tabs

`Error: Could not find 'gridJsFunctions.isDateTimeLocalSupported' ('gridJsFunctions' was undefined).
    at http://localhost:5000/_framework/blazor.server.js:1:67714
    at Array.forEach (<anonymous>)
    at e.findFunction (http://localhost:5000/_framework/blazor.server.js:1:67674)
    at v (http://localhost:5000/_framework/blazor.server.js:1:69416)
    at http://localhost:5000/_framework/blazor.server.js:1:70362
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.server.js:1:70335)
    at http://localhost:5000/_framework/blazor.server.js:1:26442
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:5000/_framework/blazor.server.js:1:26412)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at GridBlazor.Pages.GridComponent`1.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

**Comment by omgnobody121** [comment]
Aswell, there is no check when making the "session time", I set it to 99999 hours and now am unbale to login since it is "out of bounds". 

crazy how long v2 has been in development but still has so many bugs.

**Comment by openbullet** [comment]
> crazy how long v2 has been in development but still has so many bugs.

You mean this free software that I develop alone in my free time? Yeah, tell me more about it please. Maybe you want a refund? Why don't you try and contribute instead of complaining? 😃

**Comment by Shuffle21** [comment]
> 

I didn't mean it in a bad way sorry. I meant it as it takes a long time and hard work to make a good software and more as a appreciation

**Comment by openbullet** [comment]
Okay I understand, sorry for attacking you. Anyways, are you getting this error when you have multiple tabs of the OB2 web client open and you switch between them? Is there any specific page where this happens?

As for the session time thing, please open a separate issue. Thanks

**Comment by Shuffle21** [comment]
I had only one tab of ob 2 open, it didnt happen on all tabs but happened on the proxy, worker and settings tab (I dont exactly remember).

**Comment by openbullet** [comment]
Ah so you were simply navigating the options of the menu. Did you do it particularly quickly? Did it happen again? Can you consistently replicate it? Thanks ^^

**Comment by Shuffle21** [comment]
Didn't do it quickly, even if I tried once it happened. 

Oh but one thing, it happened when I was launching it through vscode debug. If I downloaded a prebuilt binary it didn't happen, I launched it through vscode since I failed to launch the binary I built myself, not sure why.

**Comment by Shuffle21** [comment]
https://streamable.com/we71d7

**Comment by openbullet** [comment]
It seems to be having problems with the js in general, look at the buttons on the columns of the guests table, they are all weird. I think it's not loading the scripts properly. I see you're on windows, can you try with Visual Studio Community 2022 instead?

**Comment by Shuffle21** [comment]
I am on Visual Studio Community 2022

**Comment by Shuffle21** [comment]
But it works with direct binaries so its fine ig

**Comment by openbullet** [comment]
Anyways, Blazor applications don't work if you just build them and run them directly, you need to use the publish functionality otherwise the static files don't get packed and it causes a lot of issues, maybe that had something to do with it.

Since this is not a game breaking problem, and most likely not something that has to do with OB2 since I'm debugging it just fine on my end, I will close this.
