### ISSUE TITLE
[Security] Workflow dotnet.yml is using vulnerable action tubone24/update_release

### ISSUE THREAD

**Issue by akulpillai** [openbullet/OpenBullet2#569]
The workflow dotnet.yml is referencing action tubone24/update_release using references v1.0. However this reference is missing the commit [57f340d9f6d237e78af226f0889edb48f78ae32f](https://github.com/tubone24/update_release/commits/57f340d9f6d237e78af226f0889edb48f78ae32f) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by meinname** [comment]
Thank you for pointing out on this issue. I updated the workflow to use the latest Version of update_release.
