### ISSUE TITLE
[REQUEST] Re-add normal JSON Parse

### ISSUE THREAD

**Issue by Official-Husko** [openbullet/OpenBullet2#57]
**Is your feature request related to a problem? Please describe.**
Yes, JToken parsing is to much of a headache and the option to use old parsing was faster and easier.

**Describe the solution you'd like**
JToken optional like before

**Describe alternatives you've considered**
Make JSON parsing like in OB1 and add a box to make JToken optional if wanted by the user

**Additional context**
None.

**Comment by openbullet** [comment]
The old way of parsing json made no sense though, really. JToken parsing is really easy to learn with the correct guides and way more reliable. What do other people think about this?

**Comment by tcortega** [comment]
> The old way of parsing json made no sense though, really. JToken parsing is really easy to learn with the correct guides and way more reliable. What do other people think about this?

I'm in complete agreement with you.

**Comment by Official-Husko** [comment]
> 
> 
> The old way of parsing json made no sense though, really. JToken parsing is really easy to learn with the correct guides and way more reliable. What do other people think about this?

I hope it didn't come around rude, could you maybe link me a tutorial a good one? i got to the point where i got certain details but then there is a random value and i can't get past that. I tried for 1 - 2 hours to get it working but i only got a bit of it till the random part came. 

```js
Parsed value: {
  "f5667204-37e9-4445-83c5-96efb68eb5db": { <------ Random Value i need to pass
    "name": "12Mill.txt", <------ Value i need
    "size": 286954355, <------ Value i need
    "mimetype": "text/plain",
    "link": "https://example.com" <------ Value i need
  }
}
```

**Comment by openbullet** [comment]
JToken (actual name is JsonPath) is actually very similar to XPath, you can find a very comprehensive guide here https://goessner.net/articles/JsonPath/

**Comment by openbullet** [comment]
```
BLOCK:ConstantString
  value = "{   \"f5667204-37e9-4445-83c5-96efb68eb5db\": { \"name\": \"textfile.txt\", \"size\": 286954355, \"mimetype\": \"text/plain\", \"link\": \"https://example.com\" } }"
  => VAR @json
ENDBLOCK

BLOCK:Parse
  input = @json
  jToken = "$.*.name"
  MODE:Json
  => VAR @parseOutput
ENDBLOCK
```
This lolicode works perfectly fine for me

**Comment by openbullet** [comment]
> I may also have found a bug. If a Job is paused and you try to clone it then it will break and throw an error.
Please open a different issue for this, thanks.

**Comment by Official-Husko** [comment]
> 
> 
> ```
> BLOCK:ConstantString
>   value = "{   \"f5667204-37e9-4445-83c5-96efb68eb5db\": { \"name\": \"textfile.txt\", \"size\": 286954355, \"mimetype\": \"text/plain\", \"link\": \"https://example.com\" } }"
>   => VAR @json
> ENDBLOCK
> 
> BLOCK:Parse
>   input = @json
>   jToken = "$.*.name"
>   MODE:Json
>   => VAR @parseOutput
> ENDBLOCK
> ```
> 
> This lolicode works perfectly fine for me

Most likely im just to stupid to do it rn, its almost 4 am in the morning afterall. I will give it a shot tomorrow again to see if i get it working. Thanks for your response

**Comment by Cyber-Criminal** [comment]
The old way of making configs made no sense though, really. C# is really easy to learn with the correct guides and way more reliable.

for OB3, Ruri will remove loliscript and you have to use C# only

**Comment by openbullet** [comment]
Closing this as I'm not interested in adding a stupid way of parsing json back into the program.
