### ISSUE TITLE
[Bug]: Puppeter multiple identifiers issue

### ISSUE THREAD

**Issue by Tutunova** [openbullet/OpenBullet2#571]
### Version of the software

Noidea

### Operating system

Windows10

### Browser / Native

Chrome 96

### What happened?

When using multiple select by text it will throw:
[Bug]: Identifier 'el' has already been declared

**Comment by Tutunova** [comment]
Another glitch:
Hey, so i’ve selected things from dropdown’s lists and when i clicked > Go to next page, it still asked for age, thing is, i noticed that it doesnt really select em, like, here’s an example:

When done via JS and selected via text, i went back in the page, then went to this page again, and it was empty.

Instead, when i do it manually and repeat the same proccess, the dropdown lists are already filled in.

**Comment by openbullet** [comment]
Could you provide a sample site where this breaks? Because I couldn't replicate the issue, see attached code

```
BLOCK:PuppeteerOpenBrowser
ENDBLOCK

BLOCK:PuppeteerNavigateTo
  url = "https://www.w3docs.com/learn-html/html-select-tag.html"
ENDBLOCK

BLOCK:PuppeteerSelectByIndex
  findBy = Selector
  identifier = "select"
  selectionIndex = 3
ENDBLOCK

BLOCK:PuppeteerSelectByIndex
  findBy = Selector
  identifier = "select"
  index = 1
  selectionIndex = 3
ENDBLOCK
```
This works without any issue

**Comment by openbullet** [comment]
Fixed the issue, please check if it worked. As for the second issue, maybe there is some js code that is triggered when you actually click on the selection. In that case maybe it would be better to use the Click Element block to first click on the dropdown and then click on the correct option.
