### ISSUE TITLE
auto proxyauth whit selenium

### ISSUE THREAD

**Issue by mamamiia** [openbullet/OpenBullet2#574]
I cant use proxy whit this format on selenium ip:port:user:pass
the browser keep asking for user:pass for the proxy
I have some sources I hope you can fix it
SeleniumHQ/selenium#10042
https://coderedirect.com/questions/158523/how-to-set-proxy-with-authentication-in-selenium-chromedriver-python
https://www.py4u.net/discuss/141444
https://botproxy.net/docs/how-to/setting-chromedriver-proxy-auth-with-selenium-using-python/

**Comment by mamamiia** [comment]
maybe this google extension can help 
https://chrome.google.com/webstore/detail/proxy-auto-auth/ggmdpepbjljkkkdaklfihhngmmgmpggp?hl=en

**Comment by RifHut** [comment]
Already i suggesed the solution  **(you can see the full topic by this id : #602)**, there is an chromium option called **--proxy-server or --proxy-pac-url**,this options work fine, but the box of command option in OB2/OB1 don't accept variables to switch between proxys ,

you can see this topics for more understanding:
https://www.browserstack.com/guide/set-proxy-in-selenium
https://www.linuxbabe.com/desktop-linux/configure-proxy-chromium-google-chrome-command-line

**Comment by openbullet** [comment]
This will continue here https://github.com/openbullet/OpenBullet2/issues/807

**Comment by Gus75000** [comment]
> Already i suggesed the solution **(you can see the full topic by this id : #602)**, there is an chromium option called **--proxy-server or --proxy-pac-url**,this options work fine, but the box of command option in OB2/OB1 don't accept variables to switch between proxys ,
> 
> you can see this topics for more understanding: https://www.browserstack.com/guide/set-proxy-in-selenium https://www.linuxbabe.com/desktop-linux/configure-proxy-chromium-google-chrome-command-line

Hello @RifHut ,
I do not understand clearly your solution for OB2 related to proxy authentification with selenium through Chrome browser.

Thanks in advance for clarification

Greetings
