### ISSUE TITLE
[REQUEST] Websocket Read Does Not Read Binary Messages

### ISSUE THREAD

**Issue by Enigma422** [openbullet/OpenBullet2#575]
### Version of the software

0.1.27

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Websocket read does not read binary messages. Server responded with a binary message that websocket read did not capture.

**Comment by openbullet** [comment]
Can you confirm that this is related to #500 ?

**Comment by Enigma422** [comment]
Yes, the websocket read block can only capture and read text and will not read the binary type messages. I've used the websocket send raw block to send a binary message which worked great but it cant read the binary message that is being sent back in response.

**Comment by openbullet** [comment]
Perfect, I will add another block to read the raw messages then ^^

**Comment by openbullet** [comment]
Since OB2 does not natively support lists of arrays of bytes I will just encode the binary messages to base64 and add them to the usual array, then you can decode them manually if you need.
