### ISSUE TITLE
[Bug] / [REQUEST] suggestions container

### ISSUE THREAD

**Issue by APT-ZERO** [openbullet/OpenBullet2#579]
### Version of the software

0.1.27 [Beta]

### Operating system

Windows 10

### Browser / Native

Latest version of Chrome and Firefox

### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/41063376/147848447-a415eec9-4932-4fba-bbce-a17f23ce2f8f.png)
most of times, when i select a variable from list, in first attempt it does not fill the box, and after the first time, it will work
i tried in chrome and firefox, both are same

actually this is a good one :
![image](https://user-images.githubusercontent.com/41063376/147848510-53bc1c56-72aa-4dad-9eff-3961df7bdf78.png)
that white line around the box made it look great
font size and style is great
space between texts are great
shows more items*
if you make suggestions container a little like this, will be great

**Comment by openbullet** [comment]
It will be fixed in the new client
