### ISSUE TITLE
[Bug]: Custom WordList not doing Jobs

### ISSUE THREAD

**Issue by otreci4sgelt0nas** [openbullet/OpenBullet2#592]
### Version of the software

0.1.27

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Created a customer WordList Type CredentialsEmailPass in Environment.ini file as shown in example.
```
[WORDLIST TYPE]
Name=CredentialsEmailEPass
Regex=^.*:.*:.*:.$
Verify=True
Separator=:
Slices=USERNAME,PASSWORD,EMAIL,EPASSWORD
```
Everything works just fine in the stacker, but when tried in Jobs to run multiple instances it just does not work.
It simply skips and does not even try/run. Not even an error message occurs. 

![skips](https://user-images.githubusercontent.com/96852897/148643060-0b0f3e27-d155-4def-b72c-5d6004605548.png)

![slicing_properly](https://user-images.githubusercontent.com/96852897/148642913-fa919244-372c-47f0-beb4-1010b5038f1d.png)

Reference issue to official forum: [discourse.openbullet.dev/t/custom-wordlist-not-doing-jobs/5141/3](https://discourse.openbullet.dev/t/custom-wordlist-not-doing-jobs/5141/3)

Thank you in advance :)

**Comment by meinname** [comment]
As @openbullet wanted me to test it, here a few screens for him which confirm the Problem.
I use the same Wordlist type.

![image](https://user-images.githubusercontent.com/16181408/148702910-9fd40064-b40a-41e8-8e8a-5eff48208698.png)
![image](https://user-images.githubusercontent.com/16181408/148702919-29184729-a72e-4baf-be7d-d5c68f9ca3aa.png)
![image](https://user-images.githubusercontent.com/16181408/148702926-394a52be-0280-4fd2-a138-4a96d3d8079d.png)
![image](https://user-images.githubusercontent.com/16181408/148702934-68fa3b07-1576-45c0-97d1-7876756fa3ee.png)

**Comment by tcortega** [comment]
What is happening is that your regex is wrong. If you attempt to go and test on websites such as [RegexR](https://regexr.com/) you may see what you missed out.

You accidentally forgot the * at the end of the string to capture everything before the third :
The correct regex would be:
`^.*:.*:.*:.$`

**Comment by tcortega** [comment]
But there seems to be a difference between how the Data Tester works and how the job regex validator works, and I suppose we can discuss this in this issue. If you want me to go and fix it, I can do it @openbullet

**Comment by openbullet** [comment]
@tcortega Hey sure, if there is a discrepancy feel free to fix it!
