### ISSUE TITLE
[Bug]: Internet access to all devices on the same network is very slow

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#593]
### Version of the software

0.1.28

### Operating system

Windows 10 Pro 21H2 - 19044.1415

### Browser / Native

Native

### What happened?

1. Open [NordVPN](https://nordvpn.com/), Connect to `P2P` and Turn ON "[Internet Kill Switch](https://nordvpn.com/features/vpn-kill-switch/)"
2. Start a job on [OpenBullet 2](https://github.com/openbullet/OpenBullet2) and set `Proxy mode: ON` and `Bots: 200`
3. Disconnect from VPN
4. [OpenBullet 2](https://github.com/openbullet/OpenBullet2) will retry to do the job
![image](https://user-images.githubusercontent.com/13978119/148708561-62eca2dd-0d1a-435d-aadf-c55f00348049.png)

Results:
All devices connected to the same network (Smartphones, PCs, TVs) will have VERY SLOW internet access, to the point that pages don't load and messages don't send.

To confirm it's [OpenBullet 2](https://github.com/openbullet/OpenBullet2) that is at fault for causing issues with internet access to all devices connected to the same network - Only when [OpenBullet 2](https://github.com/openbullet/OpenBullet2) is closed then internet access resumes to normal.

**Comment by meinname** [comment]
if it wouldn't be with the killswitch i'd say the NAT Table of your "Router" (the "" cause a Home-router is usually is not really a normal router but a NAT Gateway) gets spammed and so if the thing is not capable of that many connections, everything is slow which needs to pass through it.

But the killswitch should avoid exactly this.
🤔 But maybe it is not working while trying to reconnect? or it is badly implemented and does not block on your PC but sets the route to something non existing or your "router" or whatever.🤷

But overall it is not really a problem of OB2. 
It is a problem of your Network and it's components which are not able to handle that insane amount of bots 
(depending on config most home "routers" can handle 10-35 but not 200)

**Comment by ObsessedHacker** [comment]
In this case, I would like to request a feature/change.
If a job is already running and the connection suddenly drops - abort job automatically instead of retrying.
Something like that would be possible?

**Comment by openbullet** [comment]
It is indeed possible to add this (with a checkbox, default disabled) but it's very low priority so I don't see this being implemented anytime soon, reopen the issue if you want

**Comment by Obegg** [comment]
So after some testing, I found out:
It's not a problem with my router or the settings (200 bots).
The issue occurs when the proxies (remote URLs) do not reload for whatever reason (downtime or temporary issue with the URLs).
Somehow it doesn't show an error or stop the current job.
Therefore I suggest the following:
If proxies fail to reload - abort job/try to reload after 10minutes.

**Comment by openbullet** [comment]
I suggest you follow this issue
https://github.com/openbullet/OpenBullet2/issues/630
