### ISSUE TITLE
[Bug]: OpenBullet dont load

### ISSUE THREAD

**Issue by DrextenMax** [openbullet/OpenBullet2#595]
### Version of the software

0.1.0

### Operating system

Windows 10

### Browser / Native

Chrome

### What happened?

I downloaded the program, i extract it but when i open it dont load

**Comment by DrextenMax** [comment]
Error:
  An assembly specified in the application dependencies manifest (OpenBullet2.deps.json) was not found:
    package: 'DeviceId', version: '5.2.0'
    path: 'lib/netstandard2.0/DeviceId.dll'

**Comment by openbullet** [comment]
Please be more specific. Why are you downloading version 0.1.0? Where did you download it from? Did you extract the archive? Guide us through all the steps you took.
