### ISSUE TITLE
[REQUEST] Searching Help and Information for Openbullet

### ISSUE THREAD

**Issue by ChristianErdtmann** [openbullet/OpenBullet2#596]
Hey iam searching for help with open bullet.

There are much configs online. I got some configs for different things. 
But i cant find explanation to this configs or the usage of openbullet.
There is nothing explained what the DATA region in the runner must show and what is happen when it only retry.
I don't know if I'm using it correctly or doing something wrong.

If there is someone who can help me with my problems and explane me some things.
Please Add me to Discord and write me. My Name is: xGismos#4114

**Comment by openbullet** [comment]
Please use the forum for stuff like this. I am planning to make a separate documentation site and possibly some videos, but I don't have an estimated date for it.

**Comment by ChristianErdtmann** [comment]
Hey do you have a link to the forum for me

**Comment by openbullet** [comment]
It's in the readme of the repository https://discourse.openbullet.dev/
