### ISSUE TITLE
[Bug]: Programm hängt beim Job "Proxy Checker"

### ISSUE THREAD

**Issue by ChristianErdtmann** [openbullet/OpenBullet2#597]
### Version of the software

0.1.28

### Operating system

Windows 11

### Browser / Native

Internet Explorer

### What happened?

Wenn man den Job Proxy Checker aufruft und er bereits existiert und man dann erneut checken will hängt sich die software meistens auf manchmal auf wenn man links wieder auf job klickt. Es geht dann garnichts mehr. Es muss komplett neu erzeugt werden.

**Comment by openbullet** [comment]
Please write in English otherwise I am not able to understand your problem
