### ISSUE TITLE
[Bug]: hello im new in the openbullet2

### ISSUE THREAD

**Issue by Bataloxa11** [openbullet/OpenBullet2#599]
### Version of the software

1.28

### Operating system

Debian11 bullseye

### Browser / Native

Firefox

### What happened?

Hello
could you kindly tell me how to fix these 2 errors thanks for your reply

good evening and good work

**Comment by openbullet** [comment]
Please provide the errors or a screenshot or anything like that otherwise I cannot know what the errors are like

**Comment by Bataloxa11** [comment]
https://imgur.com/a/dlpVfdE

**Comment by Bataloxa11** [comment]
https://imgur.com/a/bv9wViq

**Comment by openbullet** [comment]
You can safely ignore there, they are js errors from blazor they don't come from the logic itself. They never caused an issue to me and I'm getting them constantly.

**Comment by Bataloxa11** [comment]
but how can I see the hits of my config because they don't show up

**Comment by openbullet** [comment]
Can you please describe the exact process you followed to get the hits? Are you sure you got them in the job and then they don't show up in the Hits tab? Can you try and use "File System" as a hit output instead of "Database" in the job options and get some hits again?

**Comment by Bataloxa11** [comment]
I make a video of what I do

**Comment by Bataloxa11** [comment]
Hello have a new problem

**Comment by Bataloxa11** [comment]
https://imgur.com/a/PLSjM1o

**Comment by Bataloxa11** [comment]
I also have this problem does not show me the hits
https://imgur.com/a/XYiy2ON

**Comment by Bataloxa11** [comment]
Pls help me openbullet
