### ISSUE TITLE
[Bug]: Error when trying to delete proxies

### ISSUE THREAD

**Issue by itay0246** [openbullet/OpenBullet2#600]
### Version of the software

0.1.28 [Beta]

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Hello im not sure what happend but i think it is a bug.. when i tested my proxies i got 1 working so i deleted all the others and then i went to jobs to test new config after that i disabled and deleted that job and tried to delete this one working proxy when trying to delete it i get this error i tried even to delete the wordlist but seems like it is not working
![image](https://user-images.githubusercontent.com/43476587/149804612-b15ef213-a489-486f-a3dc-f76f1dc6e97a.png)
help please
1 more thing which is kinda annoying when you add wordlist and you select specific wordlist type and right after that adding a file, the wordlist type is being reseted to the first one on the top.
Thank you for reading hope i wasn't wrong about those and if i did i will be glad for help :)

**Comment by openbullet** [comment]
I think there is already an issue about the proxy one, can you please check?

**Comment by itay0246** [comment]
> I think there is already an issue about the proxy one, can you please check?

I did a short view on the issues here i saw few bugs on proxies but i don't think it is the same one but i might be wrong, thanks

**Comment by openbullet** [comment]
Should be fixed in the next build
