### ISSUE TITLE
[REQUEST] Add shuffle option for wordlists + add paste option for wordlists

### ISSUE THREAD

**Issue by marsman101** [openbullet/OpenBullet2#605]
If you could mix up the wordlist combos it would be cool :). There is already something like this for proxies.

also if you could paste accounts instead of having them from a file would be nice and convenient.

**Comment by openbullet** [comment]
You would lose the ability to preserve your progress since it would just be randomized each time. Also this would mean loading the entire wordlist in memory so it's not as efficient with big lists. Can't you just use something like notepad++ to shuffle the lines when you need to do it?

**Comment by exzin2** [comment]
Please do it manually, create a perfect list of you, do not take advantage and harm bots
