### ISSUE TITLE
[Bug]: misleading error message on compiled config

### ISSUE THREAD

**Issue by meinname** [openbullet/OpenBullet2#606]
### Version of the software

latest

### Operating system

Windows Server 2019

### Browser / Native

Browser

### What happened?

When trying to look at the bot log of a compiled config an error gets shown, which is ok
But the message is a bit misleading 
![image](https://user-images.githubusercontent.com/16181408/150852249-99b68bfc-6d55-4bee-a9d2-47db23f969f1.png)
ofc log was enabled in settings

**Comment by openbullet** [comment]
Closed by PR #612
