### ISSUE TITLE
[Bug]: Sometimes I can't see hits/Custom/To Check , also another problem

### ISSUE THREAD

**Issue by r00tee** [openbullet/OpenBullet2#607]
### Version of the software

0.1.28 [Beta]

### Operating system

Windows 11

### Browser / Native

Microsoft edge

### What happened?

![0981737270373edbff00c43905c58339168984f9](https://user-images.githubusercontent.com/32619657/151060722-ace3d346-8abb-4662-a8b7-0ba0aea32ff2.gif)

![Untitled Project](https://user-images.githubusercontent.com/32619657/151062028-e9d88400-874d-49ba-bd20-cc2102451df0.gif)

**Comment by openbullet** [comment]
This will be fixed in the new web client
