### ISSUE TITLE
[REQUEST] Hindi Translation

### ISSUE THREAD

**Issue by Generation88** [openbullet/OpenBullet2#61]
Please add hindi translation. i can help translate it.

**Comment by matsver** [comment]
https://discourse.openbullet.dev/t/how-to-add-or-modify-translations/33

**Comment by Laiteux** [comment]
Thanks for offering your help! You can find a guide to add a translation [here](https://discourse.openbullet.dev/t/how-to-add-or-modify-translations/33).
