### ISSUE TITLE
[Bug]: Skip number doesn't update when selecting a different wordlist

### ISSUE THREAD

**Issue by Obegg** [openbullet/OpenBullet2#611]
### Version of the software

0.1.28

### Operating system

Windows 10 Pro x64 21H2 19044.1466

### Browser / Native

Native

### What happened?

1. Start a job with wordlist "A"
2. Wait for the skip number to be above 0
3. Abort job
4. Add **new** wordlist "B"

Result:
The skip number is the same when the job stopped with wordlist "A".

**Comment by openbullet** [comment]
Fixed by PR #613
