### ISSUE TITLE
[BUG] The problem with XML as content type

### ISSUE THREAD

**Issue by RiseFox** [openbullet/OpenBullet2#62]
**Describe the bug**

The problem when sending XML code in Content as text/xml content type requests

**To Reproduce**

The problem when sending XML code in Content as text/xml content type requests, I get an error of this:
When CompilationErrorException: (19,123): error CS8076: Missing close delimiter '}' for interpolated expression started with '{'.

**Expected behavior**
The problem is if the request is written in Stacker, then it does not correctly translate the code into C #, of course I can fix it with my own hands in the C # code, but then it's a crutch.

`<?xml version="1.0" encoding="UTF-8"?><ecp:message xmlns:ecp="http://www.somesite.com/ecp"></ecp:container></ecp:message>`

**Screenshots**

![image](https://user-images.githubusercontent.com/28965614/110770208-b8468500-8261-11eb-880b-6d608ba13a57.png)

**Comment by Laiteux** [comment]
Can you please paste what C# code it produces?

**Comment by tcortega** [comment]
What is happening is: you're trying to pass a string that uses <> as interpolated data in the content, while interpolated data is reserved for variables only. In case you don't have any actual variable in this content, just change the type in the right blue button, but, in case you have interpolated variables in it, I'd recommend creating `Constant Blocks` with the type of string, and then you could try partitioning this string, it'd end up being something like this: 

`BLOCK:ConstantString
LABEL:left
  value = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ecp:message xmlns:ecp=\""
  => VAR @left
ENDBLOCK

BLOCK:ConstantString
LABEL:right
  value = "\"></ecp:container></ecp:message>"
  => VAR @right
ENDBLOCK

BLOCK:HttpRequest
  TYPE:STANDARD
  @left + input.USERNAME + right
  "application/x-www-form-urlencoded"
ENDBLOCK`

**Comment by openbullet** [comment]
Maybe we need a way to define an escape sequence in the regex to read `<` and `>` literally

**Comment by RiseFox** [comment]
looks interesting, btw i have have interpolated variables in, add here not a full code for save it from a leak, sorry about it, can send it only as dm,  btw found 2 moments in length can`t to use string like `{"api_key":"15cb936e6d19cd7db1d6f94b96017541","client":"Android-3.4.2.4.52477b52477","os":"22","password":"<PASS>","username":"<USER>","uuid":"6d29ef61-ff19-4124-a053-e148475cf889"} ` 
same error, btw all works in ob1.
better mb way to define this.

**Comment by openbullet** [comment]
https://discourse.openbullet.dev/t/comprehensive-guide-to-wordlist-types/435

**Comment by RiseFox** [comment]
@openbullet with wordlist all fine, i mean same like with XML code in content for Http Request block i have in Length block

![image](https://user-images.githubusercontent.com/28965614/110806432-bd6bfa00-828a-11eb-976e-61b0558469b3.png)
`[IDLE] CompilationErrorException: (7,25): error CS1525: Invalid expression term '{'`
 in old OB it was function Length, and where is GenerateGuid (this is not very important cuz ez to use RandomString) btw XML and my 1 comment before i think is need it (as i said before i can make a some crutch what fix all my problems, cuz i can to do it as special plugin btw it's a crutch)

**Comment by tcortega** [comment]
> @openbullet with wordlist all fine, i mean same like with XML code in content for Http Request block i have in Length block
> 
> ![image](https://user-images.githubusercontent.com/28965614/110806432-bd6bfa00-828a-11eb-976e-61b0558469b3.png)
> `[IDLE] CompilationErrorException: (7,25): error CS1525: Invalid expression term '{'`
> in old OB it was function Length, and where is GenerateGuid (this is not very important cuz ez to use RandomString) btw XML and my 1 comment before i think is need it (as i said before i can make a some crutch what fix all my problems, cuz i can to do it as special plugin btw it's a crutch)
> 
> Hmm changed var to old OB style now all fine, then need only ideas with XML and windows-1251

The error is happening because you're using the var type in the input, specified in the blue button on the right side of the input field. Just change it to interpolated and it will work fine.

And for you XML content, for now you can just use the solution I gave you over here: https://github.com/openbullet/OpenBullet2/issues/62#issuecomment-796718689

**Comment by openbullet** [comment]
You are using the input parameter as VAR type, it should be interpolated (`</>` icon) click on the blue button that says VAR until the background of the textbox turns green

**Comment by openbullet** [comment]
Ah didn't see you already got a reply xD the page didn't refresh properly. Anyways I think we should make a new issue to add the thing I mentioned above (escaping `<`)

**Comment by RiseFox** [comment]
@openbullet i did this with recommend by tcortega, btw realy need normal fix not like this XD 7 String constant for 2 requests XD to op

**Comment by openbullet** [comment]
@RiseFox yes follow the other issue #66 please
