### ISSUE TITLE
[Bug]: Wont upload configs

### ISSUE THREAD

**Issue by Bugleman** [openbullet/OpenBullet2#621]
### Version of the software

0.2.0

### Operating system

Linux 5.10.63-v7l+ #1496 SMP

### Browser / Native

Chromium

### What happened?

When trying to upload any .loli config it gives a "End of Central Directory record could not be found."
Error.
![2022-02-01-134837_1920x1080_scrot](https://user-images.githubusercontent.com/83040443/151931075-2ee7ab4a-df87-422d-afa5-c22dca2406c7.png)

**Comment by openbullet** [comment]
In order to use `.loli` configs in OB2 you need to place them in the `UserData/Configs` folder of OB2 and then click on the Reload button. It will repackage them to .opk format so be careful and make a copy before doing so!

**Comment by openbullet** [comment]
Actually I will leave this issue open so that I can add support for adding .loli configs via the upload button as well.

**Comment by Bugleman** [comment]
Thanks,
Btw when trying to copy / move any files into /UserData it says permission denied I have tried using the CLI but I cant seem to move any config or any file into /UserData

**Comment by openbullet** [comment]
Hey, maybe your OB2 is in a folder that only root can access, but you're trying to copy the files to that location as a user with lower privileges. You should consider moving OB2 to another folder.
