### ISSUE TITLE
[REQUEST] select multiple lists in the job section

### ISSUE THREAD

**Issue by Thughers** [openbullet/OpenBullet2#624]
**Is your feature request related to a problem? Please describe.**
I happen to have to try different wordlists for a single config and I have to create multiple jobs for the same config and find 100 jobs with the same config with different wordlists.

**Describe the solution you'd like**
it would be useful to add the multiple selection of wordlists so when one wordlist ends the job goes to the next and so on, in this way you would have a very organized job organization.

**Describe alternatives you've considered**
at the moment I can't think of alternatives I find the one described very functional.

**Additional context**
no additional content is required

**Comment by openbullet** [comment]
https://github.com/openbullet/OpenBullet2/issues/31
