### ISSUE TITLE
[Bug]: Thread pool starvation when load proxies

### ISSUE THREAD

**Issue by Theodikes** [openbullet/OpenBullet2#630]
### Version of the software

0.2.0 / 0.2.1

### Operating system

Ubuntu 20.04 / Windows 10

### Browser / Native

Browser

### What happened?

When I set proxy reload interval, e. g. one minute, and OpenBullet cannot fetch proxylist from remote URL, the program, instead of repeating requests over and over again, simply frozes with an error<details> <summary> Error screenshot </summary>![error](https://imgur.com/T4GHyGu.png) </details>
And futhermore, if I set proxy reload interval to 0 and change checkbox "No valid proxy behaviour" from "Unban" to "Reload", OpenBullet2, if it is not possible to get the list of proxies from URL, starts request spamming ([2-3 times per second](https://user-images.githubusercontent.com/44587268/153772291-b5bba85d-fe12-4358-b33e-7aedc4b3a2d6.png)), then OpenBullet crashes. Nothing can be done about this, since there is no functionality to set a delay in this case.

I also thought that there is an opportunity in the side menu, in the "Proxies" tab, to create a separate group that will be updated, say, once a minute, and all Job`s will use it, but it didn’t work out here either - you can’t set an update timer per proxy group.

Please tell me how to solve this problem. It is not specific to a certain system, I tried both on Windows and Linux of different versions, and with different proxies.

**Comment by Obegg** [comment]
I think this issue is supposed to be on ![image](https://user-images.githubusercontent.com/13978119/158960434-008f159e-d0b6-4188-bfcc-0ad23f8c407c.png)
