### ISSUE TITLE
[Bug]:  OB2 Console Not Working 

### ISSUE THREAD

**Issue by RifHut** [openbullet/OpenBullet2#634]
### Version of the software

0.2.0 and 0.2.1

### Operating system

Windows 10 Pro / Windows 10 server 2019

### Browser / Native

Console

### What happened?

I try with different methods but the some issue , please dude can u test the latest OB2 console version for me ? @Ruri 
![image](https://user-images.githubusercontent.com/51222371/154082035-9bcd7635-42c0-4fd1-b047-fb2236ef0ea1.png)

Still in Finished status with 0 hits 0 fail ...
I really need this

**Proof that I followed all the steps:**

### **1 - : Environment.ini**

```
[WORDLIST TYPE]
Name=VERIF
Regex=^(.*@.*)|(.*)|(.*@.*):\\+([0-9]{12})$
Verify=True
Separator=|
Slices=EMAIL,PASS,EMBER
```
### **2 - : rockyou.txt**

PATH : `publish\rockyou.txt`
CONTENT : `email@gmail.com|password@|email@gmail.com:+212600000000`

### **3 -: exec.bat** 

```
@echo off
"bin\OpenBullet2.Console.exe" --bots 1 --config V1.opk --wordlist rockyou.txt --wltype VERIF
pause
```

### **4 -: Screen2 tested with .bat**

![image](https://user-images.githubusercontent.com/51222371/154081788-441d5612-2025-4039-a5b8-4fa55c49713e.png)

**Comment by openbullet** [comment]
Fixed in https://github.com/openbullet/OpenBullet2/commit/2b2176932ea859724efca56a7448afd8f66efb05
