### ISSUE TITLE
[Bug]: Reorder of conditions in keycheck block don't change order in C# and Lolicode

### ISSUE THREAD

**Issue by tntd2k2** [openbullet/OpenBullet2#635]
### Version of the software

0.2.1

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

https://user-images.githubusercontent.com/47687492/154125811-11f09aca-6be9-43bc-856f-a285d018cc5f.mp4

**Comment by openbullet** [comment]
Stop uploading videos showing yourself doing what you shouldn't be doing

**Comment by tntd2k2** [comment]
Any feature in keycheck block that i can reorder the conditions?

**Comment by tntd2k2** [comment]
@openbullet Check this one.
UI change but lolicode not change then it change my conditions order.
https://user-images.githubusercontent.com/47687492/154128498-0a43bac0-f664-414c-8370-7633edb7f772.mp4
