### ISSUE TITLE
[Bug]: Reorder of conditions in keycheck block don't change order in C# and Lolicode

### ISSUE THREAD

**Issue by tntd2k2** [openbullet/OpenBullet2#636]
### Version of the software

0.2.1

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

When i reorder the conditions in keycheck block, UI changed but nothing change in lolicode and it reorder the condtion back.

P/s: Sorry for last time, i uploaded wrong video. I think it is a bug so i decide to open issue again. If it's not a bug, sorry for your time.

https://user-images.githubusercontent.com/47687492/154131143-c86ff5b7-7401-420f-a8ba-c7fdcd57a337.mp4

**Comment by openbullet** [comment]
Can you please try the same in the web client and let me know if it's just an issue of the native client? Thanks

**Comment by tntd2k2** [comment]
> Can you please try the same in the web client and let me know if it's just an issue of the native client? Thanks

@openbullet It's just an issue of native client. Web client works well.
