### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xXvolcanoXx** [openbullet/OpenBullet2#637]
### Version of the software

1.2.2

### Operating system

win10

### Browser / Native

chrome

### What happened?

hey 
i'm trying to parse crsftoken from cookies but it wont i anyone have any idea how it works 
![image](https://user-images.githubusercontent.com/99762701/154139677-4d3a5d31-d3ee-46f5-a029-120d7a447cb8.png)

im i doing it wrong ? 
![image](https://user-images.githubusercontent.com/99762701/154139776-78037ca9-1970-4107-8ca6-a0c0c0721266.png)

**Comment by openbullet** [comment]
OB1 is not supported anymore, switch to OB2
