### ISSUE TITLE
this config does not support the provided wordlist type

### ISSUE THREAD

**Issue by connected201** [openbullet/OpenBullet2#639]
### Version of the software

0.2.1

### Operating system

windows 8.1

### Browser / Native

Native

### What happened?

when i want to run taks, i receive this error:
this config does not support the provided wordlist type
post request format: username=<USERNAME>&password=<PASSWORD>&realm=pam
but i tried with <USER> and <PASS> same results
also Environment.ini
```
[WORDLIST TYPE]
Name=Credentials
Regex=^.*:.*$
Verify=True
Separator=:
Slices=USERNAME,PASSWORD
SlicesAlias=USER,PASS
```
![image](https://user-images.githubusercontent.com/20506433/154860080-8f03f9dc-cb15-4631-b56b-2f345eb349de.png)
![image](https://user-images.githubusercontent.com/20506433/154860164-2ba6182f-b1fc-4f7a-9cb5-09581b5f03df.png)
![image](https://user-images.githubusercontent.com/20506433/154860486-8fca301d-1eda-4a5e-b408-2522f1661c3e.png)

### Relevant LoliCode if needed

```shell
BLOCK:HttpRequest
LABEL:try to login
  url = "https://192.168.1.50:8006/api2/extjs/access/ticket"
  method = POST
  TYPE:STANDARD
  $"username=<USER>&password=<PASS>&realm=pam"
  "application/json"
ENDBLOCK

BLOCK:Keycheck
LABEL:success or not
  KEYCHAIN SUCCESS OR
    STRINGKEY @data.SOURCE Contains "CSRFPreventionToken"
  KEYCHAIN FAIL OR
    STRINGKEY @data.SOURCE Contains "authentication failure"
ENDBLOCK
```

**Comment by connected201** [comment]
i found problem, i need to enter in settings=>data, and add to allowed

![](https://user-images.githubusercontent.com/20506433/154860844-26b24e2a-6286-4ec9-afb9-abf65fec1711.png)

**Comment by Scizerisop** [comment]
I have a problem, wordlist say is not accepted

**Comment by Daftyyy** [comment]
> i found problem, i need to enter in settings=>data, and add to allowed
> 
> ![](https://user-images.githubusercontent.com/20506433/154860844-26b24e2a-6286-4ec9-afb9-abf65fec1711.png)

may I ask how to find "settings=>data"?  Because I only found the option to manually set the config to Email and not your screen + my solution didnt worked so Id appreciate your help

**Comment by Daftyyy** [comment]
> ###
> **[Daftyyy](/Daftyyy) ** commented [Mar 30, 2023](#issuecomment-1489553558) •

https://github.com/openbullet/OpenBullet2/issues/639#issuecomment-1489553558
