### ISSUE TITLE
[BUG] Screenshot not saving as .png or .jpeg

### ISSUE THREAD

**Issue by matsver** [openbullet/OpenBullet2#64]
When i take a screenshot of the page with pupeteer it saves it saves it but not as jpg or png file. Its also very blurry

Take screenshot on pupeteer page

[REMOVED]
^^ renamed this manually to add .jpg in order to upload to github

And it just stores it in the root dir of openbullet maybe make a diffrent folder for it?

**Comment by openbullet** [comment]
Use screenshot to base64 and then the file > write bytes so you can define your own path
