### ISSUE TITLE
[REQUEST] Documentation,

### ISSUE THREAD

**Issue by jayhill365** [openbullet/OpenBullet2#641]
Are there any solid attack example docs ?

**Comment by openbullet** [comment]
Not yet, I am building an in-depth documentation site, one page at a time, it will take a while before it's completed though since I don't have much time to dedicate to it.

**Comment by jayhill365** [comment]
Okay thanks, I might help and put some effort into building this out.

**Comment by openbullet** [comment]
@jayhill365 Do you mean the documentation or the software itself? Either way, I appreciate it. The repo for the documentation is private at the moment, I will be making it public soon.

**Comment by jayhill365** [comment]
Thanks, @openbullet  is there anyway I can take a look at the documentation before you make it public?

**Comment by jayhill365** [comment]
Wanted to use this and chain it to another project https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b
  
as like an automated phishing / credential use in one go

**Comment by jayhill365** [comment]
Gotcha, its a great tool! I'm working full time as well too. I just think the 2fa to ---> credential use would be a nice enhancement to have.
