### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Draco420404** [openbullet/OpenBullet2#642]
### Version of the software

1.2.2

### Operating system

Windows 10

### Browser / Native

Chrome

### What happened?

In my Request block, I used a POST METHOD and checked the “Read Resp Source” to post my data to a website but I keep getting “(website url) 404 not found“ in the log section and the html view but the site works/display well in the html view when I turn off “Read Resp Source“ but still shows “(website url) 404 not found“ in the log section. Why’s that please ??? 
I tried the GET METHOD with the “Read Resp Source” Checked it worked well but post is giving me issue and the actual METHOD is POST

**Comment by openbullet** [comment]
This depends on the actual site, it's not an issue of OB2. You're most likely making the wrong request / setting the wrong URL.

**Comment by Draco420404** [comment]
I just unchecked the “Read Resp Source” and it worked fine. So ? Does it mean not all the website needs the Read Resp Source???

**Comment by openbullet** [comment]
Read Resp Source simply means "don't read the body of the response sent by the server". That's it. So if you don't see the error message anymore, it means that it's not reading it. It's just a read from the network stream, it's not something magical that changes what the server sees.

**Comment by Draco420404** [comment]
Okay I understand. Thanks 🙏 a lot
