### ISSUE TITLE
[Bug]: OB2 not working on M1 Macs

### ISSUE THREAD

**Issue by meinname** [openbullet/OpenBullet2#650]
### Version of the software

0.2.1

### Operating system

Macos Monterey

### Browser / Native

Browser

### What happened?

Same as https://github.com/dotnet/efcore/issues/24198

**Comment by JReming85** [comment]
Sadly nothing can be done until SQLite gets updated, looks like they have a PR to fix it tho.

**Comment by meinname** [comment]
Will be fixed on next ob2 build coming soon
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/16181408/158066783-8b14588e-ebcd-4f1f-9583-7e1badf24b06.png">

BTW: it will still need to allow sqlite3 in Security preferences of your mac after first try to start. But after that ob2 should work (maybe you need also to use an other port - as i did. Cause Airplay sits on Port 5000)

**Comment by openbullet** [comment]
Build pushed, M1 supported from 0.2.3

**Comment by meinname** [comment]
Reopen: i noticed when we would update the efcore nuget(s) to the latest version we wouldn't need the security preferences stuff anymore.
So maybe we should update the packages again 
(did a quick test and at least ob2 did start on macos and was able to show hits from an existing DB)

**Comment by openbullet** [comment]
@meinname is this fixed now?

**Comment by meinname** [comment]
yes, was fixed long time ago ;)
Closing this
