### ISSUE TITLE
[REQUEST] New config option to strip certain characters from email:pass

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#651]
**Is your feature request related to a problem? Please describe.**
Feel free to decline as this is a weird one, but depending on application I am testing the password requirements vary... 
e.g. 1 site we have hosted behind CF doesnt allow < > /  etc, and will net a < error from CF without passing to site, but is acceptable on another site that has less strict password requirements.

**Describe the solution you'd like**
A special option in the script to parse & remove selected characters from the input.USER/PASS vars.  I tried doing it myself  but it would fail replacing back to input.PASS

I know I can do it manually but was thinking if it wasnt too much trouble to add it as a feature so I can use the same lists for my sites

**Describe alternatives you've considered**
Alt, I can manually replace and set to a new var and pass the new var instead of input.USER/PASS

**Additional context**
Just a weird request, feel free to decline if you think its a poor idea or waste of time.

**Comment by openbullet** [comment]
Sorry I think this is not something that will be a useful improvement for many people, it's better to do it manually with a block.

**Comment by JReming85** [comment]
not an issue, figured this would be the most likely outcome.

Thanks for reviewing
