### ISSUE TITLE
Parse "Execute JS" output

### ISSUE THREAD

**Issue by Ostrich2020** [openbullet/OpenBullet2#652]
is there a way to parse a variable/response of executed JS code in either versions of OB?

**Comment by openbullet** [comment]
Hi, at the moment you can only evaluate expressions, I would need to implement this https://github.com/hardkoded/puppeteer-sharp/blob/master/docfx_project/examples/Page.EvaluateFunctionAsync.ComplexJSObjects.md in the block (maybe via a checkbox). I can definitely do that, stay tuned for it in the next version.

**Comment by openbullet** [comment]
But I found out you can do this!

```
BLOCK:PuppeteerOpenBrowser
ENDBLOCK

BLOCK:PuppeteerExecuteJs
  expression = "function hello() { return 'hello' }; hello();"
  => VAR @puppeteerExecuteJsOutput
ENDBLOCK
```
Just declare it inside a function and then call that function.

**Comment by openbullet** [comment]
Closed for inactivity
