### ISSUE TITLE
[Bug]: Block copy error

### ISSUE THREAD

**Issue by beyto0o** [openbullet/OpenBullet2#656]
### Version of the software

0.2.2

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

i get an error when i try to copy a block
![Screenshot_1](https://user-images.githubusercontent.com/90928376/158058048-426d87c4-34a4-4cab-b5e1-12452ae3296f.png)
[crash.log](https://github.com/openbullet/OpenBullet2/files/8239433/crash.log)

Correction;
I get error in "Http Request" block

**Comment by JReming85** [comment]
![image](https://user-images.githubusercontent.com/21246660/158058557-a0c4baba-5966-4f86-9a1b-77831fd68639.png)

**Comment by openbullet** [comment]
This was already fixed yesterday, I will push a new build today
https://github.com/openbullet/OpenBullet2/issues/653
