### ISSUE TITLE
[REQUEST] Add BlockResources Plugin for Puppeteer

### ISSUE THREAD

**Issue by ShayMe21** [openbullet/OpenBullet2#658]
https://github.com/Overmiind/Puppeteer-sharp-extra/tree/master/PuppeteerExtraSharp/Plugins/BlockResources

This feature would be extremely handy when using paid proxy servers. As some proxy servers charge you based on bandwidth you use, so It would be a great idea to be able to block static resources like Images, Video, Fonts, etc from a page when using the Puppeteer bot.

I searched through the OB2 code and couldn't find this plugin used anywhere.

This could be a simple Block that lets you pick the static resources to block on the page.

**Comment by openbullet** [comment]
Have you tried enabling this option in Config Settings?

![immagine](https://user-images.githubusercontent.com/48930622/158231804-086301d1-c498-4123-b1e9-4d5edb72b3d4.png)

Because it does exactly what you ask, it only loads the html and scripts. Let me know if the problem was fixed.

**Comment by ShayMe21** [comment]
I must have somehow missed that option. Thanks for that.
My proxy server must be extremely slow even after blocking other resources, it is still timing out!
