### ISSUE TITLE
[Bug]: WEB - Send to Recheck broken

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#661]
### Version of the software

0.2.3

### Operating system

Windows Server 2019 DC

### Browser / Native

Latest Opera/Chrome

### What happened?

I went and sent a few hits from the **Hits** page to recheck.

It transferred everything over to a new job and by force of habit just started it without changing the Wordlist Type

It refused to start but also wont stop and is stuck on **X Skip Wait**
![image](https://user-images.githubusercontent.com/21246660/158505615-9414a2b8-656d-455d-890a-4e8c6c0712bd.png)

I also think an easy fix would be to be able to assign multiple wordlist types to each file to prevent accidents

**Comment by meinname** [comment]
Tried to replicate. 
But for me always the wordlist type from hits was set 🤷

**Comment by JReming85** [comment]
Set it to the wrong wrodlist type

**Comment by openbullet** [comment]
If I remember correctly, the "send to recheck" function takes the wordlist type from the first selected hit and assigns it to the new temp wordlist.

**Comment by JReming85** [comment]
Maybe its related back to the initial issue with changing Wordlist Types where it never actually changed?

It auto selects Credentials for other hits, but when I select from a certain group it always defaults to UserPass

Just a note all my wordlists are set to Credentials and all configs allow both.

**Comment by openbullet** [comment]
> initial issue with changing Wordlist Types where it never actually changed

I fixed that issue in one of the latest updates though, it's tested and works.

**Comment by JReming85** [comment]
I know that, but thats the only reason I can think it would populate with the wrong wordlist type

**Comment by openbullet** [comment]
We will investigate with hits with 2 different wordlist types then

**Comment by JReming85** [comment]
The main issue tho is once you save/start with the wrong wordlist time you cant stop it.

It stays stuck on Waiting

**Comment by openbullet** [comment]
Yeah I understand, I will definitely fix this. Thanks!
