### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Minhne22** [openbullet/OpenBullet2#662]
### Version of the software

1.2.2

### Operating system

Windows 11

### Browser / Native

Chrome 96

### What happened?

I parsed PARSE "<USER>" LR "" "@" -> VAR "user_mail" 
Post data: id=<user_mail>&signup=
But when I try to send data, it turns out to be: id=&signup=
SBS:Step Data:testmail@test.com Default

**Comment by openbullet** [comment]
OB1 is not supported anymore, and this isn't even the correct repo
