### ISSUE TITLE
[Bug]: Wordlist upload speed slow 

### ISSUE THREAD

**Issue by sunneydev** [openbullet/OpenBullet2#664]
### Version of the software

0.2.3

### Operating system

Linux

### Browser / Native

Browser

### What happened?

Upload speed is slow. I'm not sure if it's the issue with the blazor file upload method, but uploading a file on websocket in 27kb chunks of base64 encoded bytes takes forever.

**Comment by openbullet** [comment]
New web client should fix this. If not, it might be your connection
