### ISSUE TITLE
[REQUEST] Debug custom inputs in the stack menu.

### ISSUE THREAD

**Issue by neonsea** [openbullet/OpenBullet2#667]
**Problem**: In the actual version of OpenBullet2, it's impossible to easily debug a custom **input prompt** in the stacker editor.

**Description**: Basically, when we press "START", the custom input is ignored, and the prompt doesn't ever appears. However, it's completely normal when the same config is ran inside an actual Job.

**Request**: Make possible to test our custom inputs during the stack editing, because some configs are dependant on the input system to make sense, and debug it unpon the Multi-Run job is a real pain.

**Nice info**: Tested in the most recent versions of OpenBullet 2 (native/remote).

**Comment by openbullet** [comment]
It was very annoying to have all the input boxes pop up in EVERY run so I changed it. Now OB2's debugger will assign whatever value is in the `Default` field of the custom input to the input variable. Alternatively, you can add something like this at the beginning of your config while you're debugging.

```
input.MYVAR = "my test value";
```
