### ISSUE TITLE
[REQUEST] Lolicode Word Wrap & Config Search

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#678]
1. It would be great to be able to have an option to word wrap the editor in Lolicode as working with small screen sizes can be difficult sometimes.
2. For people having 100+ configs, it would be great to have a search bar where you can search for the config name.
Thank you

**Comment by openbullet** [comment]
Hey

1. I agree, I will definitely add this
2. Switch to the detailed view and just filter on the config column
