### ISSUE TITLE
[BUG] socks5 auth proxy not work with puppeteer

### ISSUE THREAD

**Issue by amrmostafa800** [openbullet/OpenBullet2#68]
socks5 auth proxy not work with puppeteer
if cant edit this
i think you can make proxys work Across other proxy
localhost proxy send data to proxy
all proxyes work across localhost proxy
like luminati proxy manger
but Unfortunately luminati proxy manger only support ssl proxyes :(

**Comment by openbullet** [comment]
This is not an issue with OB2 but with puppeteer, please follow this issue https://github.com/puppeteer/puppeteer/issues/4170 and when it's solve reopen this issue or make a new one so I can update the puppeteer package in OB2.

**Comment by amrmostafa800** [comment]
check this https://github.com/apify/proxy-chain
i think you can fix issue with it

**Comment by openbullet** [comment]
As you can see above issue is fixed in a PR that I just merged https://github.com/openbullet/OpenBullet2/commit/af06485d3829e4813ef41e57d8988214079cf28b

**Comment by amrmostafa800** [comment]
not work i test the new 0.1.2 release
ERR_TUNNEL_CONNECTION_FAILED
