### ISSUE TITLE
[REQUEST] Add a release of native ob2 to run without installing .net desktop runtime

### ISSUE THREAD

**Issue by APT-ZERO** [openbullet/OpenBullet2#680]
![image](https://user-images.githubusercontent.com/41063376/161305503-0d2c8b89-c1c6-4587-87ce-48f72b365f1c.png)
Please add another release of native ob2 to run without installing .Net Desktop Runtime
you can also do same about browser version
thanks

**Comment by openbullet** [comment]
What's the point though? It would just add some nuisance to the updater. Is there some reason why you cannot install .NET 6 directly?

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
> What's the point though? It would just add some nuisance to the updater. Is there some reason why you cannot install .NET 6 directly?

because sometimes i have an rdp without admin access and i can install nothing. and also it's useful in other cases
