### ISSUE TITLE
add "ignore Response Errors" as in OB1 [REQUEST]

### ISSUE THREAD

**Issue by ZEUS-src** [openbullet/OpenBullet2#682]
can you add "ignore Response Errors" as in OB1 in OB2 
![Screenshot 2022-04-01 162722](https://user-images.githubusercontent.com/83480310/161307248-f093cf8f-8236-4f9a-b4f8-b5c79200af61.png)

**Comment by openbullet** [comment]
You can just add a try/catch around the block.
I will leave this open so I remember to add a SAFE checkbox for the http block as well. I'm currently adding it to the parse block and it's already added to the majority of other blocks. That option will catch every error that might happen in the block.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
SAFE checkbox is needed for 'Key Check' block too
i use try catch for Key Check in my configs
