### ISSUE TITLE
[Bug]: random string custom charset

### ISSUE THREAD

**Issue by exzin2** [openbullet/OpenBullet2#686]
### Version of the software

0.2.3

### Operating system

windows 11 10 7 server 2019

### Browser / Native

native

### What happened?

Custom charset : 0123456789abcdef    >>>   Generated string: nd4ot3qk6i9ot344eqn5y4hcdq0nhm9n

I want the string only containing the characters 0123456789 and abcdef

[https://i.imgur.com/5hrn7Cd.png](url)

**Comment by openbullet** [comment]
If you want to use characters from the custom charset you have to use `?c` not `?n`. This is written in the documentation of the block if you read carefully.
