### ISSUE TITLE
[Bug]: 2Captcha GeeTest returns empty "successful" response

### ISSUE THREAD

**Issue by ShayMe21** [openbullet/OpenBullet2#687]
### Version of the software

0.2.3

### Operating system

MacOS 12.2.1

### Browser / Native

Chrome Version 100.0.4896.75 

### What happened?

I am using the 2captcha service to solve this GeeTest slider for fun: https://www.geetest.com/demo/slide-float.html
AFAIK, this is not GeeTest v4 because `captcha_id` parameter is not there as per guide 2captcha guide [here](https://2captcha.com/2captcha-api#geetest-v4).

I get a solution but it is always empty like this:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/14830205/162128600-35296b73-5539-4851-aaa4-aa4675fb7dad.png">

### Relevant LoliCode if needed

```shell
BLOCK:CurrentUnixTime
  => VAR @now
ENDBLOCK

BLOCK:HttpRequest
LABEL:Http Request - GeeTest challenge page
  url = $"https://www.geetest.com/demo/gt/register-slide?t=<now>"
  maxNumberOfRedirects = 7
  customHeaders = {}
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK

BLOCK:Parse
LABEL:Parse GeeTest Script - challenge
  input = @data.SOURCE
  attributeName = ""
  jToken = "challenge"
  multiLine = True
  MODE:Json
  => VAR @challenge
ENDBLOCK

BLOCK:Parse
LABEL:Parse GeeTest Script - gt
  input = @data.SOURCE
  attributeName = ""
  jToken = "gt"
  multiLine = True
  MODE:Json
  => VAR @gt
ENDBLOCK

BLOCK:SolveGeeTestCaptcha
  gt = @gt
  apiChallenge = @challenge
  apiServer = "apiv6.geetest.com"
  siteUrl = "https://www.geetest.com/demo/slide-float.html"
  => VAR @solveGeeTestCaptchaOutput
ENDBLOCK
```

**Comment by openbullet** [comment]
Hello, please open the issue on the CaptchaSharp repository (it's still maintained by me) since this is a CaptchaSharp issue https://github.com/openbullet/CaptchaSharp

**Comment by ShayMe21** [comment]
There you go: https://github.com/openbullet/CaptchaSharp/issues/16

**Comment by londek** [comment]
I made PR fixing this https://github.com/openbullet/CaptchaSharp/issues/20
