### ISSUE TITLE
bug? code

### ISSUE THREAD

**Issue by RydjGit** [openbullet/OpenBullet2#69]
I think there is a bug in UpdateService.CS 

`
// Try to read the current version from disk

            try
            {
                var content = File.ReadLines(versionFile).First();
                var version = Version.Parse(versionFile);`

that sould be :
`

            try
            {
                var content = File.ReadLines(versionFile).First();
                var version = Version.Parse(content);`

**Comment by openbullet** [comment]
Hey, nice find, thanks. Do you want to make a PR so you can appear as a contributor or do you want me to push the fix directly?

**Comment by RydjGit** [comment]
please push the fix directly I'm still browsing the code ... I see some enhacemnts and implemntations to be done ... you will see me make a pull request after that.

keep up the good work.
best regards.

**Comment by openbullet** [comment]
Done https://github.com/openbullet/OpenBullet2/commit/79ccbbeac775d345cc8b4adbe67d8d0fe998afdd thank you and I'm looking forward to the PRs!
