### ISSUE TITLE
[Bug]: Every time I download the software the .exe file doesn't want to work. 

### ISSUE THREAD

**Issue by SLIM3110** [openbullet/OpenBullet2#693]
### Version of the software

0.2.3

### Operating system

windows 11

### Browser / Native

Chrome

### What happened?

Every time I download the file, it doesn't want to open the app. I can share the file if needed. The system doesn't want to open. I download the file, Extract, refresh and then go into the file and it doesn't want to open the system.

**Comment by openbullet** [comment]
Did you install .NET 6? If you start the program via command line with `dotnet ./OpenBullet2.dll` then you will see the error message in the terminal. Please follow the installation guide step by step and you will have no issues.
