### ISSUE TITLE
[REQUEST] Display proxy group on jobs on the Jobs dashboard.

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#694]
Instead of displaying as Proxies: On, it would be very helpful if it shows the Proxy Group name instead of on. The Default and Off can stay as is. An example:
![chrome_87ZJZoKBzx](https://user-images.githubusercontent.com/87672015/164224572-99793f22-d3b7-4a14-bf7b-d0ba89777ff1.png)

**Comment by openbullet** [comment]
As there may be many proxy groups and other types of proxy sources too, it would become too cluttered
