### ISSUE TITLE
[REQUEST] How can i put Parse is retrieved by Recursive in the BLOCK HTTP REQUEST URL ?

### ISSUE THREAD

**Issue by jackmaokay** [openbullet/OpenBullet2#697]
I want to create a for loop
The word Parse is retrieved by Recursive with value = [list,forlist,newlist,oldlist,savelist]
now how can i put it in the BLOCK HTTP REQUEST URL ?
for example URL=link/< Parsevalue >/file.html
that it can run all the Parse that I took out earlier?

**Comment by openbullet** [comment]
Please refer to my answer on the forum, let's continue the discussion there. This is not a bug or feature request you just need some help so the forum is the best place to find it
https://discourse.openbullet.dev/t/download-save-img-to-folder/5722/5
