### ISSUE TITLE
[Bug]: only hitting for checking

### ISSUE THREAD

**Issue by BnadYY** [openbullet/OpenBullet2#698]
### Version of the software

0.2.3

### Operating system

Windows 10

### Browser / Native

Mozialla Firefox

### What happened?

If i start checking its only hitting for checking, it does not hitting bad or something only for checking, what can i do to fix this

**Comment by openbullet** [comment]
https://discourse.openbullet.dev/t/how-to-debug-ban-error-issues-in-a-job/3055
