### ISSUE TITLE
[BUG] OB2 Threads Problem on Linux

### ISSUE THREAD

**Issue by MaviReiz** [openbullet/OpenBullet2#70]
Sorry for my english first ,  this problem living on jobs page if i open five jobs cpu usage it will reach 100% , its normal. If i want to close jobs and click abort buttons sometimes not closing threads and cpu usage it stays stable because of it. If i click stop buttons not closing just holding. I have no choice but to abort button. This causes the error to occur

![Screenshot_8](https://user-images.githubusercontent.com/44947741/110857332-ce882b80-82c9-11eb-8f12-f7cf1fbddc03.png)

![Screenshot_9](https://user-images.githubusercontent.com/44947741/110857335-cf20c200-82c9-11eb-8d94-0d05246b06be.png)

**Comment by Rohan4412s** [comment]
yes same problem I m getting

**Comment by MaviReiz** [comment]
fixed
