### ISSUE TITLE
[REQUEST] Geetest post

### ISSUE THREAD

**Issue by golemsoft** [openbullet/OpenBullet2#700]
Hi, solved geetest, but when I add the answer in "geetest_challenge", "geetest_validate" and "geetest_seccode", it doesn't send with the form. Is there a function to call before the post?

**Comment by openbullet** [comment]
Hi, this heavily depends on the specific implementation in the website. I don't think I can help much without seeing the js code. Since this is not a bug with OB2 itself, please consider opening a thread on the forum instead of using github issues, thanks!
