### ISSUE TITLE
[Bug]: ipvanish proxy failing

### ISSUE THREAD

**Issue by vasudev123t** [openbullet/OpenBullet2#706]
### Version of the software

2

### Operating system

Windows 10

### Browser / Native

Chrome

### What happened?

ipvanish socks5 proxy are not working in OB2. USERNAME PASSWORD ARE ALL PROPER FOR THEIR WORKING.

**Comment by openbullet** [comment]
There are no known issues with importing socks5 proxies in OB2 you must be doing something wrong

**Comment by ZaryImortal** [comment]
no proxy is working for me
