### ISSUE TITLE
[REQUEST] Implement an API that communicates with OB2 based on incoming requests

### ISSUE THREAD

**Issue by AdaptCharm** [openbullet/OpenBullet2#707]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be much appreciated if you could implement an API that provides the option to share data and execute commands. Although the native and cross-platform web client does an excellent job at this, there are certain scenarios where you want the API to handle that.

For instance, currently it is only possible to start/stop a job manually through the GUI. What if you require this process to be automated? Or what if you have your own custom API and want that to control an OB2 job?

Below is the suggested API routes:
`/jobs/` - Get the status of all current jobs. Outputs the amount of hits, progress, cpm and status (idle/running)
`/jobs/:controls` - Start, pause or stop all the jobs by passing a parameter (start/pause/stop)
`/jobs/hits` - Get the hits data of all the jobs and output as json format
`/job/:id` - Get the status of a specific job. Same output as the `/jobs/` route
`/job/:id/:controls` - Start, pause or stop a specific job. Similar to the `/jobs/:controls` route
`/job/:id/hits` - Get the hits data of a specific job. Same output as the `/jobs/hits` route

~~`/jobs/create` - Creates a new job by providing the config, data pool, proxy source along with other props~~
Obviously, it should not be possible to create a new job through the API as this process is quite comprehensive and depends on a lot of factors. Nevertheless, if this route were to be added there is a chance that fewer people would use the jobs interface on the native/cross-platform web client, which is not what we want to achieve.

The API can also be extended further by adding more routes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by openbullet** [comment]
Hello, there is already an issue open about this and it's something I intend to address as soon as I have some time to work on OB2. Please copy this message and continue the discussion on this other issue https://github.com/openbullet/OpenBullet2/issues/572
