### ISSUE TITLE
[REQUEST] Openbullet Selenium Deactivate Headless Mode

### ISSUE THREAD

**Issue by Burningx2** [openbullet/OpenBullet2#710]
Cant find any way deactivate the headless mode of Selenium.
It would be nice if this will be possible in future release

**Comment by openbullet** [comment]
Config > Settings > Puppeteer > Untick "headless"
It should work for both Puppeteer and Selenium

![immagine](https://user-images.githubusercontent.com/48930622/165525505-1f6cb0d9-1081-48f2-9fba-79ea1bf38aca.png)

As for the keys you were asking about, there is a link to a list of key names in the block description of the `Key Press` block, just add the block and then look at the top, there will be a link.
