### ISSUE TITLE
[Bug]:  Openbullet2 is sending the wrong Ciphersuites

### ISSUE THREAD

**Issue by KawaCode** [openbullet/OpenBullet2#714]
### Version of the software

0.2.3

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Hey Ruri,

Openbullet2 is sending the wrong Ciphersuites, for SystemNet only. Rurilib doesn't work either.

SystemNet sends wrong Cipher suites;
Pic:
![image](https://user-images.githubusercontent.com/93525229/166128275-23d8a9b9-69e4-4cff-8c75-b0782e1e08ab.png)

Rurilib throwing error: 
![image](https://user-images.githubusercontent.com/93525229/166128384-c8365fe0-823b-4b29-a818-9242e8c9fb85.png)

**Comment by openbullet** [comment]
At the moment Cipher Suites with the `System.Net` library only work if you are using a `Socks` proxy. Can you please try with such proxy and let me know if that works? Thanks.

**Comment by openbullet** [comment]
Oh I just noticed you're using Windows. When on Windows, .NET uses SChannel as TLS provider instead of openssl so the cipher suites cannot be changed. You need to use macOS / Linux and install the latest openssl library, then try again.

**Comment by openbullet** [comment]
Implemented the above, now SystemNet on linux/macOS with openssl sends the correct cipher suites even with HTTP proxies or proxiless. Closing this, the discussion for RuriLib / Windows will continue here https://github.com/openbullet/OpenBullet2/issues/691
