### ISSUE TITLE
[REQUEST] TCP blocks with byte array inputs

### ISSUE THREAD

**Issue by Londek** [openbullet/OpenBullet2#716]
Hey, I'm unable to use TCP Blocks, because bytes -> ascii conversions that take place above charcode 127 are wrong. Above 127 most characters happen to be question marks.

I have tried different encodings in both OB2 and Node environment, but I couldn't find any that would magically not turn half of my bytes into question marks.

https://github.com/openbullet/OpenBullet2/blob/701e25c5f9bde89655bc0af732ab354fab2318a9/RuriLib/Blocks/Requests/Tcp/Methods.cs
TcpSendRead, TcpSend, TcpRead

I suggest adding TcpSendReadBytes, TcpSendBytes, TcpReadBytes or renaming current methods to TcpSendReadString, TcpSendString, TcpReadString and adding new.

If you are too lazy or I will have too much time, I will PR all changes.

Regards

**Comment by openbullet** [comment]
No worries I can add them right now

**Comment by openbullet** [comment]
Mind that I did not have time to test this so please do let me know if it's working, thanks!

**Comment by Londek** [comment]
It is working well, but I found a typo "Use U TF8" instead of "Use UTF8" checkbox.

**Comment by openbullet** [comment]
It's not a typo, it's the parameter name generator that does that, I didn't implement a custom parameter name attribute yet. It's something I plan on doing though, if you want feel free to open an issue about it.
