### ISSUE TITLE
[Bug]: Methods not shown

### ISSUE THREAD

**Issue by KawaCode** [openbullet/OpenBullet2#720]
### Version of the software

0.2.4

### Operating system

Kali Linux

### Browser / Native

Browser

### What happened?

Hey Ruri, I installed Openbullet 0.2.4 on Kali Linux, i cannot select any methods i used the latest version of Dotnet, i also tried it on Ubuntu from version 18 to 22 and other Plattforms same thing happend, i think there is a Bug in Openbullet 0.2.4 which weren't there in other previous versions.
Screenshot of bug:
![Screenshot from 2022-05-08 14-34-19](https://user-images.githubusercontent.com/93525229/167296667-18905f44-e7d9-4abb-b528-8d24786ae06a.png)

Edit: 
Its working fine for OpenBullet 0.2.3, the Bug is only there in 0.2.4

**Comment by openbullet** [comment]
Thanks for notifying me about it, I made a mistake when batch replacing some value in a file. Should be good now, try to rebuild from latest source code.
