### ISSUE TITLE
how to parse openbullet2 data.COOKIES as a variant?

### ISSUE THREAD

**Issue by hzmnet** [openbullet/OpenBullet2#721]
![image](https://user-images.githubusercontent.com/5361750/168046646-09ba2dc8-a6ae-461c-aa1b-8bcd8e3385b3.png)

but we received is below string:
` {(name,value),(name,value)}
`
what we want is browser type:
`name=value;name=value;`

how to pass this cookies to what we want?

**Comment by openbullet** [comment]
You have to use C# for this
```csharp
// Add 2 cookies to the cookies dictionary
data.COOKIES["name1"] = "value1";
data.COOKIES["name2"] = "value2";

// Merge the cookies into a single string in the Cookie header format
string cookieString = string.Join(";", data.COOKIES.Select(kvp => $"{kvp.Key}={kvp.Value}"));

// Log it to the bot log
LOG cookieString
```

**Comment by hzmnet** [comment]
thanks you it work now
