### ISSUE TITLE
Recursive Parse to have Fill String Value

### ISSUE THREAD

**Issue by CaptHigh** [openbullet/OpenBullet2#722]
Hey,
When using Recursive Parsing there is an issue that if the input list of strings doesn't have a variable it just skips to the next string in the list and checks. Can you please add a feature where if in the list of strings there isn't a matching variable it would use a Fillstring variable to fill its placeholder and output the same size of list as input 
Input:
Rawlist( ListOfStrings) = [{device=device1,_otheruselessdata_},{device=device2, Device_Model=ModelofDevice2, _otheruselessdata_}
Functions:
2 parsing functions are used, one parses device name and the other parses Model but every device doesn't necessarily have a model attribute so this screws up the final list 
Output:
devname (ListOfStrings) = [Device1, Device2]
devedition (ListOfStrings) = [ModelofDevice2]  
Final List
list (ListOfStrings) = [Device1|Device_ModelofDevice2  ,   Device2|NULL

**Comment by openbullet** [comment]
You can use the Zip function, it does exactly this.
