### ISSUE TITLE
[Bug]: Hit viewer not showing hits.

### ISSUE THREAD

**Issue by Enigma422** [openbullet/OpenBullet2#725]
### Version of the software

0.2.4

### Operating system

Windows 10

### Browser / Native

Chrome 100

### What happened?

This happens quite frequently when there is a lot of custom/to check hits, the hit viewer simply does not show any data and you have to scroll all the way down to view hits which at times the scroll bar just goes back up and it takes about 10 minutes for me to be able to view the hits. Its the most annoying thing in OB2 currently. This exists for atleast 3 months now.

**Comment by Enigma422** [comment]
Also it seems that one of the hit viewer height elements keeps on changing between 2 numbers all the time.

**Comment by Enigma422** [comment]
Changing width and height css code seems to fix this.

**Comment by RifHut** [comment]
![image](https://user-images.githubusercontent.com/51222371/169283930-5fb07129-14f6-4440-ac55-08d697572c7c.png)

just try to enable this option in your OB settings to view logs in your job section

**Comment by RifHut** [comment]
> Changing width and height css code seems to fix this.

i don't understand dude

**Comment by Enigma422** [comment]
> 

Bruh, i already have that enabled thats not what this issue is about.
When you run a job for a while and the job displays multiple tocheck, custom hits and what not the hit viewer bugs out and nothing is shown.

![image](https://user-images.githubusercontent.com/81516898/169310013-5a1ccbec-422c-41d5-a827-8177a4d291d3.png)

**Comment by Enigma422** [comment]
> > Changing width and height css code seems to fix this.
> 
> i don't understand dude

Once again this is a bug report, not a how to enable this or that question.

**Comment by openbullet** [comment]
I will definitely check this out, thanks. Does the CSS change you mentioned have any side effects (e.g. regarding the layout) or can it be implemented directly for everyone in the source of OB2?

**Comment by Enigma422** [comment]
There is side effects to this yes.
![image](https://user-images.githubusercontent.com/81516898/169662909-df6ce444-fa53-485f-8770-9196d773979d.png)

**Comment by Enigma422** [comment]
Oh and scrolling becomes a bit weird idk how to really explain it.

**Comment by leakguard** [comment]
Add this to your CSS as temporary fix:
`div.job-viewer-hits {
  height: auto;
}`

**Comment by openbullet** [comment]
Closing this as the new web client is completely remade from scratch and shouldn't have this issue
