### ISSUE TITLE
[Bug]: Problem with Post Data Content!

### ISSUE THREAD

**Issue by A1NTHATEASY** [openbullet/OpenBullet2#734]
### Version of the software

0.2.4

### Operating system

Windows

### Browser / Native

Native

### What happened?

While making a config I confronted this Error from the Post Data Content!

`[IDLE] CompilationErrorException: (80,786): error CS8076: Missing close delimiter '}' for interpolated expression started with '{'.`

![image](https://user-images.githubusercontent.com/96981727/170044021-d291bdf0-1a40-48b1-ae73-2c3a10f1687f.png)

Post Data Content:
`{"Header":{"context":{"_jsns":"urn:zimbra","userAgent":{"name":"ZimbraWebClient - GC101 (Win)","version":"8.8.15_GA_4059"},"session":{"_content":117383809,"id":117383809},"notify":{"seq":1},"account":{"_content":"<input.USER>","by":"name"}}},"Body":{"SendMsgRequest":{"_jsns":"urn:zimbraMail","suid":1653397949502,"m":{"id":"38534","did":"38534","idnt":"0e4ae929-796d-4aa7-bb3e-01191ca78867","e":[{"t":"t","a":"anyuser@test.net"},{"t":"f","a":"<input.USER>","p":"<input.USER>"}],"su":{"_content":"Test"},"mp":[{"ct":"multipart/alternative","mp":[{"ct":"text/plain","content":{"_content":"Test \n"}},{"ct":"text/html","content":{"_content":"<html><body><div style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12pt; color: #000000\"><div>Test</div></div></body></html>"}}]}]}}}}`

**Comment by openbullet** [comment]
I see the issue here. It's not the curly braces as you might think from the error, it's actually the XML because it makes OB2 think that there are variables (e.g. `<div>`) when there are not. There is no way to escape them at the moment. I suggest you put all the XML inside a separate variable and use that variable for the interpolation.

Make a constant string block WITHOUT interpolation (so dark grey background, not green) and put this inside
```
<html><body><div style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12pt; color: #000000\"><div>Test</div></div></body></html>
```
and then the post data becomes
```
{"Header":{"context":{"_jsns":"urn:zimbra","userAgent":{"name":"ZimbraWebClient - GC101 (Win)","version":"8.8.15_GA_4059"},"session":{"_content":117383809,"id":117383809},"notify":{"seq":1},"account":{"_content":"<input.USER>","by":"name"}}},"Body":{"SendMsgRequest":{"_jsns":"urn:zimbraMail","suid":1653397949502,"m":{"id":"38534","did":"38534","idnt":"0e4ae929-796d-4aa7-bb3e-01191ca78867","e":[{"t":"t","a":"anyuser@test.net"},{"t":"f","a":"<input.USER>","p":"<input.USER>"}],"su":{"_content":"Test"},"mp":[{"ct":"multipart/alternative","mp":[{"ct":"text/plain","content":{"_content":"Test \n"}},{"ct":"text/html","content":{"_content":"<html>"}}]}]}}}}
```
This should work without any issue.

**Comment by A1NTHATEASY** [comment]
By "dark grey background" you mean when the logo next to the string data is `T` right?
If yes then it did work perfectly. Thank you so much for that.

**Comment by openbullet** [comment]
Yes that's what I meant.
`T` symbol takes whatever you pass without doing anything to it
`</>` symbol will replace all `<these>` with variables, but will crash if they don't exist (it's not smart enough to know which variables exist at that point in time)
`VAR` symbol just takes the name of a single variable

**Comment by A1NTHATEASY** [comment]
Clear enough, I really appreciate your clarifying for this and I hope that this will be implemented in the future within the variable mode (dark green) so there will be no need to do such a procedure.
