### ISSUE TITLE
FingerPrint Plugin Or C# Code

### ISSUE THREAD

**Issue by kamirouni** [openbullet/OpenBullet2#739]
Please Guys Can Anyone Make a C# Who generate new fingerprint evry request I really need it

**Comment by kamirouni** [comment]
> E-mail me your telegram/discord to [generositytruth@gmx.com](mailto:generositytruth@gmx.com) I might be able to help with this

done i emailed u id u need drop telegram or discord here better

**Comment by openbullet** [comment]
This is not an issue with OB2, closing. Use the forum next time
