### ISSUE TITLE
[Bug]: OB2 process crash 

### ISSUE THREAD

**Issue by AdaptCharm** [openbullet/OpenBullet2#745]
### Version of the software

0.2.4

### Operating system

macOS Monterey v12.5 beta (21G5027d)

### Browser / Native

Chrome 102.0.5005.61

### What happened?

Created two jobs of the same config.

Attached below is a screenshot of the error messages that caused the OB2 instance to crash.
<img width="1339" alt="Skjermbilde 2022-06-21 kl  22 02 16" src="https://user-images.githubusercontent.com/17816720/174888329-f58b936b-f14e-43bf-9e8b-6abec4b1755b.png">

### Relevant LoliCode if needed

```shell
N/A
```

**Comment by openbullet** [comment]
Closing old issue, if you have a way to reliably replicate the issue, please reopen and provide more details. Thanks.
