### ISSUE TITLE
[REQUEST] Runner in Config editor

### ISSUE THREAD

**Issue by rockyd3vil** [openbullet/OpenBullet2#757]
for debugging code we need a runner in config editor when bot ends with retry or error then it should retry the code .

Just put tick for "looper" and bot status selector "retry" "error".

because of this we will know the conditions for keycheck. 
And if capmonster is returning wrong solution for few iterations so to catch the good captcha it help.

I hope you understand this and add this feature in next update . thank you

**Comment by openbullet** [comment]
You can already do all of this by using conditions/loops and keychecks. Also, if it fails once for temporary reasons, can't you just run it once again immediately after?

**Comment by rockyd3vil** [comment]
because of captcha I'm clicking start "start" 30-100 times to get captcha correct and to find the condition.

ok if can't add it. thank you

**Comment by openbullet** [comment]
Now I'm curious. What kind of captcha is it that you need 30 to 100 attempts to solve it? It sounds like a very bad way to spend your money (if you're using a captcha service, that is).

**Comment by rockyd3vil** [comment]
![image](https://user-images.githubusercontent.com/75754463/177205554-bb49a58c-bd87-49bc-94cc-4c6930278de3.png)

![image](https://user-images.githubusercontent.com/75754463/177205603-fbda6cd1-b0a4-451e-8e0b-ef9d8e6d6e66.png)

like this

that is why I said put a tick mark to run in a loop when retries. under the proxy box.

**Comment by openbullet** [comment]
Ok but why don't you loop directly inside the config itself? You can use LoliCode or C# to do a `while` loop and keep trying to solve the captcha until it's solved. Wouldn't that be better?
