### ISSUE TITLE
[Bug]: error 100 and 111

### ISSUE THREAD

**Issue by gabriel9010** [openbullet/OpenBullet2#758]
### Version of the software

0.2.4

### Operating system

kali linux 

### Browser / Native

chrome 

### What happened?

i have this problem please help me to fix ???

https://imgur.com/a/YZx1jSG this is image of the error

**Comment by openbullet** [comment]
Hi, can you give me more context on when this happened? Like, can you consistently reproduce the error? What are the steps to reproduce it / what were you doing when it happened?

It seems like it's having trouble rendering the MultiRunJobViewer page. Maybe try to download OB2 again? It might be corrupted.

**Comment by openbullet** [comment]
Closing stale issue
