### ISSUE TITLE
[Bug]: OpenBullet2.exe opens then closes immediately

### ISSUE THREAD

**Issue by ILayZee** [openbullet/OpenBullet2#759]
### Version of the software

0.2.4

### Operating system

Windows 11

### Browser / Native

Native

### What happened?

It opened for a split second then closed.

**Comment by KingBarker** [comment]
This happens to me also windows 11.

**Comment by ILayZee** [comment]
> This happens to me also windows 11.

Oh yeah did you download the app version or the browser version?
