### ISSUE TITLE
[BUG] Because puppeteer dont support socks5 auth proxy

### ISSUE THREAD

**Issue by amrmostafa800** [openbullet/OpenBullet2#76]
check this https://github.com/apify/proxy-chain
https://github.com/apify/proxy-chain/issues/69
i think you can fix issue with it
https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212

**Comment by openbullet** [comment]
This issue is already fixed, see https://github.com/openbullet/OpenBullet2/commit/af06485d3829e4813ef41e57d8988214079cf28b

**Comment by amrmostafa800** [comment]
not work i test the new 0.1.2 relase
ERR_TUNNEL_CONNECTION_FAILED

**Comment by openbullet** [comment]
We tested it ourselves with our own proxies and it worked. Please send me the proxy via PM on the forum and I'll check with your proxy to see what the issue is, otherwise I cannot replicate

**Comment by amrmostafa800** [comment]
ok

**Comment by amrmostafa800** [comment]
i send

**Comment by amrmostafa800** [comment]
when i try with domcontentloaded it work but Load not work
i send here Because cant send in forum
You’ve reached the maximum number of replies a new user can create on their first day. Please wait 5 hours before trying again.

**Comment by amrmostafa800** [comment]
it work but need 62711 ms
it very slow :D
