### ISSUE TITLE
[Bug]: [IDLE] CompilationErrorException: (15,121): error CS0103: The name 'USER' does not exist in the current context

### ISSUE THREAD

**Issue by brimmlessyankee** [openbullet/OpenBullet2#766]
### Version of the software

0.2.4

### Operating system

Windows 10

### Browser / Native

Chrome 103

### What happened?

No idea why this keeps happening/what it means, trying to use selenium and have entered <USER> to fill one of the fields, keep getting this message. 
![image](https://user-images.githubusercontent.com/71589193/179868275-20bbfdf8-01ce-48e9-a927-efe77b2e186f.png)

### Relevant LoliCode if needed

```shell
BLOCK:SeleniumOpenBrowser
ENDBLOCK

BLOCK:SeleniumNavigateTo
  url = "https://www.zalando.com/login/"
  timeout = 15000
ENDBLOCK

BLOCK:SeleniumWaitForElement
  findBy = XPath
  identifier = "//*[@id=\"login.email\"]"
  timeout = 10000
ENDBLOCK

BLOCK:SeleniumTypeElementHuman
LABEL:Type Human username
  findBy = XPath
  identifier = "//*[@id=\"login.email\"]"
  text = $"<USER>"
ENDBLOCK

BLOCK:SeleniumTypeElementHuman
LABEL:Type Human password
  findBy = XPath
  identifier = "//*[@id=\"login.secret\"]"
  text = $"<PASS>"
ENDBLOCK

BLOCK:SeleniumClick
LABEL:Click Login
  findBy = XPath
  identifier = "//*[@id=\"sso\"]/div/div[2]/main/div/div[2]/div/div/div/form/button"
ENDBLOCK

BLOCK:SeleniumGetDOM
  => VAR @seleniumGetDOMOutput
ENDBLOCK

BLOCK:Keycheck
  KEYCHAIN FAIL OR
    STRINGKEY @seleniumGetDOMOutput Contains "zds-icon"
ENDBLOCK
```

**Comment by maliktyhp** [comment]
Use <input.USER> & <input.PASS>

**Comment by brimmlessyankee** [comment]
Thanks a lot man, really helps, sadly two new issues have popped up

https://github.com/openbullet/OpenBullet2/issues/768
https://github.com/openbullet/OpenBullet2/issues/767

**Comment by angdn7** [comment]
do u successfully config ?
