### ISSUE TITLE
[BUG] OB2 Updater error

### ISSUE THREAD

**Issue by Reminem92** [openbullet/OpenBullet2#77]
Hi, i get an error when i try to update OB2 because there is a new update. 
I close the instance, close OB2 windows then i open Updater.exe and i get this error message : 

"[1/6] Fetching version info from remote... Failed! Accessed JArray values with invalid key value: "name". Int32 array index expected."

I can't update OB2.

Someone knows what to do in this case please ?

**Comment by openbullet** [comment]
Updater of 0.1.0 is broken, redownload 0.1.1 from scratch and then in the future it will work
