### ISSUE TITLE
Question about SolveCaptcha block

### ISSUE THREAD

**Issue by Aholicknight** [openbullet/OpenBullet2#786]
https://github.com/openbullet/OpenBullet2/blob/00fc6c18b18a755b95884c777d92f144ede1dae3/RuriLib/Legacy/Blocks/BlockSolveCaptcha.cs#L68

https://github.com/openbullet/OpenBullet2/blob/00fc6c18b18a755b95884c777d92f144ede1dae3/RuriLib/Legacy/Blocks/BlockSolveCaptcha.cs#L71

I am trying to figure out how to find the recaptcha site key and I can't find any documentation about this anywhere. On the site, the captcha window is invisible. 

![msedge_8953915229](https://user-images.githubusercontent.com/7843719/184515960-daa67bc2-2962-40be-ad59-00645885e44d.png)

Thank you for your help!

**Comment by openbullet** [comment]
Hello, usually the key starts with 6L and has underscores in it, so it looks like the `k` parameter in this case.

**Comment by Aholicknight** [comment]
Thank you for your reply @openbullet I will see if this works now.
