### ISSUE TITLE
[Bug]:always to check

### ISSUE THREAD

**Issue by zoro1s** [openbullet/OpenBullet2#789]
### Version of the software

0.2.4

### Operating system

windows11

### Browser / Native

brave

### What happened?

All the accounts go for to check , no failed , no hits
![image](https://user-images.githubusercontent.com/111541353/185506819-74b9365a-b7cb-405a-a018-66dd001c9348.png)

**Comment by openbullet** [comment]
This is an issue with your config in particular, not with OB2 itself. Please enable "bot log" in the RuriLib settings and then check the bot log of one of those hits, it will have information on why it ended with status `NONE` instead of FAIL / SUCCESS etc.

**Comment by jineurxd-hue** [comment]
to check
