### ISSUE TITLE
[BUG] getting high cpu usage and error every time.

### ISSUE THREAD

**Issue by Rohan4412s** [openbullet/OpenBullet2#79]
it also freezes and unable to click on any tab.

![wasdCapture](https://user-images.githubusercontent.com/53138230/110949353-823ff880-8368-11eb-9b3d-5820cf430b4d.PNG)
![wasCapture](https://user-images.githubusercontent.com/53138230/110949398-8ec45100-8368-11eb-8c99-ed94b2e62a11.PNG)
![2wswCapture](https://user-images.githubusercontent.com/53138230/110949421-93890500-8368-11eb-8ed0-c3c5a9751146.PNG)
![2sw2Capture](https://user-images.githubusercontent.com/53138230/110949439-98e64f80-8368-11eb-9add-225a85c5a247.PNG)

**Comment by openbullet** [comment]
Those errors don't matter at all, they can be disregarded as it's just some JS failing.
