### ISSUE TITLE
Fix plz ?

### ISSUE THREAD

**Issue by Khaledmohamed1988** [openbullet/OpenBullet2#791]
![2022_08_20_19_11_13_OpenBullet_2_0 2 4_Beta](https://user-images.githubusercontent.com/111654257/185796092-4c8f0ced-2a4b-402c-be95-f547800dd430.png)
![2022_08_21_16_29_35_HttpRequestException](https://user-images.githubusercontent.com/111654257/185796095-f31cd2ee-1853-4df0-8adc-92c6ddbfbda5.png)

**Comment by openbullet** [comment]
It is impossible to debug this without knowing the endpoint that you're calling. Please email me the website (you can find my email in the readme of this repository). Also, have you tried selecting `SystemNet` instead of `RuriLibHttp` as the HTTP library in the Http Request block parameters?

**Comment by Khaledmohamed1988** [comment]
Ok bro email sent to you with details thanks for caring and your time with efforts in advance

**Comment by openbullet** [comment]
Not an OB2 issue, closing
