### ISSUE TITLE
[Bug]: it wont open

### ISSUE THREAD

**Issue by valuefn** [openbullet/OpenBullet2#793]
### Version of the software

neweat version

### Operating system

windows 11

### Browser / Native

chrome

### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/84644902/185951423-61e967a2-432e-429d-b6df-c3a2f6c54434.png)

**Comment by DJHooligan** [comment]
have you tried http://0.0.0.0:5000 and http://127.0.0.1:5000 ?

**Comment by openbullet** [comment]
Can you sniff the request using the network tab (in the dev tools of your browser) and see if the server actually responds to the request with a 404? If it responds then the server is reachable, it just has trouble with the routing for some reason.

**Comment by Debruyne7** [comment]
I get this message whever I start the the run "Not supported Exception" the config does not support the provided wordlist type . 
please any explanations ?

**Comment by DJHooligan** [comment]
open that config , and then from the config menu, choose Settings, look for allowed wordlist types and add the type you need...
