### ISSUE TITLE
[Bug]: Why Console Box Don't Appear ?

### ISSUE THREAD

**Issue by davinci19213** [openbullet/OpenBullet2#796]
### Version of the software

2.4

### Operating system

ubuntu/Windows11

### Browser / Native

firefox, chrome

### What happened?

A bug happened!  Why the console BOX don't appear ?  See Link image, -> [HERE](https://ibb.co/MphPgv6)

DEBUG ERROR:

﻿
headManager.js:79 Uncaught SyntaxError: Unexpected token 'export'
loader.js:1320 Uncaught Error: Can only have one anonymous define call per script file
    at r.enqueueDefineAnonymousModule (loader.js:1320:23)
    at _ (loader.js:1807:27)
    at bootstrap.bundle.min.js:6:136
    at bootstrap.bundle.min.js:6:204
loader.js:1344 Duplicate definition of module 'vs/editor/editor.main.nls'
blazor.server.js:1 [2022-08-30T00:33:50.555Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:5000/_blazor'.
blazor.server.js:1 [2022-08-30T00:33:50.579Z] Information: WebSocket connected to ws://127.0.0.1:5000/_blazor?id=Ir2_cj4mm07wKe1l93fEdw.
Impossibile caricare la mappa di origine in DevTools: Impossibile caricare il contenuto per http://127.0.0.1:5000/js/bootstrap.bundle.min.js.map: Errore HTTP: codice di stato 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE.
Impossibile caricare la mappa di origine in DevTools: Impossibile caricare il contenuto per http://127.0.0.1:5000/js/popper.min.js.map: Errore HTTP: codice di stato 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE.
http://127.0.0.1:5000/js/popper.min.js.map

aught Error: Can only have one anonymous define call per script file
    at r.enqueueDefineAnonymousModule (loader.js:1320:23)
    at _ (loader.js:1807:27)
    at bootstrap.bundle.min.js:6:136
    at bootstrap.bundle.min.js:6:204
loader.js:1344 Duplicate definition of module 'vs/editor/editor.main.nls'
r.defineModule @ loader.js:1344
blazor.server.js:1 [2022-08-30T00:39:04.649Z] Information: Normalizing '_blazor' to 'http://0.0.0.0:5000/_blazor'.
blazor.server.js:1 [2022-08-30T00:39:04.689Z] Information: WebSocket connected to ws://0.0.0.0:5000/_blazor?id=rzRFBXfKo-JvId0VLI5snA.
### Relevant LoliCode if needed

FIREFOX DEBUG CONSOLE:

Error: Promised response from onMessage listener went out of scope [background.js:841:170](moz-extension://bc82ccf6-0198-4135-9b25-ef8c6ca755c1/dist/background.js)
Uncaught SyntaxError: export declarations may only appear at top level of a module [headManager.js:79](http://0.0.0.0:5000/_content/Microsoft.AspNetCore.Components.Web.Extensions/headManager.js)
Uncaught Error: Can only have one anonymous define call per script file
    enqueueDefineAnonymousModule loader.js:1320
    _ loader.js:1807
    <anonymous> bootstrap.bundle.min.js:6
    <anonymous> bootstrap.bundle.min.js:6
[loader.js:1320:22](http://0.0.0.0:5000/_content/BlazorMonaco/lib/monaco-editor/min-maps/vs/out-editor/vs/loader.js)
Duplicate definition of module 'vs/editor/editor.main.nls' [loader.js:1344:28](http://0.0.0.0:5000/_content/BlazorMonaco/lib/monaco-editor/min-maps/vs/out-editor/vs/loader.js)
[2022-08-30T01:08:39.685Z] Information: Normalizing '_blazor' to 'http://0.0.0.0:5000/_blazor'. [blazor.server.js:1:37158](http://0.0.0.0:5000/_framework/blazor.server.js)
Use of drawWindow method from CanvasRenderingContext2D is deprecated. Use tabs.captureTab extensions API instead https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab [pagedata-script.js:1:12465](moz-extension://d0554d27-c6ba-4cf6-8434-41b05092f6a4/content/pagedata-script.js)
[2022-08-30T01:08:39.774Z] Information: WebSocket connected to ws://0.0.0.0:5000/_blazor?id=S-AaHQa6BiprwjLHv0RiJQ. [blazor.server.js:1:37158](http://0.0.0.0:5000/_framework/blazor.server.js)
Error: Promised response from onMessage listener went out of scope 2 [background.js:841:170](moz-extension://bc82ccf6-0198-4135-9b25-ef8c6ca755c1/dist/background.js)
Source map error: Error: request failed with status 404
Resource URL: http://0.0.0.0:5000/js/bootstrap.bundle.min.js
Source Map URL: bootstrap.bundle.min.js.map

_No response_

**Comment by davinci19213** [comment]
SOLVED ,  WITH INSTALL FLARESOLVER now RUN and Maybe for now ALL GO FINE ! .. :X

**Comment by openbullet** [comment]
Did you download the precompiled version or did you try to compile it yourself?

**Comment by dyurnozz** [comment]
> Did you download the precompiled version or did you try to compile it yourself?

Yes i have downloaded the precompiled version from here :; https://github.com/openbullet/OpenBullet2/releases/tag/0.2.4

OpenBullet2.zip  for kali linux 22
and
OpenBullet2.Native.zip on W11

is the same issue problem for me.. have you an idea to get solve it? 

thanks

**Comment by openbullet** [comment]
The new web client will fix this, so I will close the issue for now. Please wait for the new release.
