### ISSUE TITLE
[Bug]: [Executing block ValidFormat] ArgumentException: The provided json is not a valid object or array

### ISSUE THREAD

**Issue by timolarra** [openbullet/OpenBullet2#798]
### Version of the software

0.2.4

### Operating system

Windows 10

### Browser / Native

Chrome 104.0.5112.102

### What happened?

When I get a JSON response with a whitespace above it, This error appears [Executing block ValidFormat] ArgumentException: The provided json is not a valid object or array.

I've tried the TRY / CATCH method but the Bot will stop work exactly at the Http Request Block (where I get the JSON response)

Could you please add a feature so we can disable this block"block ValidFormat" because the bot will stop working when this error appears.

**Comment by timolarra** [comment]
No, there is no block called ValidFormat, but I figured that out from the error message "[Executing block ValidFormat]"
And yes I've tried to change the HTTP library to SystemNet but still getting the same error
<img width="618" alt="Screenshot 2022-09-02 at 11 47 31" src="https://user-images.githubusercontent.com/40927202/188124343-ee2e3dd3-1f38-4673-aa79-0f7365e4a200.png">

**Comment by openbullet** [comment]
Are you using a parse block right after the http request? If that's the case, maybe try using the Trim block first to remove the extra whitespace.

**Comment by timolarra** [comment]
Even with 'safe mode' checked, the Bot stops immediately after the Request Block and this is the problem.

**Comment by openbullet** [comment]
This is really weird, can you check the LoliCode and see if you can find the word "ValidFormat" anywhere in the script? It makes absolutely no sense that it prints that.

**Comment by openbullet** [comment]
Closing stale issue
