### ISSUE TITLE
[BUG] Range Data Limits

### ISSUE THREAD

**Issue by aeruginascin** [openbullet/OpenBullet2#8]
**Describe the bug**
When using anything over a 9-digit number on the range data pool option, there is an error.

**Comment by openbullet** [comment]
https://github.com/openbullet/OpenBullet2/commit/e8a9b33a17162b5484f74645f31c481f1c6bbac8

**Comment by Laiteux** [comment]
> [e8a9b33](https://github.com/openbullet/OpenBullet2/commit/e8a9b33a17162b5484f74645f31c481f1c6bbac8)

You can include the issue # in the commit message in order to reference it 😉 Example: https://github.com/openbullet/OpenBullet2/commit/31927bda0701b33e0ef0f25a771dc742d7d5842c / https://github.com/openbullet/OpenBullet2/issues/10
