### ISSUE TITLE
[BUG] Can't read input password

### ISSUE THREAD

**Issue by elcracen** [openbullet/OpenBullet2#80]
[Executing block US] 'System.Dynamic.ExpandoObject' does not contain a definition for 'USERNAME'

Basically whenever i'm running this function to read input.USERNAME and urlencode it.

![image](https://user-images.githubusercontent.com/74982267/110955512-97556100-8341-11eb-813c-9b704f8f8da4.png)
![image](https://user-images.githubusercontent.com/74982267/110955540-9d4b4200-8341-11eb-823b-0c9f6138dadb.png)
I've been trying with the "default" wordlist type and this fake account justamail@gmail.com:201938aaj

**Comment by elcracen** [comment]
*Update*
input.USERNAME and input.PASSWORD is only working on credentials not sure what default is then

**Comment by openbullet** [comment]
Default wordlist type just takes all the line without splitting it and assign its value to `input.DATA`.
This guide should clear any doubts https://discourse.openbullet.dev/t/comprehensive-guide-to-wordlist-types/435

**Comment by rikyravi** [comment]
I obtain this error if I try to use input.VARIABLENAME where VARIABLENAME come from "parse" block, how can I solve that?

**Comment by openbullet** [comment]
> 
> 
> I obtain this error if I try to use input.VARIABLENAME where VARIABLENAME come from "parse" block, how can I solve that?

Just type `VARIABLENAME` do not type `input.VARIABLENAME`. The `input` is only for stuff coming from the wordlist data or from custom inputs.

**Comment by rikyravi** [comment]
WHILE INTKEY 1 LessThan 2
...
END

This is the description of the while function, if i have to run while VARIABLE is more than 0 how can I do that?

**Comment by rikyravi** [comment]
WHILE 0 LessThan <VARIABLE> ?

**Comment by rikyravi** [comment]
It's telling me this [IDLE] CompilationErrorException: (48,10): error CS1026: È previsto il segno )

**Comment by openbullet** [comment]
@rikyravi this is not a forum, these are github issues. Please use the forum for discussions if you don't know something about OB2 https://discourse.openbullet.dev
