### ISSUE TITLE
[Bug]:  Using '/root/.aspnet/DataProtection-Keys - HOW Solve this?

### ISSUE THREAD

**Issue by davinci19213** [openbullet/OpenBullet2#800]
### Version of the software

0.2.4

### Operating system

linux ubuntu

### Browser / Native

firefox, chrome

### What happened?

A bug happened! 

IN TERMINAL WHEN RUN OB2 i see this WARN,ERROR:
 
 info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[62]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.

how i can solve?

Thanks

**Comment by openbullet** [comment]
It's just a warning, you can safely disregard it if you're using OB2 locally. It only happens on Linux, you can find more information [here](https://stackoverflow.com/questions/52424618/what-is-this-asp-net-core-log-message-microsoft-aspnetcore-dataprotection-keyma)
