### ISSUE TITLE
[Bug]: Windows system 32 bit does not work the app

### ISSUE THREAD

**Issue by selo1212** [openbullet/OpenBullet2#802]
### Version of the software

0.2.3

### Operating system

windows 7

### Browser / Native

local

### What happened?

hello developer.my computer is 32 bit system and i can't run openbullet 2 native file and i need it how can i solve it. Will the program be compatible for 32 bit?

**Comment by openbullet** [comment]
Hello, OB2 is compatible with Windows 32 bit, please follow this guide to know how to start it on 32-bit systems.
https://discourse.openbullet.dev/t/how-to-download-and-start-openbullet-2/29
