### ISSUE TITLE
[Bug]: Cannot Use Computed hash in request or as a Constant String

### ISSUE THREAD

**Issue by fasuayn** [openbullet/OpenBullet2#803]
### Version of the software

0.2.4 Beta

### Operating system

Windows 10 Pro

### Browser / Native

Brave

### What happened?

I cant get the Computed hash value as a Constant String. I tried to use ''computed hash'' value directly in ''request Content'' but its not using, it just replacing it with ''System.Byte[]''

For recreating the issue

https://ghostbin.me/631aaadb43577

![Untitled](https://user-images.githubusercontent.com/113156181/189262842-f4ce8015-4ec5-47d5-a52d-6de6f18168ee.png)

### Relevant LoliCode if needed

```shell
BLOCK:CurrentUnixTime
  useUtc = True
  => VAR @ct
ENDBLOCK

BLOCK:ConstantString
  value = $"164b44444442315aa50751032fcaab02<ct>"
  => VAR @constantsCT
ENDBLOCK

BLOCK:Hash
  input = @constantsCT
  => VAR @authhash
ENDBLOCK

BLOCK:ConstantString
  value = $"<authhash>"
  => VAR @constantStringOutput
ENDBLOCK
```

**Comment by CyberParadise** [comment]
Try use 'Bytes => String' block

**Comment by openbullet** [comment]
If you're trying to hash a string and get a string as output, you need to use the `Hash String` block.
If you're trying to hash a hex string and get a hex string as output, you need to use the `Hex => Bytes` block, then the `Hash` block and finally the `Bytes => Hex` block on the output.

If you cannot figure it out and still need more assistance, please post the input and output you desire and I will write you the code.
