### ISSUE TITLE
Please add "Ignore Response Errors" option or solve this issue

### ISSUE THREAD

**Issue by MajedurFahim** [openbullet/OpenBullet2#811]
There was a ### "Ignore Response Errors" option in prior versions of openbullet.

![ScreenShot_20220925025706](https://user-images.githubusercontent.com/80979723/192118593-b2d4932b-3cd7-47ab-b601-efbd57d2e443.png)
However, in openbullet 2, there is no such option. When the bot receives an error response, there is no way to skip it and it will retry continuously. I put Error in **"Statuses for which the bot continues/stops"** but it doesn't work. I encountered this issue more frequently when creating ### IMAP/SMTP configurations. When the IMAP/SMTP configuration receives a **"invalid login" AuthenticationExpection error**, it will not proceed to the next Keycheck block to change the status fail or retry, and the multi runner will receive an endless error response.

It would be really helpful to know if there is a way to ignore response errors and set the status as retry or fail. Alternatively, please include an option to "Ignore Response Errors" . I've been dealing with this issue for more than a year.
![ScreenShot_20220925025746](https://user-images.githubusercontent.com/80979723/192118591-44427635-7dcf-4643-a46d-387e3d552303.png)
![ScreenShot_20220925025609](https://user-images.githubusercontent.com/80979723/192118594-a49cb95e-b219-45b9-b683-4b3d81d0374a.png)

**Comment by CyberParadise** [comment]
You can use 'Safe mode'
![изображение](https://user-images.githubusercontent.com/110465792/193164883-921ed8b8-09ad-4828-9409-6e82c4369e34.png)

then use `IF STRINGKEY @data.ERROR Contains "Authentication failed"`

**Comment by ahmedyahiaa50** [comment]
![image](https://user-images.githubusercontent.com/43252100/209996199-711153da-edf2-438f-a56f-e21cb9f4cc38.png)
how can i add the key!
