### ISSUE TITLE
[REQUEST] Automatically stop a job when internet goes off

### ISSUE THREAD

**Issue by BobaKush** [openbullet/OpenBullet2#815]
**Is your feature request related to a problem? Please describe.**
When internet goes off while running a job, all combos turned into tocheck.

**Describe the solution you'd like**
I think a good solution would be to automatically stop a job when there's no available internet connection

**Describe alternatives you've considered**
idk honestly

**Additional context**
Love your works Ruri

**Comment by RifHut** [comment]
I will share with you a crazy trick!
as you know, when there's no available internet connection, running bots goes to retry, right ?
Try this example, to understand all: 
![image](https://user-images.githubusercontent.com/51222371/198838616-8761d21b-b53b-4b2f-8444-1f3e4d235953.png)

**Comment by openbullet** [comment]
I would like to add that Retries EqualTo 10 is very dangerous as they could go from 9 to 11 directly and the job would never stop. So it's better to use GreaterThan. Read more information here https://docs.openbullet.dev/docs/jobs/job-monitor/
