### ISSUE TITLE
Custom Constant String Plugin

### ISSUE THREAD

**Issue by arshambh** [openbullet/OpenBullet2#821]
Hi 
I want to write customize plugin for  "Constant String"  and i follow this guide [OB2PluginSample]( https://github.com/openbullet/OB2PluginSample) but i can`t save my value to "VAR" !!!!
is there any sample plugin that save result "VAR" as like as  Constant String Function?
thanks in advance

**Comment by openbullet** [comment]
You just have to return the value from your block method, like
```cs
[Block(...)]
public string MyConstantString(BotData data)
{
  return "hello";
}
```
