### ISSUE TITLE
[Bug]: Can't pass port 80 via HTTPS on request block

### ISSUE THREAD

**Issue by puma7dragon** [openbullet/OpenBullet2#822]
### Version of the software

0.2.4

### Operating system

Linux

### Browser / Native

Browser

### What happened?

ProxyExecption: Failed SSL Connect
When specify port 80 on a https request, above error happens.
Example: https://YourIPAddressHere:80
It works just fine with any other port and on the Native Client as well (Tested on windows)

Happens only to the Browser version.

Please test below Lolicode to reproduce (Fake IP in code below)

### Relevant LoliCode if needed

```shell
BLOCK:HttpRequest
LABEL:X-Token
  url = $"https://125.15.15.15:80"
  maxNumberOfRedirects = 1
  urlEncodeContent = True
  alwaysSendContent = True
  timeoutMilliseconds = 5000
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK
```

**Comment by RifHut** [comment]
sometimes not working, due to firewall , try add ob2 in firewall (inbound and outbount rules), also check this url on tested machine.
