### ISSUE TITLE
Noob here with Unraid. How to connect to browser?

### ISSUE THREAD

**Issue by jferris-** [openbullet/OpenBullet2#825]
Apologies but I can't see how to get this working. I've the Openbullet Docker up and running on my Unraid machine just fine. I see there was two tutorial videos but they've both been pulled.

I can't figure how I link this to a browser?
I've setup a Puppeteer headless browser docker which offers a IP:PORT to connect to, but Openbullet only has the option to give the directory of a Chrome/Firefox executable? 

Please advise.

**Comment by RifHut** [comment]
what is your OS ? linux or windows ?

**Comment by jferris-** [comment]
> what is your OS ? linux or windows ?

Linux

**Comment by openbullet** [comment]
Please launch the docker container with the command written in this guide https://discourse.openbullet.dev/t/how-to-download-and-start-openbullet-2/29

This command will map the port inside the volume to a port on the host so you can access the OB2 web interface via your normal browser.

**Comment by jferris-** [comment]
> Please launch the docker container with the command written in this guide https://discourse.openbullet.dev/t/how-to-download-and-start-openbullet-2/29
> 
> This command will map the port inside the volume to a port on the host so you can access the OB2 web interface via your normal browser.

These are the details to reach the UI. My question is about how do I connect to the non-existent puppeteer browser.

**Comment by openbullet** [comment]
Sorry for the misunderstanding.
OB2 spawns its own headless firefox browser (bundled inside the docker image) to control with Puppeteer, it is not able to connect to a remote browser. I suggest you use the default browser, the path to the executable in docker is `/usr/bin/firefox`.
