### ISSUE TITLE
[BUG] Тheme is switch back to default on every Update

### ISSUE THREAD

**Issue by mastercho** [openbullet/OpenBullet2#83]
**Describe the bug**
Once we update OB2 to latest trough updater.exe theme i reset to default
**To Reproduce**
1. Close OB2
2. Run Updater.exe
3. Open OB2 again

**Expected behavior**
To keep settings for theme

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser Chrome
 - Version 88

**Comment by openbullet** [comment]
Fixed https://github.com/openbullet/OpenBullet2/commit/2519863af0e5cbd263042ec58bfba2c6e232e069
