### ISSUE TITLE
Adding AYCD AutoSolver

### ISSUE THREAD

**Issue by adamsmithx00** [openbullet/OpenBullet2#834]
### **Hi ruri, can I suggest u to add AYCD AutoSolver support on captcha blocks? it is one of the best solver and it would be useful.
thanks**

**Comment by openbullet** [comment]
I can definitely add this but I need an account and I do not plan on paying for it myself.

**Comment by adamsmithx00** [comment]
> I can definitely add this but I need an account and I do not plan on paying for it myself. Also please open a new issue in the https://github.com/openbullet/CaptchaSharp repository which is where I implement captcha-related things.

could you please contact me : adamsmithx00@gmail.com
