### ISSUE TITLE
[Bug]: how do i add identity token at end of url?

### ISSUE THREAD

**Issue by cooperskickz** [openbullet/OpenBullet2#837]
### Version of the software

0.2.5

### Operating system

windows 7

### Browser / Native

brower

### What happened?

im looking to see if theres a way to retrieve the url identity token.. ill provide an example. but first when i put the url without the token at the end for example: example.com/identity/login it comes with an error saying "access denied" it also does this with the token which was generated on the original website when retrieving the data for the config. I am still learning and any help would be appreciated.

example of identity token: example.com/identity/login?signin=<token>

any help with this issue would be highly appreciated!

### Relevant LoliCode if needed

```shell
BLOCK:HttpRequest
  url = "https://my.asos.com/identity/login"
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK
```

**Comment by openbullet** [comment]
Once you parse the token from a response, you can send it like this

```
BLOCK:HttpRequest
  url = $"https://my.asos.com/identity/login?signin=<TOKEN>"
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK
```

Sadly I cannot provide any help on actually getting the token in the first place.
