### ISSUE TITLE
[Bug]: Proxy database update error after delete not working proxy

### ISSUE THREAD

**Issue by tntd2k2** [openbullet/OpenBullet2#839]
### Version of the software

0.2.5

### Operating system

Windows 10 (Native), Ubuntu 20.04 (WebApp)

### Browser / Native

Both

### What happened?

This happens when delete Not Working proxy during Proxy Check task.
=> Proxy DB wont update anymore
=> This error occurs in version 0.2.5
![Bug](https://i.imgur.com/3oysv7T.png)
[screen-capture.webm](https://user-images.githubusercontent.com/47687492/210599149-6fc70d16-0c16-4342-b0f5-78ee74dbdf14.webm)

**Comment by openbullet** [comment]
This has been fixed in 0.3.0
