### ISSUE TITLE
[REQUEST] Debug Mode Close Button

### ISSUE THREAD

**Issue by MaviReiz** [openbullet/OpenBullet2#84]
It would be nice to add a way to turn off console logs

![image](https://user-images.githubusercontent.com/44947741/110995549-96492180-838b-11eb-816c-87f961aa3dec.png)

**Comment by openbullet** [comment]
Exceptions in the console log are important to see, so those are going to stay, while I made a "verbose mode" button for all those BANs that you see while running a job, I added it here https://github.com/openbullet/OpenBullet2/commit/e32b61895b70d62ad37c2ba2a308345ee9582ac5
