### ISSUE TITLE
[Bug]: Not checking only to check

### ISSUE THREAD

**Issue by Sh4r3catyt** [openbullet/OpenBullet2#845]
### Version of the software

0.2.5

### Operating system

10

### Browser / Native

Chrome

### What happened?

![grafik](https://user-images.githubusercontent.com/77161107/211947243-2951821d-6216-416f-8b0d-3b3e87aec56c.png)

not checked a single acc tried multiple cfgs + proxie

### Relevant LoliCode if needed

```shell
any config all not work
```

**Comment by openbullet** [comment]
This is not an issue with OB2 itself, it must be an issue with your configs or with the environment. Please debug using this guide https://discourse.openbullet.dev/t/how-to-debug-ban-error-issues-in-a-job/

**Comment by Sh4r3catyt** [comment]
I used multiple configs ...

**Comment by openbullet** [comment]
It does not matter, you need to follow the guide and debug the issue. It is probably an issue across all configs.
