### ISSUE TITLE
[Bug]: Why does this refresh happen

### ISSUE THREAD

**Issue by motikolorado** [openbullet/OpenBullet2#850]
### Version of the software

latest

### Operating system

linux

### Browser / Native

browser

### What happened?

The page always refresh after about 2-20 minutes and this cuts any ongoing upload and if i leave a job running, it stops after about an hour and i have to setup again like first time use uploading all my configs and wordlists.
<img width="1440" alt="Screenshot 2023-01-16 at 1 43 33 AM" src="https://user-images.githubusercontent.com/83591079/212636854-4879b675-e231-419f-ab51-d34693a4dfda.png">

**Comment by openbullet** [comment]
This is an app policy of your specific hosting provider and not a bug of OB2 itself. Host it on an EC2 on AWS they have a free plan. Otherwise look into the new Oracle Cloud, they also have a free plan.
