### ISSUE TITLE
[REQUEST] file editor

### ISSUE THREAD

**Issue by motikolorado** [openbullet/OpenBullet2#852]
This is kinda like the proxies upload where you can just paste proxies but for the wordlist so that users can edit wordlists by just copy paste and save. This cuts the time of uploading large files.

**Comment by openbullet** [comment]
I don't see how this will cut the time to upload large files, if you still need to send the data from your browser to the server, just in a different (less efficient) way. Why don't you use `scp` to copy everything you need to the server from your PC instead?

**Comment by motikolorado** [comment]
I am running heroku instance so please explain how i can use this `scp`

**Comment by openbullet** [comment]
Ah nevermind, heroku machines seem to be firewalled, so you cannot use `scp`. I suggest you switch to something like AWS, they have a free tier where you can use a t2.micro instance for free. You will need to hook up a credit card though.
