### ISSUE TITLE
[REQUEST] Implement solvecaptcha.net captcha solver

### ISSUE THREAD

**Issue by shemz14** [openbullet/OpenBullet2#853]
can you add this on captchas website https://solvecaptcha.net/ for the next patch i think the solvecaptcha on the pic is https://solvecaptcha.com/ not /net so can you add this https://solvecaptcha.net/  i need this please thank you
![image](https://user-images.githubusercontent.com/122832447/212764281-1a2ac04f-d19f-43d6-897f-1fd3ccbf8761.png)

**Comment by openbullet** [comment]
Please open an issue on the CaptchaSharp repository as that is where it needs to be implemented first.

**Comment by shemz14** [comment]
how can i open this .dll what software to use 
![image](https://user-images.githubusercontent.com/122832447/212830040-d0e46839-d080-4184-8b36-4e173b5e53ad.png)

**Comment by shemz14** [comment]
i dont know how to add this captcha plss help me owner

**Comment by shemz14** [comment]
displaying like this 
![image](https://user-images.githubusercontent.com/122832447/212832672-78d70694-ab31-47ad-94eb-42cdbe53685a.png)

**Comment by openbullet** [comment]
I mean that you have to open another issue here https://github.com/openbullet/CaptchaSharp
