### ISSUE TITLE
Archivos se pasaron por escaneo de Antimalware

### ISSUE THREAD

**Issue by loladante501** [openbullet/OpenBullet2#855]
**Openbullet2.zip**

🧬 Detecciones: 1 / 65

⛔️ Antiy-AVL
  ╰ Virus/Win32.Nimnul

------------------------------------------------------------

**OpenBullet2.native.zip**

_No se encontró malware_

------------------------------------------------------------

**OpenBullet2.console.zip**

🧬 Detecciones: 1 / 57

⛔️ MaxSecure
  ╰ Trojan.Malware.300983.susgen
------------------------------------------------------------

**Patch.zip**

_No se encontró malware_

**Comment by openbullet** [comment]
There are no viruses, don't worry, it's a false positive. Anyways, the code is open source, you can read it and compile your own build if you don't trust the precompiled one, the instructions are on the forum.
