### ISSUE TITLE
[Bug]: AES Decryption not working - IV Error

### ISSUE THREAD

**Issue by Spyderzz** [openbullet/OpenBullet2#858]
### Version of the software

0.2.5 

### Operating system

Windows 11

### Browser / Native

Native

### What happened?

I was going through AES Decryption in OB2, I tried with a working Key and IV but idk it’s showing the error “**CryptographicException: Specified initialization vector (IV) does not match the block size for this algorithm.**”

I tried to decrypt the same Cipher Text with the KEY & IV on an [online website](https://www.devglan.com/online-tools/aes-encryption-decryption) and it just worked fine.
I have posted this Issue on the Forum too, [Check here](https://discourse.openbullet.dev/t/aes-decrypt-iv-error/6808) .
![Screenshot (65)](https://user-images.githubusercontent.com/50264910/213702378-f9fb7870-78e5-4ca3-ab8e-090662d3464c.png)

![Screenshot (67)](https://user-images.githubusercontent.com/50264910/213702389-e2a11c95-04eb-4a65-a452-a700f32f1311.png)

### Relevant LoliCode if needed

```shell
BLOCK:AESDecryptString
  cipherText = Pe+vf4/XZl4T05XQ5XNxoq8bM/Kv2s7el1exSdnzEdHMWYM1Lb+CL2gWI1rperSY4TzKemUa/cZrhbXv15m8Wm6XWyPfqKngEu+wptW6lOPkNUK01xduBwfHuBSRuxs+jkB26SjJbqVgnTaMOvAey9/RQw3L4aLti0A/0RXah8E=
  key = x3UJQeY2ift0AaCH7e7hQYvQyhOtpt87
  iv = gpR6JLD2qpDD406l
  => VAR @aESDecryptStringOutput
ENDBLOCK
```

**Comment by openbullet** [comment]
If you compute the base64 of `gpR6JLD2qpDD406l` and use that instead, it will work properly.
