### ISSUE TITLE
[REQUEST] Stop all bots on command

### ISSUE THREAD

**Issue by hinderobjects** [openbullet/OpenBullet2#863]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the ability to stop all bots when a specific block or code is executed, like a 'Stop' command to stop that individual bot or 'StopAllBots'
For example, you have one bot that returns SUCCESS. At this point, the bots are no longer needed and can be stopped. This would be convenient if you are not or can not necessarily watch the job at all times.

**Describe alternatives you've considered**
I don't believe there is a proper alternative at this time

**Additional context**
I have seen this feature requested previously on the forums

**Comment by openbullet** [comment]
If you want to stop the job after it gets a single hit, there is a way to do this through the job monitor. Please read the documentation here https://docs.openbullet.dev/docs/jobs/job-monitor

Also, with the new web client, there will be an API you can call to stop or abort the job from within the script of the config.
