### ISSUE TITLE
[Bug]: ConstantString / error CS1010: Newline in constant

### ISSUE THREAD

**Issue by APT-ZERO** [openbullet/OpenBullet2#876]
### Version of the software

0.2.4

### Operating system

Windows 10

### Browser / Native

Chrome

### What happened?

A bug happened!

`[IDLE] CompilationErrorException: (3,64): error CS1010: Newline in constant`

### Relevant LoliCode if needed

```shell
BLOCK:ConstantString
  value = $"a\n`]\nd\n[e]"
  => VAR @constantStringOutput
ENDBLOCK
```

**Comment by openbullet** [comment]
Hello, thanks for pointing out the bug. I just wanted to say that without the interpolated mode (a.k.a. the leading `$`) it works as intended. I will have to look into this.

**Comment by onisoc** [comment]
Use `\\n` instead `\n` then it could be fixed.
