### ISSUE TITLE
[Bug]:  Problem with importing a proxy file!

### ISSUE THREAD

**Issue by A1NTHATEASY** [openbullet/OpenBullet2#878]
### Version of the software

0.2.5

### Operating system

Windows

### Browser / Native

Native

### What happened?

A bug happened!

[https://discourse.openbullet.dev/t/problem-with-importing-a-proxy-file/6715?u=ainthateasy](url)

**Comment by openbullet** [comment]
https://github.com/openbullet/OpenBullet2/issues/872
