### ISSUE TITLE
[Bug]: Windows 11: No way to change Proxy Checker from Google

### ISSUE THREAD

**Issue by frozen905** [openbullet/OpenBullet2#880]
### Version of the software

latest

### Operating system

Win11

### Browser / Native

Chrome latest

### What happened?

Cannot change the proxy check from the only selection, which is Google.com and built in Title.

I want to change to a different server, and page title. 

https://i.imgur.com/UGsJaWR.png

Edit - also is not changeable within the job screen, only the bot count. I don't want to use Google.com !

https://imgur.com/a/jKUk6i5

**Comment by openbullet** [comment]
Hello, on the old web client you can configure your proxy check targets in the OB2 Settings page. With the new web client, this can be also changed directly from the job options.
