### ISSUE TITLE
[Bug]: webserver with custom port

### ISSUE THREAD

**Issue by APT-ZERO** [openbullet/OpenBullet2#886]
### Version of the software

0.2.4 / 0.2.5

### Operating system

Windows 10

### Browser / Native

ANY Browser

### What happened?

A bug happened!
I tried to post/get a webserver with port 3333
idk why, but when im using browser client of OB2 it will give me this error, on both http libraries
`[SAFE MODE] Exception caught and saved to data.ERROR: System.Threading.Tasks.TaskCanceledException: A task was canceled.`
But the same config works on native with no problem on both http libraries!
idk what is the problem, it's really weird

**Comment by openbullet** [comment]
I would need to have an example webserver to properly test and debug this.
