### ISSUE TITLE
You must install or update .NET to run this application error.

### ISSUE THREAD

**Issue by adepauldami** [openbullet/OpenBullet2#893]
![Screenshot at 2023-05-22 04-17-58](https://github.com/openbullet/OpenBullet2/assets/70479594/4f61fb2c-8e66-4561-a577-88c03c9c4968)

### I kept getting the following issue even after successfully installing dotnet version 7, I do see the version using dotnet --version command:

_dotnet ./OpenBullet2.dll
You must install or update .NET to run this application.

App: /home/flutterdev/Documents/dev/OpenBullet/OpenBullet2.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=parrot.5.3-x64_

**Comment by DarkScripted** [comment]
.NET runtimes are not backwards compatible, so you'll need to install .NET **6.0** in order to run OpenBullet, as the latest release was built with that version.
As it looks like you are using Linux, you can search how to install that specific version with your distro's package manager.
