### ISSUE TITLE
[Bug]: Windows 11:  RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition 'x'

### ISSUE THREAD

**Issue by frozen905** [openbullet/OpenBullet2#895]
### Version of the software

0.2.5 [Beta]

### Operating system

Windows 11

### Browser / Native

Edge

### What happened?

Hello there, on a fresh install on the latest Windows 11 build I am encountering this error when trying to debug things, or run any scripts even.

RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition 'X' where X is the type

I have uninstalled and reinstalled .net 6.0 , i can't figure out what the problem is

**Comment by RicherRoss** [comment]
Also having this issue

**Comment by openbullet** [comment]
Please have a look at the documentation on wordlists. You're most likely using the wrong wordlist type (e.g. if your wordlists has only the `DATA` slice, you can't use `input.USER` as it doesn't exist, and that's the error you would see).

https://docs.openbullet.dev/docs/wordlists/general-info
