### ISSUE TITLE
How to host web client as website not in local host

### ISSUE THREAD

**Issue by Yourdadbro** [openbullet/OpenBullet2#896]
### Version of the software

Nill

### Operating system

Nill

### Browser / Native

Nilll

### What happened?

How to host web client as website not in local host

**Comment by openbullet** [comment]
Use the OB2 docker (check [this post](https://discourse.openbullet.dev/t/how-to-download-and-start-openbullet-2/29)) and just follow any guide that shows you how to set up a linux server to host a website. You will need a domain, a server, apache/nginx as reverse proxy flipping your traffic to your docker container, and a TLS certificate (use certbot). You can find all of this information online.
