### ISSUE TITLE
[BUG] Config deletion crashes the interface

### ISSUE THREAD

**Issue by HypeMaxers** [openbullet/OpenBullet2#9]
**Describe the bug**
When you create a job and add the config , whenever you delete that config the interface would break and I have to restart it,

**To Reproduce**
1. Create a job with a config
2. Delete the config
3. Navigate to "jobs"

**Expected behavior**
I expect the program to be able to update the runner or anything that prevents this crash.

**Screenshots**
https://gyazo.com/collections/da3eff1f64c566095480fa9547ffb1e8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.1.0

**Comment by Laiteux** [comment]
Thanks for the report!

@openbullet When deleting the config, should we check if an existing job is using it, and if so move the config to a temp folder while the job exists... or should we simply delete the job?

**Comment by HypeMaxers** [comment]
Little note the job wasn't running it just crashed as soon as I deleted the config

**Comment by openbullet** [comment]
@Laiteux the user might delete the file directly, causing the same issue, so it's better to just make the job throw errors at the screen instead of crashing the entire program directly

**Comment by openbullet** [comment]
Cannot replicate this anymore, seems to be fixed now.
