### ISSUE TITLE
OB2 Native crashes when selecting cmd.exe

### ISSUE THREAD

**Issue by TestDeTuring** [openbullet/OpenBullet2#903]
### Version of the software

0.2.5

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Whenever I try to open with a shell command my cmd or powershell, OB2 crashes.

### Relevant LoliCode if needed

```shell
BLOCK:ShellCommand
LABEL:Shell
  executable = "C:\\WINDOWS\\system32\\cmd.exe"
  => VAR @shellCommandOutput
ENDBLOCK
```

**Comment by openbullet** [comment]
Tried and works if you just type `cmd` or `powershell`. Note that the block waits for the command to return (a.k.a. it waits for you to close the terminal window) so you should pass some arguments to execute something and then return, otherwise it will hang there.
