### ISSUE TITLE
No UserPass or MailPass

### ISSUE THREAD

**Issue by pusheensec** [openbullet/OpenBullet2#907]
when uploading or editing a wordlist, im only given the options of 

```
Default
Emails
Credentials
Numeric
Urls
```

even in the settings for a config, MailPass and UserPass show up as 2 thin empty boxes (screenshot)
![dataOB2](https://github.com/openbullet/OpenBullet2/assets/139312866/c0d80cf9-5cd5-41cf-82ca-0bd629f25a8d)

could this be a issue with my installation?

**Comment by a9eesh** [comment]
Edit config to use Credentials than MailPass, its the same
