### ISSUE TITLE
[Question]: Parse From tcp or imap

### ISSUE THREAD

**Issue by agx47** [openbullet/OpenBullet2#912]
### Version of the software

2

### Operating system

windows 10

### Browser / Native

Native

### What happened?

Hey, I'm sorry, but this is not a bug; it's just a question. 
I'm new to GitHub, and I don't know where to put my question. Anyways, 
I just want to know how to parse the selected response from a TCP or an IMAP. I'm not sure how. Can you help? (I'm a noob)"

![Untitled](https://github.com/openbullet/OpenBullet2/assets/117392387/680ce5be-5aa8-4880-ad1e-8430d7256cc4)

**Comment by openbullet** [comment]
You can't really parse anything from it, but you can make it a SAFE block, and any errors will be written to `data.ERROR`. So if `data.ERROR` is empty it means it was successful. If you're using a `TcpConnect` block, then you already know the host and port so why would you want to parse them?
