### ISSUE TITLE
[Bug]: Unhandled exception thrown on 17/8/2023 5:50:13 μμ System.IO.FileNotFoundException: Could not load file or assembly 'CaptchaSharp, Version=1.0.11.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by veritas1945-byte** [openbullet/OpenBullet2#917]
### Version of the software

0.2.4

### Operating system

windows 11

### Browser / Native

Chrome

### What happened?

Unhandled exception thrown on 17/8/2023 5:50:13 μμ
System.IO.FileNotFoundException: Could not load file or assembly 'CaptchaSharp, Version=1.0.11.0, Culture=neutral, PublicKeyToken=null'.

**Comment by openbullet** [comment]
Seems like it's not finding a DLL it needs. Redownload OB2 (back up your UserData folder so you won't lose anything). Also make sure your antivirus isn't removing any files. The code is all open source, so it that happens it's a false positive.
