### ISSUE TITLE
[Bug]: Selenium issue with latest chrome version

### ISSUE THREAD

**Issue by slashhesham** [openbullet/OpenBullet2#918]
### Version of the software

0.2.5

### Operating system

macOS Monterey

### Browser / Native

FireFox

### What happened?

**Describe the bug**
Starting Chrome version 115, Google has stopped using Chromedriver and started using 'Google Chrome for Testing', I've downloaded the corresponding version that matches my chrome version and added the correct path in RL settings.
but I keep getting an exception when I run any selenium block: 
```
InvalidOperationException This version of chromedriver only supports chrome version 114 current browser version is 115.0.58456
```
I'm 100% sure that I have the right version and I can use it with selenium for Python successfully.

Note: 
I was facing the same issue with Selenium for python and it didn't work till I updated selenium to the latest version. so I guess OB2 needs to be updated with the latest selenium version 

**To Reproduce**
1. Go to https://googlechromelabs.github.io/chrome-for-testing/ and download the latest chrome for testing version & download the latest chrome version
2. update the executable path in RL settings
3. start a new config with one block of  Selenium open browser

**Expected behavior**
A browser window to open

**Version**
 - 0.2.5

**Comment by openbullet** [comment]
Hello, where did you place chromedriver.exe? In the root folder of OB2 or in the bin folder? Because I don't remember which one it is, maybe put it in both places, then restart OB2 and see if it works. Otherwise double check your chromedriver version.

**Comment by slashhesham** [comment]
> Hello, where did you place chromedriver.exe? In the root folder of OB2 or in the bin folder? Because I don't remember which one it is, maybe put it in both places, then restart OB2 and see if it works. Otherwise double check your chromedriver version.

as you probably know chromedriver is no more since chrome version 115, so I'm using the "chrome for testing" app and Im pointing the RL settings to it

**Comment by openbullet** [comment]
I don't think the current version of the selenium lib supports it. You can still download the chromedriver separately at this link I guess https://googlechromelabs.github.io/chrome-for-testing/
