### ISSUE TITLE
[Bug]: CAPSOLVER.COM [BadAuthenticationException]

### ISSUE THREAD

**Issue by CircuitSavage** [openbullet/OpenBullet2#920]
### Version of the software

0.2.5

### Operating system

Win 10 Pro

### Browser / Native

Native

### What happened?

When in debugger, or checking bal at RL settings it works.
But as soon as I press Start, All it does is refresh when it comes to solvecaptcha. It stays there for 0.2s, then bans and redoes. When checking, if I press Check balance this error comes up:
[](https://i.imgur.com/Ae699Fq.png)

When i stop the runner again, and then wait 5s it works again.
This is for the capsolver.com API, solving V3 Enterprise

### Relevant LoliCode if needed

```shell
Not needed.
```

**Comment by nillenalle4** [comment]
Just have to add, if I solve through request blocks on OB1 it works while running this OB2 checker which I find weird.

**Comment by nillenalle4** [comment]
I read that calling their /getbalance API with alot of requests temporary bans the API.
So if you made Disable Balance Check actually work that would be great.

**Comment by openbullet** [comment]
CapSolver is not supported anymore as per their explicit request.
