### ISSUE TITLE
[Bug]: Jobs stucks at start

### ISSUE THREAD

**Issue by completeforyou** [openbullet/OpenBullet2#924]
### Version of the software

0.2.5

### Operating system

Windows 11

### Browser / Native

Native

### What happened?

![Screenshot 2023-08-28 163626](https://github.com/openbullet/OpenBullet2/assets/143455870/fafad454-7d43-4d9a-b85c-43bbe751bda5)
Job not running after click start.
config is running fine in config edit tab

**Comment by kantonise** [comment]
the same bug, any help ?

**Comment by openbullet** [comment]
> the same bug, any help ?

While starting, the startup script is being executed, maybe that's the culprit?
