### ISSUE TITLE
[Bug]: CAN ANYONE PLS HELP

### ISSUE THREAD

**Issue by pipinstallme** [openbullet/OpenBullet2#925]
### Version of the software

0.2.5

### Operating system

Windows 11

### Browser / Native

Native

### What happened?

Please give me the correct WORDLIST TYPE
is it input.USER & input.PASS
or 
input.USERNAME & input.PASSWORD
Well i tried many things nothing seems to work, Default, neither Credentials.

What seems to be the ISSUE here 
**[IDLE] CompilationErrorException: (45,94): error CS1525: Invalid expression term '/'**
![Screenshot 2023-08-30 043241](https://github.com/openbullet/OpenBullet2/assets/143299472/a4306c44-87a7-4cdd-85f3-74b0f3976c47)

Pls pass me the correct WORDLIST TYPE

I am using the original, heck i even re downloaded the Native and extract the Environment.ini and replace with the modified i had
![image](https://github.com/openbullet/OpenBullet2/assets/143299472/3f1c78eb-b6ff-4591-b472-0db40663e870)

**Comment by openbullet** [comment]
Please refer to the docs https://docs.openbullet.dev/docs/wordlists/general-info
