### ISSUE TITLE
[Bug]: IP:PORT:USER:PASS Proxies does not work for capsolver

### ISSUE THREAD

**Issue by CircuitSavage** [openbullet/OpenBullet2#933]
### Version of the software

0.2.5

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Using capsolver API, and enabling proxy for hcaptcha solver gives "host only accepts ip addresses" even though it supports ipportuserpass.

### Relevant LoliCode if needed

```shell
Not needed
```

**Comment by openbullet** [comment]
CapSolver is not supported anymore as per their explicit request.
