### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by pitagoras530** [openbullet/OpenBullet2#939]
Here is what i want

bool passwordtest = Regex.IsMatch(@input.PASS, @"[^a-zA-Z0-9~!@#$%^&*()_+-={}\[\]|\\:;<>,.?/]");
IF BOOLKEY @passwordtest Is true
data.STATUS = "FAIL";
return;
END

a simple ASCII checker for input.DATA which marks the data as fail with a check box or something

**Comment by openbullet** [comment]
![immagine](https://github.com/openbullet/OpenBullet2/assets/48930622/8252a50f-609d-4596-80f7-3f673eb9449f)

You can simply go to the Config > Settings and use a Regex data rule to check this. The feature is already available. You just have to invert your Regex if you want to fail when it matches.
