### ISSUE TITLE
[BUG] problem in monitor section

### ISSUE THREAD

**Issue by beer15** [openbullet/OpenBullet2#94]
i foud a problem in the monitor Actions section > Wait,  there is a display problem, 

and in addition to that the seconds are replaced by minutes, the minutes by hours etc 

tested in windows 10 and windows server 2012

I have a last question, with the monitor, can I pause the runner for example 10 minutes once all the proxies are banned and restart automatically once the 10 minutes are over?
thanks 

![20da964ad2c7b7d8c190e0173fb1156f](https://user-images.githubusercontent.com/50250811/111052017-a4fd0a80-8457-11eb-8fdf-a867e7b396c7.png)

**Comment by openbullet** [comment]
It's just a visual bug as you said, it's supposed to be read as:
Wait X days, Y hours, Z minutes, W seconds. The textboxes are in order in which you read them. But I understand that it's a bit unclear so I'll modify it.

As for the question, you can stop and start the job, there is no pause/resume implemented yet.
