### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nillenalle4** [openbullet/OpenBullet2#941]
### Version of the software

0.2.5

### Operating system

Win 10 Server

### Browser / Native

Native

### What happened?

Suddenly all I receive is "NO_RANDOM_UA_FOUND"
Nothing I do changes it either.
Ive tried different setups, like desktop mobile etc. But same stuff.

**Comment by openbullet** [comment]
This means you don't have any random user agent configured in your settings, and you enabled the random UA from the list provided in settings. Either disable it or put some user agent strings in there.
