### ISSUE TITLE
Upgrade To .net 8

### ISSUE THREAD

**Issue by arshambh** [openbullet/OpenBullet2#956]
Hello
is there any chance to upgrade it to .net 8 ?

**Comment by openbullet** [comment]
Next version will run on .NET 8

**Comment by Gauvino** [comment]
@openbullet if you need a good base on openbullet for the net8 update a friend of mine as make a fork for net8 currently working
https://github.com/WizzardHub/OpenBullet2

**Comment by openbullet** [comment]
@Gauvino don't worry I got it 😄

**Comment by WizzardHub** [comment]
> @openbullet if you need a good base on openbullet for the net8 update a friend of mine as make a fork for net8 currently working https://github.com/WizzardHub/OpenBullet2

It's more of a workaround than a proper fork, but thanks.
