### ISSUE TITLE
need help for moving dll's

### ISSUE THREAD

**Issue by ArchangerOne** [openbullet/OpenBullet2#966]
Hi, sorry if i have posted in wrong section. Just want to figure out how to do to move root folder ll's to subfolder, ex: bin subfolder.

Any help would be appreciated.

Regards

**Comment by openbullet** [comment]
That's not something you should do, I need to do it when linking the assemblies. Hopefully I can manage and the next version will have this.

**Comment by openbullet** [comment]
Next version will be cleaner
