### ISSUE TITLE
Not issue just problem

### ISSUE THREAD

**Issue by relisek** [openbullet/OpenBullet2#969]
Hello,

I didnt want it to post this here but can't find any help with it im desperated.

I cant figure it out for 2 days already

the thing is my target uses NUMBER:PASSWORD as login. I do have NUMBERS.txt and PASSWORDS.txt both in separate files. The question is how do i use them now if i can add only 1 file as a wordlist. All i want it to do is check each number with each password from the list. Anyone can help?

**Comment by yannstkk** [comment]
well, openBullet take combolist as input, the input will be NUMBER:PASSWORD as you said , not NUMBER alone or PASSWORD alone they must be in the same file combo.txt , there are tool to join them with the separator ":" i dont remeber the name of the tool

**Comment by openbullet** [comment]
Use something like this there are a lot of tools that do the same thing and give you a merged combolist https://github.com/destan0098/combolist
