### ISSUE TITLE
The name 'USER' does not exist in the current context

### ISSUE THREAD

**Issue by Aholicknight** [openbullet/OpenBullet2#970]
![msedge_2nKUpECs3v](https://github.com/openbullet/OpenBullet2/assets/7843719/42659856-48e8-4074-8a5e-9abb298a1538)

Hello. I do not understand what is causing this error when I try to create an Openbullet2 config. I am more familiar with OpenBullet, so I assumed it would be the same with OpenBullet2, `<USER>` and `<PASS>`.

Am I doing something wrong? What am I supposed to use instead? Thank you!

**Comment by iLikeCSharp** [comment]
Set the wordlist type to credentials and then the variables are input.USERNAME and input.PASSWORD. https://discourse.openbullet.dev/t/comprehensive-guide-to-wordlist-types/435 guide

**Comment by Aholicknight** [comment]
> Set the wordlist type to credentials and then the variables are input.USERNAME and input.PASSWORD. https://discourse.openbullet.dev/t/comprehensive-guide-to-wordlist-types/435 guide

@iLikeCSharp Thank you!
