### ISSUE TITLE
[REQUEST] What's the variable for the full proxy (IP:PORT:USER:PASS)?

### ISSUE THREAD

**Issue by cryophyte** [openbullet/OpenBullet2#973]
I'm trying to parse the proxy (IP:PORT:USER:PASS) and save them in a file, but I don't know what's the VAR of the proxy, it was available in openbullet1 so I'm wondering why it's not available in openbulelt2

**Comment by openbullet** [comment]
In OB2 you have access to separate things like <data.Proxy.Host>, same for Port, Username and Password. So if you want all of them you are going to have to build the final string yourself, e.g. using a constant string block.

Please refer to the language docs https://discourse.openbullet.dev/t/lolicode-language-documentation/3992
