### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by elmin-suley** [openbullet/OpenBullet2#974]
could you please add the scrappey.com captcha service?

![photo1711894445](https://github.com/openbullet/OpenBullet2/assets/91567290/bc51fc09-50a8-4602-ac04-941313266a60)

**Comment by openbullet** [comment]
By skimming through their docs, I don't see any API that can solve captchas, only one tied to the browser service they provide. Feel free to prove me wrong if you find some docs for a captcha service.
https://wiki.scrappey.com/getting-started
