### ISSUE TITLE
PASS dont match

### ISSUE THREAD

**Issue by tuanhoang224q** [openbullet/OpenBullet2#977]
"I am encountering an issue where the password containing the '&' character does not work. I tried using '<input.PASS>' password=aFpVh2QN4&5UfiZ*r@GY&lang=login.html but it still doesn't work even though the password is correct."
thank you!

**Comment by openbullet** [comment]
You need to URL encode the password since `&` is a reserved characters in URLs meant to join query params. There is a block to do URL encoding, just search for it, give it `input.PASS` as parameter and then use the output variable of that block instead in your URL.
