### ISSUE TITLE
[Bug]: [IDLE] CompilationErrorException: (60,20): error CS1026: ) expected

### ISSUE THREAD

**Issue by svbconfigmaker** [openbullet/OpenBullet2#980]
### Version of the software

0.2.5 Beta

### Operating system

Windows 11

### Browser / Native

Native

### What happened?

A bug happened! 

**[IDLE] CompilationErrorException: (60,20): error CS1026: ) expected**

I tried Default, Credential none of them worked
Also tried to re drag and drop all the files from a new Downloaded archieve (thought my OS realtime threat thing deleted)
but nope everything is good but cannot Debug.

Also tried input.USER , input.USERNAME , input.PASS, input.PASSWORD 
none of them works
keeps giving me the same "**[IDLE] CompilationErrorException: (60,20): error CS1026**"

Also please for god sake tell me why **ENDIF Statement** doesn't work in OB2, how to END the IF & ELSE , ENDIF statement here.

![image](https://github.com/openbullet/OpenBullet2/assets/163485075/f052f131-eb88-4e43-9012-8c8723a43aa0)

**Comment by svbconfigmaker** [comment]
IF "@data.SOURCE" Contains "No packages owned."

BLOCK:ConstantString
  value = "False"
  => CAP @HasPackages
ENDBLOCK

ELSE

BLOCK:ConstantString
  value = "True"
  => CAP @HasPackages
ENDBLOCK

**ENDIF**

![image](https://github.com/openbullet/OpenBullet2/assets/163485075/89b55c33-cbc7-4054-90da-c76431545c8d)

the **ENDIF** ain't working why?
Where are the OB2 Documentation please make one for Github

**Comment by openbullet** [comment]
You're confusing LoliCode with LoliScript. They are two completely different languages. Please refer to the LoliCode docs here https://docs.openbullet.dev/docs/lolicode/statements

I will close this. If you still have trouble, please reopen and post the LoliCode that is giving you trouble, otherwise it's hard to debug the issue.
