### ISSUE TITLE
large number of requests

### ISSUE THREAD

**Issue by tuanhoang224q** [openbullet/OpenBullet2#981]
What do I need to do to get a large number of requests for the posts on my website like this? 
![Capture](https://github.com/openbullet/OpenBullet2/assets/48936356/efad8126-a7c0-4000-be8b-061cb41e040c)
Thank you.
![1](https://github.com/openbullet/OpenBullet2/assets/48936356/d00b4c3f-90d9-4bea-a70e-62aa48df3cc7)

**Comment by openbullet** [comment]
I think you're missing the point. OB2 can only reproduce one of those requests per HTTP block. If you instead want an automated browser, look into the Selenium and Puppeteer blocks.

**Comment by tuanhoang224q** [comment]
So, how can I capture this webpage? Can I use Burp Suite?

**Comment by openbullet** [comment]
You have to use the Selenium or Puppeteer blocks, search for them in Stacker, they will emulate a real browser

**Comment by tuanhoang224q** [comment]
thank you
