### ISSUE TITLE
[Bug]: failed to ssl connect

### ISSUE THREAD

**Issue by Sraczyslaw** [openbullet/OpenBullet2#983]
### Version of the software

all

### Operating system

windows 8.1

### Browser / Native

Custom one and native

### What happened?

Hi! today i was trying to teach some request features but i found some bug, if i try to GET a google for example, its ok, but when i put some mail sites like wp a error pops out, "proxyexception: failed to ssl connect", i never seen that before (i using a OB on new pc, when i was using it before i dont have this) what can i do with it?
![image](https://github.com/openbullet/OpenBullet2/assets/167707234/8d74b8bf-c901-4366-a15a-b0c7ade12763)

### Relevant LoliCode if needed

```shell
BLOCK:HttpRequest
  url = "https://wp.pl"
  TYPE:STANDARD
  $""
  "application/x-www-form-urlencoded"
ENDBLOCK
```

**Comment by openbullet** [comment]
I will close this, please reopen if not solved, or better, update your windows version since 8.1 is really old at this point.
