### ISSUE TITLE
[Bug]: app

### ISSUE THREAD

**Issue by sodon12** [openbullet/OpenBullet2#987]
### Version of the software

i dont have any system

### Operating system

windows

### Browser / Native

chrome

### What happened?

can i get the latest openbullet link i was trying to look for it but i cant find it

### Relevant LoliCode if needed

```shell
can i get the latest openbullet link i was trying to look for it but i cant find it
```

**Comment by openbullet** [comment]
Just go to the releases page or check out the forum, the download link is really easy to find...
