### ISSUE TITLE
Add Async function to nodejs

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#99]
**Describe the bug**
add async function to nodejs

**Solution**
the solution is from the lib https://github.com/JeringTech/Javascript.NodeJS#usage Async function
<img width="917" alt="Screen Shot 2021-03-14 at 5 11 17 PM" src="https://user-images.githubusercontent.com/80313339/111075450-4cc21900-84e8-11eb-8289-225cc981fdbc.png">

**tested and working**
here is the script
<img width="1065" alt="Screen Shot 2021-03-14 at 5 16 26 PM" src="https://user-images.githubusercontent.com/80313339/111075595-04efc180-84e9-11eb-85e5-68b814447196.png">

here is the execution
<img width="1887" alt="Screen Shot 2021-03-14 at 5 17 41 PM" src="https://user-images.githubusercontent.com/80313339/111075631-310b4280-84e9-11eb-81d3-ea2596a6186d.png">

success ===> BOT ENDED AFTER 5123 ms <--- the 5s delay from THE TIMEOUT

**Comment by openbullet** [comment]
To test that this works you can use this LoliCode

```csharp
var x = 1;
var y = 2;

BLOCK:Script
INTERPRETER:NodeJS
INPUT x,y
BEGIN SCRIPT
function delay() {
return new Promise(resolve => setTimeout(() => {
resolve("hello from the promise")
}, 5000))
};

var myString = await delay();
var result = x + y;
END SCRIPT
OUTPUT Int @result
OUTPUT String @myString
ENDBLOCK

LOG result.ToString()
LOG myString
```

**Comment by openbullet** [comment]
Thanks @qMMMp for the amzing work <3
