### ISSUE TITLE
[REQUEST] Save and Restore frequent blocks

### ISSUE THREAD

**Issue by APT-ZERO** [openbullet/OpenBullet2#991]
I made many Blocks and saved them in .txt files
For example a JS block that makes random UUIDv5
When i need it, i must find that .txt file and paste that block or blocks in my current config

You can let us save them in Plugins folder and restore them easier from OB2 blocks

**Comment by openbullet** [comment]
You can already do this via the Snippets feature in OB Settings. Just save a snippet over there and use it in the LoliCode editor. You might need to restart OB2 depending on which client you're using.

**Comment by openbullet** [comment]
You need to write the id of the snippet in the LoliCode editor and it will suggest to add the snippet of code. Then go back to Stacker and you will see the blocks that resulted from the snippet.

**Comment by openbullet** [comment]
Sorry if that's not useful but that's how to do it, and it works.
