### ISSUE TITLE
name 'USER' does not exist in the current context

### ISSUE THREAD

**Issue by mixserrm999** [openbullet/OpenBullet2#992]
![252B7140-F5E4-43CA-AFB1-E44162798E12](https://github.com/openbullet/OpenBullet2/assets/61624005/94949c4a-0491-4411-b0d8-f0f740f17756)

< input.USER > < input.PASS > working 
But 
< USER > < PASS > Not working

**Comment by openbullet** [comment]
This is intended

**Comment by mixserrm999** [comment]
Bro? I have to use input.USER instead of USER, is that correct?

**Comment by mixserrm999** [comment]
> This is intended
Bro? I have to use input.USER instead of USER, is that correct?

**Comment by openbullet** [comment]
Yes, OpenBullet 2 was designed like this. There's no workaround, you just have to adapt to the new way
