### ISSUE TITLE
[Bug]: i keep getting erros and banned and i cant seem to find or open the error log

### ISSUE THREAD

**Issue by 212zz** [openbullet/OpenBullet2#994]
### Version of the software

most recent

### Operating system

win 10

### Browser / Native

Native

### What happened?

i was running a config and i just kept getting errors and banneds i try then to open my error log to see the issue but cant seem to find it
![image](https://github.com/openbullet/OpenBullet2/assets/173623328/ab8692dc-d9dc-4bba-bc02-40f545d66437)

and i think this is where the logs are supposed to be at but theres nothing in that folder
![image](https://github.com/openbullet/OpenBullet2/assets/173623328/8a79941e-8c78-4208-a9ca-faf7918aeb61)

i am new to openbullet

**Comment by openbullet** [comment]
Hello, this is not a bug. Please read this https://discourse.openbullet.dev/t/how-to-debug-ban-error-issues-in-a-job/3055
