### ISSUE TITLE
Input Default Answer fix

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#999]
Rurri can you please fix the new OB2 3.0 so that when you're debugging your config the debugger reads the default input text please.

**Comment by meinname** [comment]
Works for me 🤷 
<img width="920" alt="image" src="https://github.com/openbullet/OpenBullet2/assets/16181408/d92be025-9c98-4288-b981-688eb21f5a4c">

<img width="930" alt="image" src="https://github.com/openbullet/OpenBullet2/assets/16181408/696cbb34-0c98-4cf0-a23a-7c3f6e76a69d">
